gt.bell.nodes = [
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Ferberite",
         "slot":"6",
         "icon":3120,
         "id":7588},
        {"item":"Raw Topaz",
         "slot":"7",
         "icon":3137,
         "id":5149},
        {"item":"Raw Iolite",
         "slot":"8",
         "icon":3137,
         "id":5150},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "stars":2,
     "slot":"6",
     "time":[3],
     "area":"Raubahn's Push",
     "zone":"Northern Thanalan",
     "coords":[17,20],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":236},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Darksteel Ore",
         "slot":"3",
         "icon":3131,
         "id":5121},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[1],
     "area":"Haldrath's March",
     "zone":"Coerthas Central Highlands",
     "coords":[27,19],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":222},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Antumbral Rock",
         "slot":"7",
         "icon":3130,
         "id":8030},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "time":[2],
     "area":"Wellwick Wood",
     "zone":"Eastern Thanalan",
     "coords":[26,18],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":246},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Native Gold",
         "slot":"6",
         "icon":3097,
         "id":7589},
        {"item":"Raw Emerald",
         "slot":"7",
         "icon":3137,
         "id":5148},
        {"item":"Raw Diamond",
         "slot":"8",
         "icon":3137,
         "id":5147},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"6",
     "time":[4],
     "area":"Lost Hope",
     "zone":"Central Thanalan",
     "coords":[25,16],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":237},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Gold Sand",
         "slot":"2",
         "icon":3116,
         "id":5273},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "time":[5],
     "area":"Yugr'am River",
     "zone":"Eastern Thanalan",
     "coords":[25,23],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":226},
    {"type":"Rocky Outcropping",
     "stars":1,
     "items":[
        {"item":"Water Cluster",
         "slot":"5",
         "icon":19,
         "id":19},
        {"item":"Grade 3 Thanalan Topsoil",
         "slot":"8",
         "icon":4646,
         "id":7766},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[5],
     "area":"Hammerlea",
     "zone":"Western Thanalan",
     "name":"Unspoiled",
     "coords":[19,28],
     "uptime":180,
     "lvl":50,
     "id":241},
    {"type":"Rocky Outcropping",
     "stars":1,
     "items":[
        {"item":"Umbral Rock",
         "slot":"7",
         "icon":3130,
         "id":7610},
        {"item":"Grade 3 Shroud Topsoil",
         "slot":"8",
         "icon":4643,
         "id":7763},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[6],
     "area":"Rootslake",
     "zone":"South Shroud",
     "coords":[18,31],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":240},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Gregarious Worm",
         "slot":"1",
         "icon":883,
         "id":10095},
        {"item":"Gold Ore",
         "slot":"6",
         "icon":3129,
         "id":5118},
        {"item":"Coblyn Larva",
         "slot":"7",
         "icon":3700,
         "id":6199},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[9],
     "area":"Burgundy Falls",
     "zone":"Eastern Thanalan",
     "coords":[28,22],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":223},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Grade 4 Carbonized Matter",
         "slot":"1",
         "icon":3410,
         "id":5602},
        {"item":"Lightning Cluster",
         "slot":"2",
         "icon":18,
         "id":18},
        {"item":"Fire Cluster",
         "slot":"3",
         "icon":14,
         "id":14},
        {"item":"Wind Cluster",
         "slot":"4",
         "icon":16,
         "id":16},
        {"item":"Water Cluster",
         "slot":"5",
         "icon":19,
         "id":19},
        {"item":"Ice Cluster",
         "slot":"6",
         "icon":15,
         "id":15},
        {"item":"Earth Cluster",
         "slot":"7",
         "icon":17,
         "id":17},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[13,17,21],
     "area":"North Silvertear",
     "zone":"Mor Dhona",
     "coords":[27,10],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":227},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Volcanic Rock Salt",
         "slot":"1",
         "icon":3375,
         "id":6152},
         {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[17],
     "area":"Raincatcher Gully",
     "zone":"Eastern La Noscea",
     "coords":[18,32],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":224},
    {"type":"Mineral Deposit",
     "stars":2,
     "items":[
        {"item":"Raw Ruby",
         "slot":"7",
         "icon":3137,
         "id":5146},
        {"item":"Raw Sapphire",
         "slot":"8",
         "icon":3137,
         "id":5151},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"7",
     "time":[18],
     "area":"Moraby Bay",
     "zone":"Lower La Noscea",
     "coords":[23,21],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":238},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Fire Cluster",
         "slot":"3",
         "icon":14,
         "id":14},
        {"item":"Grade 3 La Noscean Topsoil",
         "slot":"8",
         "icon":4640,
         "id":7760},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"3",
     "time":[19],
     "area":"Zephyr Drift",
     "zone":"Middle La Noscea",
     "coords":[24,27],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":239},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Astral Rock",
         "slot":"7",
         "icon":3138,
         "id":5158},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[21],
     "area":"Dragonhead",
     "zone":"Coerthas Central Highlands",
     "coords":[23,26],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":225},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Silkworm Cocoon",
         "slot":"4",
         "icon":3259,
         "id":5350},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[1],
     "area":"Little Solace",
     "zone":"East Shroud",
     "coords":[22,26],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":216},
    {"type":"Mature Tree",
     "items":[
        {"item":"Grade 4 Carbonized Matter",
         "slot":"1",
         "icon":3410,
         "id":5602},
        {"item":"Lightning Cluster",
         "slot":"2",
         "icon":18,
         "id":18},
        {"item":"Fire Cluster",
         "slot":"3",
         "icon":14,
         "id":14},
        {"item":"Wind Cluster",
         "slot":"4",
         "icon":16,
         "id":16},
        {"item":"Water Cluster",
         "slot":"5",
         "icon":19,
         "id":19},
        {"item":"Ice Cluster",
         "slot":"6",
         "icon":15,
         "id":15},
        {"item":"Earth Cluster",
         "slot":"7",
         "icon":17,
         "id":17},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"1",
     "time":[1,5,9],
     "area":"North Silvertear",
     "zone":"Mor Dhona",
     "coords":[32,11],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":215},
    {"type":"Mature Tree",
     "items":[
        {"item":"Fragrant Log",
         "slot":"6",
         "icon":3290,
         "id":7611},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":1,
     "time":[2],
     "area":"Upper Paths",
     "zone":"South Shroud",
     "coords":[18,23],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":242},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Shroud Tea Leaves",
         "slot":"6",
         "icon":2876,
         "id":7591},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "time":[2],
     "area":"Sorrel Haven",
     "zone":"Central Shroud",
     "coords":[15,19],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":233},
    {"type":"Mature Tree",
     "items":[
        {"item":"Scarlet Sap",
         "slot":"4",
         "icon":3360,
         "id":7590},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "time":[3],
     "area":"Alder Springs",
     "zone":"North Shroud",
     "coords":[16,28],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":230},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Trillium",
         "slot":"1",
         "icon":3386,
         "id":5545},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "time":[5],
     "area":"The Bramble Patch",
     "zone":"East Shroud",
     "coords":[17,19],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":217},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Honey Lemon Seeds",
         "slot":"1",
         "icon":4633,
         "id":7733},
        {"item":"Honey Lemon",
         "slot":"2",
         "icon":2850,
         "id":6147}],
     "time":[5],
     "area":"Bloodshore",
     "zone":"Eastern La Noscea",
     "coords":[28,32],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":219},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Young Cieldalaes Spinach",
         "slot":"6",
         "icon":2822,
         "id":7594},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "time":[6],
     "area":"Cedarwood",
     "zone":"Lower La Noscea",
     "coords":[32,11],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":235},
    {"type":"Mature Tree",
     "items":[
        {"item":"Redolent Log",
         "slot":"6",
         "icon":3290,
         "id":8031}],
     "stars":2,
     "time":[6],
     "area":"Naked Rock",
     "zone":"Central Shroud",
     "coords":[30,21],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":245},
    {"type":"Mature Tree",
     "items":[
        {"item":"Blood Orange",
         "slot":"2",
         "icon":2848,
         "id":7595},
        {"item":"Bamboo Stick",
         "slot":"6",
         "icon":3273,
         "id":5365},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "slot":"2",
     "time":[7],
     "area":"Bronze Lake",
     "zone":"Upper La Noscea",
     "coords":[29,25],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":232},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"La Noscean Leek",
         "slot":"6",
         "icon":2830,
         "id":7593},
        {"item":"Waterfowl Feather",
         "slot":"?",
         "icon":3260,
         "id":8024},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":2,
     "slot":"6",
     "time":[8],
     "area":"Quarterstone",
     "zone":"Western La Noscea",
     "coords":[34,28],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":234},
    {"type":"Mature Tree",
     "items":[
        {"item":"Apricot",
         "slot":"2",
         "icon":4579,
         "id":7592}],
     "stars":2,
     "time":[9],
     "area":"Summerford",
     "zone":"Middle La Noscea",
     "coords":[19,16],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":231},
    {"type":"Mature Tree",
     "items":[
        {"item":"Spruce Log",
         "slot":"6",
         "icon":3300,
         "id":5395},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[9],
     "area":"Providence Point",
     "zone":"Coerthas Central Highlands",
     "coords":[28,13],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":211},
    {"type":"Mature Tree",
     "items":[
        {"item":"Prickly Pineapple Seeds",
         "slot":"1",
         "icon":4633,
         "id":7734},
        {"item":"Prickly Pineapple",
         "slot":"4",
         "icon":2855,
         "id":4816},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"1",
     "time":[9],
     "area":"Bloodshore",
     "zone":"Eastern La Noscea",
     "coords":[30,27],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":214},
    {"type":"Mature Tree",
     "items":[
        {"item":"Vampire Plant",
         "slot":"8",
         "icon":3379,
         "id":5547}],
     "time":[13],
     "area":"Dragonhead",
     "zone":"Coerthas Central Highlands",
     "coords":[26,22],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":212},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Dzemael Tomato Seeds",
         "slot":"1",
         "icon":4632,
         "id":7724},
        {"item":"Dzemael Tomato",
         "slot":"3",
         "icon":2819,
         "id":6148},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "slot":"1",
     "time":[13],
     "area":"Raincatcher Gully",
     "zone":"Eastern La Noscea",
     "coords":[16,27],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":220},
    {"type":"Mature Tree",
     "items":[
        {"item":"Thavnairian Mistletoe",
         "slot":"2",
         "icon":3379,
         "id":5537}],
     "time":[17],
     "area":"Whitebrim",
     "zone":"Coerthas Central Highlands",
     "coords":[7,11],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":213},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Kidragora",
         "slot":"7",
         "icon":3710,
         "id":6209},
        {"item":"Trillium Bulb",
         "slot":"8",
         "icon":3387,
         "id":5546}],
     "slot":"7",
     "time":[21],
     "area":"The Honey Yard",
     "zone":"East Shroud",
     "coords":[13,23],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":218},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Platinum Ore",
         "slot":"6",
         "icon":3130,
         "id":5120},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":3,
     "time":[4],
     "area":"Broken Water",
     "zone":"Southern Thanalan",
     "coords":[17,9],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":247},
    {"type":"Mature Tree",
     "items":[
        {"item":"Ebony Log",
         "slot":"6",
         "icon":3299,
         "id":5394},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":3,
     "time":[4],
     "area":"Zephyr Drift",
     "zone":"Middle La Noscea",
     "coords":[23,26],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":248},
    {"type":"Mature Tree",
     "items":[
        {"item":"Cypress Log",
         "slot":"6",
         "icon":3290,
         "id":9518},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":3,
     "time":[10],
     "area":"Bentbranch",
     "zone":"Central Shroud",
     "coords":[24,31],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":249},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Pumice",
         "slot":"1",
         "icon":3190,
         "id":9519},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":3,
     "time":[1],
     "area":"Raincatcher Gully",
     "zone":"Eastern La Noscea",
     "coords":[17,26],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":250},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Virgin Basilisk Egg",
         "slot":"6",
         "icon":3195,
         "id":10093},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "stars":4,
     "time":[17],
     "area":"Bluefog",
     "zone":"Northern Thanalan",
     "coords":[23,22],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":252},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Rosemary",
         "slot":"1",
         "icon":3381,
         "id":10096},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "stars":4,
     "time":[17],
     "area":"Nine Ivies",
     "zone":"East Shroud",
     "coords":[23,30],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":251},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Mazlaya Greens",
         "slot":"2",
         "icon":2870,
         "id":10098},
        {"item":"Black Truffle",
         "slot":"7",
         "icon":2839,
         "id":4800},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335},
        {"item":"Unaspected Crystal",
         "slot":"?",
         "icon":3490,
         "id":10099}],
     "time":[13],
     "area":"Drybone",
     "zone":"Eastern Thanalan",
     "coords":[12,15],
     "name":"Unspoiled",
     "uptime":180,
     "lvl":50,
     "id":221},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Chives",
         "collectable":1,
         "slot":"1",
         "icon":7235,
         "id":12884},
        {"item":"Pearl Sprouts",
         "collectable":1,
         "slot":"6",
         "icon":2828,
         "id":12877},
        {"item":"Coerthan Tea Leaves",
         "collectable":1,
         "slot":"7",
         "icon":2876,
         "id":12882}],
     "time":[10,22],
     "zone":"Coerthas Western Highlands",
     "area":"Black Iron Bridge",
     "coords":[31,20],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":55,
     "id":339,
     "condition":"Perception < 377",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Chysahl Greens",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"6",
         "icon":7243,
         "id":12900}],
     "time":[9,21],
     "zone":"Coerthas Western Highlands",
     "area":"Dragonspit",
     "coords":[8,9],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":60,
     "id":344,
     "condition":"Perception < 565",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Yellow Copper Ore",
         "collectable":1,
         "slot":"2",
         "icon":3121,
         "id":5108},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "time":[0,12],
     "zone":"Coerthas Western Highlands",
     "area":"Black Iron Bridge",
     "coords":[29,24],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":50,
     "id":315,
     "condition":"Perception < 304",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Old World Fig",
         "collectable":1,
         "slot":"2",
         "icon":7240,
         "id":12896},
        {"item":"Dark Matter Cluster",
         "slot":"?",
         "icon":5899,
         "id":10335}],
     "time":[2,14],
     "zone":"The Dravanian Forelands",
     "area":"Chocobo Forest",
     "coords":[27,14],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":50,
     "id":340,
     "condition":"Perception < 304",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Chalcocite",
         "collectable":1,
         "slot":"2",
         "icon":3119,
         "id":12941},
        {"item":"Pyrite",
         "collectable":1,
         "slot":"3",
         "icon":3121,
         "id":5109},
        {"item":"Limonite",
         "collectable":1,
         "slot":"4",
         "icon":3124,
         "id":5112}],
     "time":[10,22],
     "zone":"The Dravanian Forelands",
     "area":"Loth ast Vath",
     "coords":[27,17],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":55,
     "id":316,
     "condition":"Perception < 348",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mature Tree",
     "items":[
        {"item":"Heavens Lemon",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"2",
         "icon":2850,
         "id":12889},
        {"item":"Abalathian Mistletoe",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"3",
         "icon":3379,
         "id":12944}],
     "time":[10,22],
     "zone":"The Sea of Clouds",
     "area":"Vundu Ok' Bendu",
     "coords":[34,19],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":60,
     "id":342,
     "condition":"Perception < 489",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Abalathian Rock Salt",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"1",
         "icon":3375,
         "id":12901},
        {"item":"Red Quartz",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"6",
         "icon":3139,
         "id":5159}],
     "time":[0,12],
     "zone":"The Sea of Clouds",
     "area":"Coldwind",
     "coords":[7,7],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":60,
     "id":318,
     "condition":"Perception < 489",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mature Tree",
     "items":[
        {"item":"Dravanian Mistletoe",
         "collectable":1,
         "slot":"3",
         "icon":3379,
         "id":12943},
        {"item":"Porcini",
         "collectable":1,
         "slot":"7",
         "icon":2834,
         "id":12899}],
     "time":[0,12],
     "zone":"The Churning Mists",
     "area":"Easton Eyes",
     "coords":[25,6],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":55,
     "id":341,
     "condition":"Perception < 348",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Yellow Quartz",
         "collectable":1,
         "slot":"4",
         "icon":3142,
         "id":5162},
        {"item":"Green Quartz",
         "collectable":1,
         "slot":"6",
         "icon":3141,
         "id":5161}],
     "time":[2,14],
     "zone":"The Churning Mists",
     "area":"The House of Letters",
     "coords":[35,21],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":55,
     "id":317,
     "condition":"Perception < 377",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mature Tree",
     "items":[
        {"item":"Cloud Banana",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"2",
         "icon":7241,
         "id":12897},
        {"item":"Morel",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"7",
         "icon":7242,
         "id":12898}],
     "time":[0,12],
     "zone":"The Dravanian Hinterlands",
     "area":"The Ruling Quarter",
     "name":"Unspoiled",
     "coords":[19,36],
     "uptime":55,
     "lvl":60,
     "id":343,
     "condition":"Perception < 493",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Cuprite",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"2",
         "icon":3124,
         "id":12942},
        {"item":"Light Kidney Ore",
         "collectable":1,
         "scripName":"Blue Gatherers' Scrip",
         "scripIcon":"t/65028",
         "slot":"3",
         "icon":3124,
         "id":5117}],
     "time":[2,14],
     "zone":"The Dravanian Hinterlands",
     "area":"The Daggers",
     "coords":[35,30],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":60,
     "id":319,
     "condition":"Perception < 493",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Adamantite Ore",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"6",
         "icon":7075,
         "id":12538}],
     "time":[11,23],
     "zone":"Azys Lla",
     "area":"Beta Quadrant",
     "coords":[23,5],
     "name":"Unspoiled",
     "uptime":55,
     "lvl":60,
     "id":320,
     "condition":"Perception < 565",
     "bonus":" Gathering Fortune 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Aurum Regis Ore",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"6",
         "icon":7073,
         "id":12536}],
     "time":[5],
     "zone":"The Churning Mists",
     "area":"Mother of the Sheave",
     "coords":[11,38],
     "name":"Legendary",
     "uptime":55,
     "lvl":60,
     "id":323,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Seventh Heaven",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"1",
         "icon":3386,
         "id":12634}],
     "time":[17],
     "zone":"The Churning Mists",
     "area":"The Lost Landlord",
     "coords":[16,36],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":347,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Snurbleberry",
         "slot":"2",
         "icon":2854,
         "id":12904}],
     "time":[19],
     "zone":"The Dravanian Hinterlands",
     "area":"The Daggers",
     "coords":[39,26],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":349,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Astral Moraine",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"4",
         "icon":3145,
         "id":5226}],
     "time":[5],
     "zone":"Coerthas Western Highlands",
     "area":"Hemlock",
     "coords":[37,16],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":321,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Violet Quartz",
         "slot":"6",
         "icon":3143,
         "id":5163}],
     "time":[7],
     "zone":"Coerthas Western Highlands",
     "area":"The Convictory",
     "name":"Legendary",
     "coords":[11,23],
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":322,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Blue Quartz",
         "slot":"7",
         "icon":3140,
         "id":5160}],
     "time":[7],
     "zone":"The Dravanian Hinterlands",
     "area":"The Answering Quarter",
     "coords":[11,16],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":325,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Sun Mica",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"2",
         "icon":7077,
         "id":12540}],
     "time":[5],
     "zone":"The Sea of Clouds",
     "area":"The Nidifice",
     "coords":[35,39],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":324,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Mineral Deposit",
     "items":[
        {"item":"Red Alumen",
         "slot":"2",
         "icon":7251,
         "id":12945}],
     "time":[7],
     "zone":"Azys Lla",
     "area":"Habisphere Control",
     "coords":[35,16],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":326,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Mature Tree",
     "items":[
        {"item":"Wattle Bark",
         "slot":"5",
         "icon":3368,
         "id":12587}],
     "time":[19],
     "zone":"Azys Lla",
     "area":"Alpha Quadrant",
     "coords":[22,8],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":350,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Mature Tree",
     "items":[
        {"item":"Honeydew Almonds",
         "collectable":1,
         "scripName":"Red Gatherers' Scrip",
         "scripIcon":"t/65029",
         "slot":"2",
         "icon":2877,
         "id":12902}],
     "time":[17],
     "zone":"The Sea of Clouds",
     "area":"The Gauntlet",
     "coords":[24,6],
     "name":"Legendary",
     "uptime":55,
     "stars":1,
     "lvl":60,
     "id":348,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Vanilla Beans",
         "slot":"3",
         "icon":"2869",
         "id":4833}],
     "time":[17],
     "zone":"Coerthas Western Highlands",
     "area":"The Watcher",
     "coords":[23,21],
     "name":"Legendary",
     "uptime":55,
     "lvl":60,
     "id":345,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Dravanian Paprika",
         "slot":"3",
         "icon":2824,
         "id":12902}],
     "time":[19],
     "zone":"Coerthas Western Highlands",
     "area":"The Bed of Bones",
     "coords":[27,33],
     "name":"Legendary",
     "uptime":55,
     "lvl":60,
     "id":346,
     "condition":"Gathering < 600",
     "bonus":" Gathering Rate 0%"},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Highland Oregano",
         "icon":2868,
         "id":12971,
         "collectable":1,
         "reduce":1},
        {"item":"Wind Cluster",
         "icon":16,
         "id":16},
        {"item":"Furymint",
         "slot":"?",
         "icon":2870,
         "id":12972,
         "collectable":1,
         "reduce":1},
        {"item":"Clary Sage",
         "slot":"?",
         "icon":2875,
         "id":12973,
         "collectable":1,
         "reduce":1}],
     "time":[0],
     "zone":"Coerthas Western Highlands",
     "area":"Twinpools",
     "name":"Ephemeral",
     "coords":[10,14],
     "uptime":240,
     "lvl":60,
     "id":329},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Highland Oregano",
         "icon":2868,
         "id":12971,
         "collectable":1,
         "reduce":1},
        {"item":"Wind Cluster",
         "icon":16,
         "id":16},
        {"item":"Furymint",
         "slot":"?",
         "icon":2870,
         "id":12972,
         "collectable":1,
         "reduce":1},
        {"item":"Clary Sage",
         "slot":"?",
         "icon":2875,
         "id":12973,
         "collectable":1,
         "reduce":1}],
     "time":[20],
     "zone":"The Sea of Clouds",
     "area":"The Blue Window",
     "coords":[23,12],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":335},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Highland Oregano",
         "icon":2868,
         "id":12971,
         "collectable":1,
         "reduce":1},
        {"item":"Wind Cluster",
         "icon":16,
         "id":16},
        {"item":"Furymint",
         "slot":"?",
         "icon":2870,
         "id":12972,
         "collectable":1,
         "reduce":1},
        {"item":"Clary Sage",
         "slot":"?",
         "icon":2875,
         "id":12973,
         "collectable":1,
         "reduce":1}],
     "time":[20],
     "zone":"The Sea of Clouds",
     "area":"Voor Sian Siran",
     "coords":[26,35],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":327},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Granular Clay",
         "icon":4644,
         "id":12968,
         "collectable":1,
         "reduce":1},
        {"item":"Earth Cluster",
         "icon":17,
         "id":17},
        {"item":"Peat Moss",
         "slot":"?",
         "icon":4638,
         "id":12969,
         "collectable":1,
         "reduce":1},
        {"item":"Black Soil",
         "slot":"?",
         "icon":4641,
         "id":12970,
         "collectable":1,
         "reduce":1}],
     "time":[8],
     "zone":"The Dravanian Forelands",
     "area":"Avalonia Fallen",
     "coords":[10,32],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":331},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Granular Clay",
         "icon":4644,
         "id":12968,
         "collectable":1,
         "reduce":1},
        {"item":"Earth Cluster",
         "icon":17,
         "id":17},
        {"item":"Peat Moss",
         "slot":"?",
         "icon":4638,
         "id":12969,
         "collectable":1,
         "reduce":1},
        {"item":"Black Soil",
         "slot":"?",
         "icon":4641,
         "id":12970,
         "collectable":1,
         "reduce":1}],
     "time":[16],
     "zone":"The Churning Mists",
     "area":"Four Arms",
     "coords":[20,30],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":333},
    {"type":"Lush Vegetation",
     "items":[
        {"item":"Granular Clay",
         "icon":4644,
         "id":12968,
         "collectable":1,
         "reduce":1},
        {"item":"Earth Cluster",
         "icon":17,
         "id":17},
        {"item":"Peat Moss",
         "slot":"?",
         "icon":4638,
         "id":12969,
         "collectable":1,
         "reduce":1},
        {"item":"Black Soil",
         "slot":"?",
         "icon":4641,
         "id":12970,
         "collectable":1,
         "reduce":1}],
     "time":[4],
     "zone":"The Dravanian Hinterlands",
     "area":"The Answering Quarter",
     "coords":[13,19],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":337},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Lightning Moraine",
         "icon":3143,
         "id":5218,
         "collectable":1,
         "reduce":1},
        {"item":"Radiant Lightning Moraine",
         "icon":3143,
         "id":5224,
         "slot":"?",
         "collectable":1,
         "reduce":1},
        {"item":"Bright Lightning Rock",
         "icon":7252,
         "id":12967,
         "slot":"?",
         "collectable":1,
         "reduce":1}],
     "time":[20],
     "zone":"Coerthas Western Highlands",
     "area":"Red Rim",
     "coords":[21,28],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":305},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Lightning Moraine",
         "icon":3143,
         "id":5218,
         "collectable":1,
         "reduce":1},
        {"item":"Radiant Lightning Moraine",
         "icon":3143,
         "id":5224,
         "slot":"?",
         "collectable":1,
         "reduce":1},
        {"item":"Bright Lightning Rock",
         "icon":7252,
         "id":12967,
         "slot":"?",
         "collectable":1,
         "reduce":1}],
     "time":[16],
     "zone":"The Sea of Clouds",
     "area":"Voor Sian Siran",
     "coords":[34,30],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":313},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Fire Moraine",
         "icon":3139,
         "id":5214,
         "collectable":1,
         "reduce":1},
        {"item":"Bright Fire Rock",
         "icon":7087,
         "id":12966,
         "slot":"?",
         "collectable":1,
         "reduce":1},
        {"item":"Radiant Fire Moraine",
         "icon":3139,
         "id":5220,
         "slot":"?",
         "collectable":1,
         "reduce":1}],
     "time":[4],
     "zone":"The Dravanian Forelands",
     "area":"Avalonia Fallen",
     "coords":[17,27],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":307},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Fire Moraine",
         "icon":3139,
         "id":5214,
         "collectable":1,
         "reduce":1},
        {"item":"Bright Fire Rock",
         "icon":7087,
         "id":12966,
         "slot":"?",
         "collectable":1,
         "reduce":1},
        {"item":"Radiant Fire Moraine",
         "icon":3139,
         "id":5220,
         "slot":"?",
         "collectable":1,
         "reduce":1}],
     "time":[12],
     "zone":"The Churning Mists",
     "area":"Landlord Colony",
     "coords":[29,19],
     "name":"Ephemeral",
     "uptime":240,
     "lvl":60,
     "id":311},
    {"type":"Rocky Outcropping",
     "items":[
        {"item":"Fire Moraine",
         "icon":3139,
         "id":5214,
         "collectable":1,
         "reduce":1},
        {"item":"Bright Fire Rock",
         "icon":7087,
         "id":12966,
         "slot":"?",
         "collectable":1,
         "reduce":1},
        {"item":"Radiant Fire Moraine",
         "icon":3139,
         "id":5220,
         "slot":"?",
         "collectable":1,
         "reduce":1}],
     "time":[8],
     "zone":"The Dravanian Hinterlands",
     "area":"The Makers' Quarter",
     "name":"Ephemeral",
     "coords":[26,24],
     "uptime":240,
     "lvl":60,
     "id":309}]