ignore:
  - user
  - eslint

parsers:
  javascript:
    enable_partials: yes

coverage:
  status:
    project:
      resources:
        paths:
          - resources
      triggers:
        paths:
          - ui/raidboss/data
