yarnPath: .yarn/releases/yarn-3.0.2.cjs
nodeLinker: node-modules

# polyfill some packages that didn't declare peer dependencies
packageExtensions:
  "debug@*":
    dependencies:
      supports-color: "*"
