cacheFolder: ./.yarn/cache

nodeLinker: pnp

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
