import { Responses } from '../../../../../resources/responses';
import ZoneId from '../../../../../resources/zone_id';
import { RaidbossData } from '../../../../../types/data';
import { TriggerSet } from '../../../../../types/trigger';

  // all Masked Carnivale Stages/Acts take place in the same zone
  // 01|2022-11-01T12:26:48.9250000-04:00|31C|All's Well That Starts Well|
  // 0x31C = 796 = ZoneId.AllsWellThatStartsWell
  // there are unique Instance Content IDs for each Masked Carnivale Stage
  // first Instance Content ID appearance is an Actor Control (0x21 = 33) line
  // 33|2022-11-01T12:26:52.0770000-04:00|800388BB|40000001|708|00|00|00|
  // 0x40000001 = Initial Commence, 0x708 = 1800s = 30m = lockout time
  // 0x8003 = instance content update, 0x88BB = 35003 = InstanceContentType
  // https://xivapi.com/InstanceContent/35003?pretty=true (Waiting for Golem)
  // Masked Carnivale missing from cactbot/resources/content_list.ts
  // Masked Carnivale info not auto-generated by cactbot/util/gen_zone_id_and_info.py
  // Masked Carnivale missing from cactbot/resources/zone_info.ts (auto-generated)
  // Masked Carnivale missing from cactbot/resources/content_type.ts (auto-generated)

export type Data = RaidbossData;

const triggerSet: TriggerSet<Data> = {
  zoneId: ZoneId.AllsWellThatStartsWell,

  triggers: [
    // ---------------- Stage 01 Act 1 ----------------
    // ---------------- Stage 02 Act 1 ----------------
    // ---------------- Stage 02 Act 2 ----------------
    // ---------------- Stage 03 Act 1 ----------------
    // ---------------- Stage 04 Act 1 ----------------
    // ---------------- Stage 04 Act 2 ----------------
    // ---------------- Stage 05 Act 1 ----------------
    // ---------------- Stage 06 Act 1 ----------------
    // ---------------- Stage 06 Act 2 ----------------
    // ---------------- Stage 07 Act 1 ----------------
    // ---------------- Stage 07 Act 2 ----------------
    // ---------------- Stage 07 Act 3 ----------------
    // ---------------- Stage 08 Act 1 ----------------
    // ---------------- Stage 08 Act 2 ----------------
    // ---------------- Stage 09 Act 1 ----------------
    // ---------------- Stage 10 Act 1 ----------------
    // ---------------- Stage 11 Act 1 ----------------
    // ---------------- Stage 11 Act 2 ----------------
    // ---------------- Stage 12 Act 1 ----------------
    // ---------------- Stage 12 Act 2 ----------------
    // ---------------- Stage 13 Act 1 ----------------
    // ---------------- Stage 13 Act 2 ----------------
    // ---------------- Stage 14 Act 1 ----------------
    // ---------------- Stage 14 Act 2 ----------------
    // ---------------- Stage 15 Act 1 ----------------
    // ---------------- Stage 16 Act 1 ----------------
    // ---------------- Stage 16 Act 2 ----------------
    // ---------------- Stage 17 Act 1 ----------------
    // ---------------- Stage 17 Act 2 ----------------
    // ---------------- Stage 18 Act 1 ----------------
    // ---------------- Stage 18 Act 2 ----------------
    // ---------------- Stage 19 Act 1 ----------------
    // ---------------- Stage 19 Act 2 ----------------
    // ---------------- Stage 20 Act 1 ----------------
    // ---------------- Stage 20 Act 2 ----------------
    // ---------------- Stage 20 Act 3 ----------------
    // ---------------- Stage 21 Act 1 ----------------
    // ---------------- Stage 21 Act 2 ----------------
    // ---------------- Stage 22 Act 1 ----------------
    // ---------------- Stage 22 Act 2 ----------------
    // ---------------- Stage 23 Act 1 ----------------
    // ---------------- Stage 24 Act 1 ----------------
    // ---------------- Stage 24 Act 2 ----------------
    // ---------------- Stage 24 Act 3 ----------------
    // ---------------- Stage 25 Act 1 ----------------
    // ---------------- Stage 25 Act 2 ----------------
    // ---------------- Stage 25 Act 3 ----------------
    // ---------------- Stage 26 Act 1 ----------------
    // ---------------- Stage 26 Act 2 ----------------
    // ---------------- Stage 27 Act 1 ----------------
    // ---------------- Stage 28 Act 1 ----------------
    // ---------------- Stage 29 Act 1 ----------------
    {
      id: 'Carnivale S29 A1 Pyre Fluid Swing',
      type: 'StartsUsing',
      netRegex: { id: '4901', source: 'Shikigami of the Pyre' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 29 Act 2 ----------------
    {
      id: 'Carnivale S29 A2 Undertow Fluid Swing',
      type: 'StartsUsing',
      netRegex: { id: '4A11', source: 'Shikigami of the Undertow' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 30 Act 1 ----------------
    // ---------------- Stage 30 Act 2 ----------------
    // ---------------- Stage 30 Act 3 ----------------
    // ---------------- Stage 31 Act 1 ----------------
    // ---------------- Stage 31 Act 2 ----------------
  ],
};

export default triggerSet;
