Options.Triggers.push({
  id: 'TheAetherfont',
  zoneId: ZoneId.TheAetherfont,
  timelineFile: 'aetherfont.txt',
  triggers: [
    {
      id: 'Aetherfont Lyngbakr Upsweep',
      type: 'StartsUsing',
      netRegex: { id: '823A', source: 'Lyngbakr', capture: false },
      response: Responses.aoe(),
    },
    {
      id: 'Aetherfont Lyngbakr Bodyslam',
      type: 'StartsUsing',
      netRegex: { id: '8237', source: 'Lyngbakr', capture: false },
      response: Responses.aoe(),
    },
    {
      id: 'Aetherfont Lyngbakr Tidal Breath',
      type: 'StartsUsing',
      netRegex: { id: '8240', source: 'Lyngbakr', capture: false },
      response: Responses.getBehind(),
    },
    {
      id: 'Aetherfont Lyngbakr Floodstide',
      type: 'StartsUsing',
      netRegex: { id: '823D', source: 'Lyngbakr', capture: false },
      // 00600 spread headmarkers come out after cast ends
      durationSeconds: 8,
      response: Responses.spread(),
    },
    {
      id: 'Aetherfont Lyngbakr Tidalspout',
      type: 'StartsUsing',
      netRegex: { id: '823F', source: 'Lyngbakr' },
      response: Responses.stackMarkerOn(),
    },
    {
      id: 'Aetherfont Lyngbakr Sonic Bloop',
      type: 'StartsUsing',
      netRegex: { id: '8241', source: 'Lyngbakr' },
      response: Responses.tankBuster(),
    },
    {
      // Initial battle cry is just aoe, the later ones create a ring.
      id: 'Aetherfont Arkas Battle Cry Initial',
      type: 'StartsUsing',
      netRegex: { id: '872D', source: 'Arkas', capture: false },
      response: Responses.aoe(),
    },
    {
      // aoe + ring
      id: 'Aetherfont Arkas Battle Cry',
      type: 'StartsUsing',
      netRegex: { id: '8254', source: 'Arkas', capture: false },
      alertText: (_data, _matches, output) => output.text(),
      outputStrings: {
        text: {
          en: 'aoe + Get Middle',
          de: 'AoE + Geh in die Mitte',
          fr: 'AoE + Allez au milieu',
          cn: 'AoE + 场边招雷',
          ko: '전체공격 + 중앙으로',
        },
      },
    },
    {
      id: 'Aetherfont Arkas Ripper Claw',
      type: 'StartsUsing',
      netRegex: { id: '8258', source: 'Arkas' },
      response: Responses.tankBuster(),
    },
    {
      id: 'Aetherfont Arkas Lightning Claw',
      type: 'StartsUsing',
      netRegex: { id: '8798', source: 'Arkas' },
      response: Responses.stackMarkerOn(),
    },
    {
      id: 'Aetherfont Arkas Electrify',
      type: 'Ability',
      // 8256 is the damage ability for Lightning Claw, which is followed by a centered aoe.
      netRegex: { id: '8256', source: 'Arkas', capture: false },
      suppressSeconds: 5,
      response: Responses.getOut(),
    },
    {
      id: 'Aetherfont Octomammoth Tidal Roar',
      type: 'StartsUsing',
      netRegex: { id: '824C', source: 'Octomammoth', capture: false },
      response: Responses.aoe(),
    },
    {
      // aoe + ring
      id: 'Aetherfont Octomammoth Saline Spit',
      type: 'StartsUsing',
      netRegex: { id: '8248', source: 'Octomammoth', capture: false },
      alertText: (_data, _matches, output) => output.text(),
      outputStrings: {
        text: {
          en: 'Stand Between Platforms',
          de: 'Steh zwischen den Platformen',
          fr: 'Restez entre les plateformes',
          cn: '站在平台间',
          ko: '플랫폼 사이로',
        },
      },
    },
    {
      id: 'Aetherfont Octomamoth Water Drop',
      type: 'StartsUsing',
      netRegex: { id: '8684', source: 'Octomammoth' },
      condition: Conditions.targetIsYou(),
      response: Responses.spread(),
    },
    {
      id: 'Aetherfont Octomammoth Tidal Breath',
      type: 'StartsUsing',
      netRegex: { id: '824A', source: 'Octomammoth', capture: false },
      response: Responses.getBehind(),
    },
    {
      id: 'Aetherfont Octomammoth Breathstroke',
      type: 'StartsUsing',
      netRegex: { id: '86F7', source: 'Octomammoth', capture: false },
      alertText: (_data, _matches, output) => output.text(),
      outputStrings: {
        text: {
          en: 'Get Behind (Avoid Tentacles)',
          de: 'Geh nach Hinten (Vermeide Tentakel)',
          fr: 'Allez derrière (évitez les tentacules)',
          cn: '去背后（远离触手）',
          ko: '보스 뒤로 (촉수 피하기)',
        },
      },
    },
  ],
  timelineReplace: [
    {
      'locale': 'de',
      'replaceSync': {
        'Arkas': 'Arkas',
        'Cyancap Cavern': 'Zyanspitze',
        'Lyngbakr': 'Lyngbakr',
        'Mammoth Tentacle': 'Oktomammut-Tentakel',
        'Octomammoth': 'Oktomammut',
        'The Deep Below': 'Ätherpfuhl',
        'The Landfast Floe': 'Raureif-Rondell',
      },
      'replaceText': {
        '\\(big\\)': '(groß)',
        '\\(small\\)': '(klein)',
        '\\(explosion\\)': '(Explosion)',
        '\\(tether\\)': '(Verbindung)',
        'Battle Cry': 'Kampfesschrei',
        'Body Slam': 'Bodenwelle',
        'Breathstroke': 'Hauchiger Hieb',
        'Clearout': 'Kreisfeger',
        'Electric Eruption': 'Blitzeruption',
        'Electrify': 'Elektrisieren',
        'Explosive Frequency': 'Explosivfrequenz',
        'Floodstide': 'Flutzeit',
        'Forked Fissures': 'Funkenstrom',
        'Lightning Claw': 'Funkenklaue',
        'Lightning Leap': 'Funkensprung',
        'Lightning Rampage': 'Funkensturm',
        'Octostroke': 'Oktoschlag',
        'Resonant Frequency': 'Resonanzfrequenz',
        'Ripper Claw': 'Fetzklaue',
        'Saline Spit': 'Spuckstrahl',
        'Shock': 'Entladung',
        'Sonic Bloop': 'Ruf aus der Tiefe',
        'Spinning Claw': 'Wirbelklaue',
        'Spun Lightning': 'Blitzgespinst',
        'Tidal Breath': 'Hauch der Gezeiten',
        'Tidal Roar': 'Schrei der Gezeiten',
        'Tidalspout': 'Wassersturm',
        'Upsweep': 'Aufbrecher',
        'Vivid Eyes': 'Wilde Augen',
        'Water Drop': 'Rauschendes Wasser',
        'Waterspout': 'Wasserhose',
      },
    },
    {
      'locale': 'fr',
      'missingTranslations': true,
      'replaceSync': {
        'Arkas': 'Arkas',
        'Cyancap Cavern': 'Caverne de Cap-cyan',
        'Lyngbakr': 'Lyngbakr',
        'Mammoth Tentacle': 'bras d\'octomammouth',
        'Octomammoth': 'octomammouth',
        'The Deep Below': 'Bassin éthéré',
        'The Landfast Floe': 'Cirque glacé',
      },
      'replaceText': {
        'Battle Cry': 'Cri de guerre',
        'Body Slam': 'Charge physique',
        'Breathstroke': 'Souffle et fauche',
        'Clearout': 'Fauchage',
        'Electric Eruption': 'Éruption d\'éclairs',
        'Electrify': 'Électrisation',
        'Explosive Frequency': 'Grande explosion résonante',
        'Floodstide': 'Marée montante',
        'Forked Fissures': 'Flux foudroyant',
        'Lightning Claw': 'Griffe survoltée',
        'Lightning Leap': 'Bond électrique',
        'Lightning Rampage': 'Ravage tonitruant',
        'Octostroke': 'Octofauche',
        'Resonant Frequency': 'Explosion résonante',
        'Ripper Claw': 'Griffe éventreuse',
        'Saline Spit': 'Crachat aqueux',
        'Shock': 'Décharge électrostatique',
        'Sonic Bloop': 'Bloup sonique',
        'Spinning Claw': 'Griffe tournoyante',
        'Spun Lightning': 'Rayon fulgurant',
        'Tidal Breath': 'Souffle supratidal',
        'Tidal Roar': 'Vague rugissante',
        'Tidalspout': 'Déferlement soudain',
        'Upsweep': 'Écho sinistre',
        'Vivid Eyes': 'Regard transperçant',
        'Water Drop': 'Boule d\'eau',
        'Waterspout': 'Inondation',
      },
    },
    {
      'locale': 'ja',
      'missingTranslations': true,
      'replaceSync': {
        'Arkas': 'アルカス',
        'Cyancap Cavern': 'シアンキャップ中継地',
        'Lyngbakr': 'リングバーク',
        'Mammoth Tentacle': 'オクトマンモスの腕',
        'Octomammoth': 'オクトマンモス',
        'The Deep Below': 'エーテリックポンド',
        'The Landfast Floe': '流氷の円庭',
      },
      'replaceText': {
        'Battle Cry': 'バトルクライ',
        'Body Slam': 'ボディスラム',
        'Breathstroke': 'ブレス&スワイプ',
        'Clearout': 'なぎ払い',
        'Electric Eruption': 'ライトニングエラプション',
        'Electrify': '大放電',
        'Explosive Frequency': '共振大炸裂',
        'Floodstide': 'フラッドタイド',
        'Forked Fissures': 'ライトニングカレント',
        'Lightning Claw': 'ライトニングクロウ',
        'Lightning Leap': 'ライトニングリープ',
        'Lightning Rampage': 'ライトニングランページ',
        'Octostroke': 'オクトスワイプ',
        'Resonant Frequency': '共振炸裂',
        'Ripper Claw': 'リッパークロウ',
        'Saline Spit': 'スピットウォーター',
        'Shock': '放電',
        'Sonic Bloop': 'ソニックブループ',
        'Spinning Claw': 'スピニングクロウ',
        'Spun Lightning': 'スパンライトニング',
        'Tidal Breath': 'タイダルブレス',
        'Tidal Roar': 'タイダルロア',
        'Tidalspout': 'バーストフラッド',
        'Upsweep': 'アプスウィープ',
        'Vivid Eyes': 'ビビッドアイズ',
        'Water Drop': '水塊',
        'Waterspout': 'オーバーフラッド',
      },
    },
  ],
});
