Options.Triggers.push({
    zoneId: ZoneId.TheTowerOfBabil,
    timelineFile: 'the_tower_of_babil.txt',
    triggers: [],
    timelineReplace: [
        {
            'locale': 'de',
            'replaceSync': {
                'Anima': 'Anima',
                'Barnabas': 'Barnabas',
                'Iron Nail': 'Animas Bosheit',
                'Iron Womb': 'Eiserner Wanst',
                'Lugae': 'Lugae',
                'Magitek Chakram': 'Magitek-Chakram',
                'Magitek Explosive': 'Magiebombe',
                'Magitek Servicing': 'Magitek-Wartungsdepot',
                'Martial Conditioning': 'Kampfhalle',
                'Mega-graviton': 'Mega-Graviton',
                'Thunderball': 'Donnerkugel',
            },
            'replaceText': {
                'Aetherial Pull': 'Seidige Finger',
                'Boundless Pain': 'Grenzenloser Schmerz',
                'Charnel Claw': 'Laserklaue',
                'Coffin Scratch': 'Flüchtiges Scharren',
                'Downpour': 'Flutschwall',
                'Dynamic Pound': 'Elektromagnetische Erderschütterung',
                'Dynamic Scrapline': 'Elektromagnetische Rollschlinge',
                'Electromagnetic Release': 'Elektromagnetische Entladung',
                'Erupting Pain': 'Schmerzeruption',
                'Explosion': 'Explosion',
                'Graviton Spark': 'Gravitonfunke',
                'Ground and Pound': 'Erderschütterung',
                'Imperatum': 'Imperator',
                'Lunar Nail': 'Dunkle Fessel',
                'Magitek Chakram': 'Magitek-Chakram',
                'Magitek Explosive': 'Magiebombe',
                'Magitek Missile': 'Magitek-Rakete',
                'Magitek Ray': 'Magitek-Laser',
                'Mega Graviton': 'Mega-Graviton',
                'Mighty Blow': 'Säulendurchschlag',
                'Obliviating Claw': 'Klaue des Vergessens',
                'Oblivion': 'Chaosdimension',
                'Pater Patriae': 'Pater patriae',
                'Phantom Pain': 'Phantomschmerz',
                'Rolling Scrapline': 'Rollschlinge',
                'Shock(?!ing)': 'Entladung',
                'Shocking Force': 'Starkstromentladung',
                'Surface Missile': 'Raketenschlag',
                'Thermal Suppression': 'Massiver Beschuss',
                'Thundercall': 'Donnerruf',
            },
        },
        {
            'locale': 'fr',
            'replaceSync': {
                'Anima': 'Anima',
                'Barnabas': 'Barnabas',
                'Iron Nail': 'griffe d\'Anima',
                'Iron Womb': 'Cœur de Fer',
                'Lugae': 'Lugae',
                'Magitek Chakram': 'Chakram magitek',
                'Magitek Explosive': 'Bombe magitek',
                'Magitek Servicing': 'Entrepôt de maintenance magitek',
                'Martial Conditioning': 'Hall d\'entraînement',
                'Mega-graviton': 'méga graviton',
                'Thunderball': 'sphère de foudre',
            },
            'replaceText': {
                'Aetherial Pull': 'Aspiration',
                'Boundless Pain': 'Lamento',
                'Charnel Claw': 'Griffes nécrosantes',
                'Coffin Scratch': 'Griffes sépulcrales',
                'Downpour': 'Déluge',
                'Dynamic Pound': 'Frappe terrestre électromagnétique',
                'Dynamic Scrapline': 'Lariat tournoyant électromagnétique',
                'Electromagnetic Release': 'Décharge électromagnétique',
                'Erupting Pain': 'Éruption torturante',
                'Explosion': 'Explosion',
                'Graviton Spark': 'Étincelle graviton',
                'Ground and Pound': 'Frappe terrestre',
                'Imperatum': 'Imperator',
                'Lunar Nail': 'Pals grotesques',
                'Magitek Chakram': 'Chakram magitek',
                'Magitek Explosive': 'Bombe magitek',
                'Magitek Missile': 'Missiles magitek',
                'Magitek Ray': 'Rayon magitek',
                'Mega Graviton': 'Méga graviton',
                'Mighty Blow': 'Empalement',
                'Obliviating Claw': 'Griffes du néant',
                'Oblivion': 'Ruée chaotique',
                'Pater Patriae': 'Pater Patriae',
                'Phantom Pain': 'Supplice fantôme',
                'Rolling Scrapline': 'Lariat tournoyant',
                'Shock(?!ing)': 'Décharge électrostatique',
                'Shocking Force': 'Décharge à haute tension',
                'Surface Missile': 'Missiles sol-sol',
                'Thermal Suppression': 'Surcharge incendiaire',
                'Thundercall': 'Drain fulminant',
            },
        },
        {
            'locale': 'ja',
            'replaceSync': {
                'Anima': 'アニマ',
                'Barnabas': 'バルナバ',
                'Iron Nail': 'アニマの爪',
                'Iron Womb': '鉄の肚',
                'Lugae': 'ルゲイエ',
                'Magitek Chakram': '魔導チャクラム',
                'Magitek Explosive': '魔導爆弾',
                'Magitek Servicing': '魔導整備庫',
                'Martial Conditioning': '武術訓練ホール',
                'Mega-graviton': 'メガグラビトン',
                'Thunderball': 'サンダースフィア',
            },
            'replaceText': {
                'Aetherial Pull': '吸引',
                'Boundless Pain': 'バウンドレスペイン',
                'Charnel Claw': 'チャーネルクロウ',
                'Coffin Scratch': 'コフィンスクラッチ',
                'Downpour': '水責め',
                'Dynamic Pound': '超電磁グラウンドパンチ',
                'Dynamic Scrapline': '超電磁ローリングラリアット',
                'Electromagnetic Release': '電磁放射',
                'Erupting Pain': 'ペインエラプション',
                'Explosion': '爆発',
                'Graviton Spark': 'グラビトンスパーク',
                'Ground and Pound': 'グラウンドパンチ',
                'Imperatum': 'インペラトル',
                'Lunar Nail': '異形の楔',
                'Magitek Chakram': '魔導チャクラム',
                'Magitek Explosive': '魔導爆弾',
                'Magitek Missile': '魔導ミサイル',
                'Magitek Ray': '魔導レーザー',
                'Mega Graviton': 'メガグラビトン',
                'Mighty Blow': '激突',
                'Obliviating Claw': 'オブリビオンクロウ',
                'Oblivion': 'カオティック・ディメンション',
                'Pater Patriae': 'パテル・パトリアエ',
                'Phantom Pain': 'ファントムペイン',
                'Rolling Scrapline': 'ローリングラリアット',
                'Shock(?!ing)': '放電',
                'Shocking Force': '高電圧放電',
                'Surface Missile': '対地ミサイル',
                'Thermal Suppression': '火力制圧',
                'Thundercall': '招雷',
            },
        },
    ],
});
