'use strict';

let gBossFightTriggers = [
  {
    id: 'test',
    zoneRegex: /^Middle La Noscea$/,
    startRegex: /:You bow courteously to the striking dummy/,
    endRegex: /:You bid farewell to the striking dummy/,
    countdownStarts: true,
  },
  {
    id: 'o1s',
    zoneRegex: /^Deltascape V1.0 \(Savage\)$/,
    startRegex: /:Alte Roite uses Wyrm Tail/,
    endRegex: /:Alte Roite was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o2s',
    zoneRegex: /^Deltascape V2.0 \(Savage\)$/,
    startRegex: /:Catastrophe uses Earthquake/,
    endRegex: /:Catastrophe was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o3s',
    zoneRegex: /^Deltascape V3.0 \(Savage\)$/,
    startRegex: /:Halicarnassus uses Critical Hit/,
    endRegex: /:Halicarnassus was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o4s-exdeath',
    zoneRegex: /^Deltascape V4.0 \(Savage\)$/,
    startRegex: /:Exdeath uses Dualcast/,
    endRegex: /:The limit gauge resets!/,
    countdownStarts: false,
  },
  {
    id: 'o4s-neo',
    zoneRegex: /^Deltascape V4.0 \(Savage\)$/,
    startRegex: /:Neo Exdeath uses Almagest/,
    endRegex: /:Neo Exdeath is defeated/,
    countdownStarts: false,
  },
  {
    id: 'Unending Coil',
    zoneRegex: /^The Unending Coil Of Bahamut \(Ultimate\)$/,
    startRegex: /:Twintania:26A7:/,
    endRegex: /Removing combatant Bahamut Prime\.  Max HP: 13751450\./,
    countdownStarts: true,
  },
  {
    id: 'Shinryu Ex',
    zoneRegex: /^The Minstrel's Ballad: Shinryu's Domain$/,
    startRegex: /:Shinryu starts using Earthen Fury/,
    endRegex: /Removing combatant Shinryu\.  Max HP: 17167557\./,
    countdownStarts: true,
  },
  {
    id: 'o5s',
    zoneRegex: /Sigmascape V1\.0 \(Savage\)/,
    startRegex: /:Wroth Ghost:28B6:/,
    endRegex: /:Phantom Train was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o6s',
    zoneRegex: /Sigmascape V2\.0 \(Savage\)/,
    startRegex: /14:2829:Demon Chadarnook starts using Demonic Shear/,
    endRegex: /:Demon Chadarnook was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o7s',
    zoneRegex: /Sigmascape V3\.0 \(Savage\)/,
    startRegex: /00:0044:WEAPON SYSTEMS ONLINE/,
    endRegex: /:Guardian was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'o8s-kefka',
    zoneRegex: /Sigmascape V4\.0 \(Savage\)/,
    startRegex: / 15:........:Kefka:28C2:/,
    endRegex: /:Kekfa was defeated by/,
    countdownStarts: false,
  },
  {
    id: 'o8s-god kefka',
    zoneRegex: /Sigmascape V4\.0 \(Savage\)/,
    startRegex: / 15:........:Kefka:28EC:/,
    endRegex: /:Kekfa was defeated by/,
    countdownStarts: false,
  },
  {
    id: 'Byakko Ex',
    zoneRegex: /^The Jade Stoa \(Extreme\)$/,
    startRegex: /:Byakko starts using Storm Pulse/,
    endRegex: /:Byakko was defeated by/,
    countdownStarts: true,
  },
  {
    id: 'Tsukuyomi Ex',
    zoneRegex: /The Minstrel's Ballad: Tsukuyomi's Pain/,
    startRegex: /:Tsukuyomi:2BBA:/,
    endRegex: /:Removing combatant Tsukuyomi/,
    countdownStarts: true,
  },
  {
    id: 'UwU',
    zoneRegex: /^(The Weapon's Refrain \(Ultimate\)|Unknown Zone \(309\))$/,
    startRegex: /:Garuda:2B53:/,
    endRegex: /Removing combatant The Ultima Weapon\.  Max HP: \d{8}\./,
    countdownStarts: true,
  },
];
