'use strict';

let gBossFightTriggers = [
  {
    id: 'test',
    zoneRegex: /^(Middle La Noscea|中拉诺西亚)$/,
    startRegex: /(:You bow courteously to the striking dummy|恭敬地对木人行礼)/,
    endRegex: /(:You bid farewell to the striking dummy|向木人告别)/,
    countdownStarts: true,
  },
  {
    id: 'o1s',
    zoneRegex: /^(Deltascape V1.0 \(Savage\)|欧米茄零式时空狭缝 \(德尔塔幻境1\))$/,
    startRegex: /:(Alte Roite uses Wyrm Tail|老者 uses 太古龙尾)/,
    countdownStarts: true,
  },
  {
    id: 'o2s',
    zoneRegex: /^(Deltascape V2.0 \(Savage\)|欧米茄零式时空狭缝 \(德尔塔幻境2\))$/,
    startRegex: /:(Catastrophe uses Earthquake|灾变者 uses (大*)地震)/,
    countdownStarts: true,
  },
  {
    id: 'o3s',
    zoneRegex: /^(Deltascape V3.0 \(Savage\)|欧米茄零式时空狭缝 \(德尔塔幻境3\))$/,
    startRegex: /:(Halicarnassus uses Critical Hit|哈利卡纳苏斯 uses 暴击)/,
    countdownStarts: true,
  },
  {
    id: 'o4s-exdeath',
    zoneRegex: /^(Deltascape V4.0 \(Savage\)|欧米茄零式时空狭缝 \(德尔塔幻境4\))$/,
    startRegex: /:(Exdeath uses Dualcast|艾克斯迪司 uses 连续咏唱)/,
    endRegex: /:The limit gauge resets!/,
    countdownStarts: false,
  },
  {
    id: 'o4s-neo',
    zoneRegex: /^(Deltascape V4.0 \(Savage\)|欧米茄零式时空狭缝 \(德尔塔幻境4\))$/,
    startRegex: /:(Neo Exdeath|新生艾克斯迪司) uses (Almagest|至高无上)/,
    countdownStarts: false,
  },
  {
    id: 'Unending Coil',
    zoneRegex: /^(The Unending Coil Of Bahamut \(Ultimate\)|巴哈姆特绝境战)$/,
    startRegex: /:(Twintania|双塔尼亚):26A7:/,
    countdownStarts: true,
  },
  {
    id: 'Shinryu Ex',
    zoneRegex: /^(The Minstrel's Ballad: Shinryu's Domain|神龙梦幻歼灭战)$/,
    startRegex: /:(Shinryu starts using Earthen Fury|神龙 starts using 大地之怒)/,
    countdownStarts: true,
  },
  {
    id: 'o5s',
    zoneRegex: /(Sigmascape V1\.0 \(Savage\)|欧米茄零式时空狭缝 \(西格玛幻境1\))/,
    startRegex: /:(Wroth Ghost|怒灵):28B6:/,
    countdownStarts: true,
  },
  {
    id: 'o6s',
    zoneRegex: /(Sigmascape V2\.0 \(Savage\)|欧米茄零式时空狭缝 \(西格玛幻境2\))/,
    startRegex: /14:2829:(Demon Chadarnook starts using Demonic Shear|恶魔查达奴克 starts using 恶魔斩)/,
    countdownStarts: true,
  },
  {
    id: 'o7s',
    zoneRegex: /(Sigmascape V3\.0 \(Savage\)|欧米茄零式时空狭缝 \(西格玛幻境3\))/,
    startRegex: /00:0044:(WEAPON SYSTEMS ONLINE|武器火控系统启动)/,
    countdownStarts: true,
  },
  {
    id: 'o8s-kefka',
    zoneRegex: /(Sigmascape V4\.0 \(Savage\)|欧米茄零式时空狭缝 \(西格玛幻境4\))/,
    startRegex: / 15:........:(Kefka|凯夫卡):28C2:/,
    endRegex: /:Kekfa was defeated by/,
    countdownStarts: false,
  },
  {
    id: 'o8s-god kefka',
    zoneRegex: /(Sigmascape V4\.0 \(Savage\)|欧米茄零式时空狭缝 \(西格玛幻境4\))/,
    startRegex: / 15:........:(Kefka|凯夫卡):28EC:/,
    countdownStarts: false,
  },
  {
    id: 'Byakko Ex',
    zoneRegex: /^(The Jade Stoa \(Extreme\)|白虎诗魂战)$/,
    startRegex: /:(Byakko starts using Storm Pulse|白虎 starts using 风雷波动)/,
    countdownStarts: true,
  },
  {
    id: 'Tsukuyomi Ex',
    zoneRegex: /(The Minstrel's Ballad: Tsukuyomi's Pain|月读幽夜歼灭战)/,
    startRegex: /:(Tsukuyomi|月读):2BBA:/,
    countdownStarts: true,
  },
  {
    id: 'UwU',
    zoneRegex: /^(The Weapon's Refrain \(Ultimate\)|Unknown Zone \(309\)|究极神兵绝境战)$/,
    startRegex: /:(Garuda|迦楼罗):2B53:/,
    countdownStarts: true,
  },
  {
    id: 'Suzaku Ex',
    zoneRegex: /^(Hells\' Kier \(Extreme\)|朱雀诗魂战)$/,
    startRegex: /:(Suzaku|朱雀):367:/,
    countdownStarts: true,
  },
  {
    id: 'Seiryu Ex',
    zoneRegex: /^(The Wreath Of Snakes \(Extreme\)|青龙诗魂战)$/,
    startRegex: /:(Seiryu|青龙):366:/,
    countdownStarts: true,
  },
  {
    id: 'o9s',
    zoneRegex: /(Alphascape V1\.0 \(Savage\)|欧米茄零式时空狭缝 \(阿尔法幻境1\))/,
    startRegex: /:(Chaos|卡奥斯):316F:/,
    countdownStarts: true,
  },
  {
    id: 'o10s',
    zoneRegex: /(Alphascape V2\.0 \(Savage\)|欧米茄零式时空狭缝 \(阿尔法幻境2\))/,
    startRegex: /:(Midgardsormr|尘世幻龙):31F9:/,
    countdownStarts: true,
  },
  {
    id: 'o11s',
    zoneRegex: /(Alphascape V3\.0 \(Savage\)|欧米茄零式时空狭缝 \(阿尔法幻境3\))/,
    startRegex: /:(Omega|欧米茄):368:/,
    countdownStarts: true,
  },
  {
    id: 'o12s-door',
    zoneRegex: /(Alphascape V4\.0 \(Savage\)|欧米茄零式时空狭缝 \(阿尔法幻境4\))/,
    startRegex: /:(Omega-M|欧米茄M):337D:/,
    countdownStarts: false,
  },
  {
    id: 'o12s-final',
    zoneRegex: /(Alphascape V4\.0 \(Savage\)|欧米茄零式时空狭缝 \(阿尔法幻境4\))/,
    startRegex: /:(Omega|欧米茄):336C:/,
    countdownStarts: false,
  },
];
