'use strict';

// Auto-generated from gen_hunt_data.py
// DO NOT EDIT THIS FILE DIRECTLY

let gMonster = {
  'Agathos': {
    'name': {
      'de': 'Agathos',
      'en': 'Agathos',
      'fr': 'Agathos',
      'ja': '\u30a2\u30ac\u30c8\u30b9',
    },
    'rank': 'A',
  },
  'Aglaope': {
    'name': {
      'de': 'Aglaope',
      'en': 'Aglaope',
      'fr': 'Aglaope',
      'ja': '\u30a2\u30b0\u30e9\u30aa\u30da',
    },
    'rank': 'S',
  },
  'Agrippa the Mighty': {
    'name': {
      'de': 'Agrippa',
      'en': 'Agrippa the Mighty',
      'fr': 'Agrippa',
      'ja': '\u30a2\u30b0\u30ea\u30c3\u30d1',
    },
    'rank': 'S',
  },
  'Albin the Ashen': {
    'name': {
      'de': 'Albin Aschfahl',
      'en': 'Albin the Ashen',
      'fr': 'Albin le blafard',
      'ja': '\u6b7b\u7070\u306e\u30a2\u30eb\u30d3\u30f3',
    },
    'rank': 'B',
  },
  'Alectryon': {
    'name': {
      'de': 'Alectryon',
      'en': 'Alectryon',
      'fr': 'Alectryon',
      'ja': '\u30a2\u30ec\u30af\u30c8\u30ea\u30aa\u30f3',
    },
    'rank': 'A',
  },
  'Alteci': {
    'name': {
      'de': 'Artic',
      'en': 'Alteci',
      'fr': 'Altek',
      'ja': '\u30a2\u30eb\u30c6\u30a3\u30c3\u30af',
    },
    'rank': 'B',
  },
  'Angada': {
    'name': {
      'de': 'Angada',
      'en': 'Angada',
      'fr': 'Angada',
      'ja': '\u30a2\u30f3\u30ac\u30c0',
    },
    'rank': 'A',
  },
  'Aqrabuamelu': {
    'name': {
      'de': 'Aqrabuamelu',
      'en': 'Aqrabuamelu',
      'fr': 'Aqrabuamelu',
      'ja': '\u30a2\u30af\u30e9\u30d6\u30a2\u30e1\u30eb',
    },
    'rank': 'A',
  },
  'Aswang': {
    'name': {
      'de': 'Aswang',
      'en': 'Aswang',
      'fr': 'Aswang',
      'ja': '\u30a2\u30b9\u30ef\u30f3\u30b0',
    },
    'rank': 'B',
  },
  'Baal': {
    'name': {
      'de': 'Baal',
      'en': 'Baal',
      'fr': 'Baal',
      'ja': '\u30d0\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Barbastelle': {
    'name': {
      'de': 'Barbastelle',
      'en': 'Barbastelle',
      'fr': 'Barbastelle',
      'ja': '\u30d0\u30fc\u30d0\u30b9\u30c6\u30eb',
    },
    'rank': 'B',
  },
  'Bird of Paradise': {
    'name': {
      'de': 'Paradiesvogel',
      'en': 'Bird of Paradise',
      'fr': 'oiseau de Paradis',
      'ja': '\u6975\u697d\u9ce5',
    },
    'rank': 'S',
  },
  'Bloody Mary': {
    'name': {
      'de': 'Bloody Mary',
      'en': 'Bloody Mary',
      'fr': 'Mary la sanglante',
      'ja': '\u30d6\u30e9\u30c3\u30c7\u30a3\u30fb\u30de\u30ea\u30fc',
    },
    'rank': 'B',
  },
  'Bone Crawler': {
    'name': {
      'de': 'Knochenkriecher',
      'en': 'Bone Crawler',
      'fr': 'Mangeur d\'os',
      'ja': '\u30dc\u30fc\u30f3\u30af\u30ed\u30fc\u30e9\u30fc',
    },
    'rank': 'S',
  },
  'Bonnacon': {
    'name': {
      'de': 'Bonnacon',
      'en': 'Bonnacon',
      'fr': 'Bonnacon',
      'ja': '\u30dc\u30ca\u30b3\u30f3',
    },
    'rank': 'S',
  },
  'Brontes': {
    'name': {
      'de': 'Brontes',
      'en': 'Brontes',
      'fr': 'Brontes',
      'ja': '\u30d6\u30ed\u30f3\u30c6\u30b9',
    },
    'rank': 'S',
  },
  'Buccaboo': {
    'name': {
      'de': 'Buccaboo',
      'en': 'Buccaboo',
      'fr': 'Bucca-boo',
      'ja': '\u30d6\u30c3\u30ab\u30d6\u30fc',
    },
    'rank': 'B',
  },
  'Bune': {
    'name': {
      'de': 'Bune',
      'en': 'Bune',
      'fr': 'Bune',
      'ja': '\u30d6\u30cd',
    },
    'rank': 'A',
  },
  'Campacti': {
    'name': {
      'de': 'Campacti',
      'en': 'Campacti',
      'fr': 'Campacti',
      'ja': '\u30ad\u30e3\u30e0\u30d1\u30af\u30c6\u30a3',
    },
    'rank': 'A',
  },
  'Chernobog': {
    'name': {
      'de': 'Czernobog',
      'en': 'Chernobog',
      'fr': 'Czernobog',
      'ja': '\u30c1\u30a7\u30eb\u30ce\u30dc\u30fc\u30b0',
    },
    'rank': 'S',
  },
  'Coquecigrue': {
    'name': {
      'de': 'Coquecigrue',
      'en': 'Coquecigrue',
      'fr': 'Coquecigrue',
      'ja': '\u30b3\u30af\u30b7\u30b0\u30eb\u30fc',
    },
    'rank': 'B',
  },
  'Cornu': {
    'name': {
      'de': 'Cornu',
      'en': 'Cornu',
      'fr': 'Cornu',
      'ja': '\u30b3\u30f3\u30cc',
    },
    'rank': 'A',
  },
  'Croakadile': {
    'name': {
      'de': 'Quakquak',
      'en': 'Croakadile',
      'fr': 'Croab\u00e9ros',
      'ja': '\u30b1\u30ed\u30b2\u30ed\u30b9',
    },
    'rank': 'S',
  },
  'Croque-mitaine': {
    'name': {
      'de': 'Croque Mitaine',
      'en': 'Croque-mitaine',
      'fr': 'Croque-mitaine',
      'ja': '\u30af\u30ed\u30c3\u30af\u30fb\u30df\u30c6\u30fc\u30cc',
    },
    'rank': 'S',
  },
  'Dalvag\'s Final Flame': {
    'name': {
      'de': 'Letzt(?:e|er|es|en) Flamme Dalvags',
      'en': 'Dalvag\'s Final Flame',
      'fr': 'derni\u00e8re flamme de Dalvag',
      'ja': '\u30d5\u30a1\u30a4\u30ca\u30eb\u30d5\u30ec\u30a4\u30e0',
    },
    'rank': 'A',
  },
  'Dark Helmet': {
    'name': {
      'de': 'Dunkelhelm',
      'en': 'Dark Helmet',
      'fr': 'Casque noir',
      'ja': '\u30c0\u30fc\u30af\u30d8\u30eb\u30e1\u30c3\u30c8',
    },
    'rank': 'B',
  },
  'Deacon': {
    'name': {
      'de': 'Diakon',
      'en': 'Deacon',
      'fr': 'Diacre',
      'ja': '\u30c7\u30a3\u30fc\u30b3\u30f3',
    },
    'rank': 'B',
  },
  'Deidar': {
    'name': {
      'de': 'Deidar',
      'en': 'Deidar',
      'fr': 'Deidar',
      'ja': '\u30c7\u30a4\u30c0\u30e9',
    },
    'rank': 'B',
  },
  'Domovoi': {
    'name': {
      'de': 'Domovoi',
      'en': 'Domovoi',
      'fr': 'Domovo\u00ef',
      'ja': '\u30c9\u30e2\u30f4\u30a9\u30fc\u30a4',
    },
    'rank': 'B',
  },
  'Enkelados': {
    'name': {
      'de': 'Engedoras',
      'en': 'Enkelados',
      'fr': 'Enk\u00e9lados',
      'ja': '\u30a8\u30f3\u30b1\u30c9\u30e9\u30b9',
    },
    'rank': 'A',
  },
  'Erle': {
    'name': {
      'de': 'Erle',
      'en': 'Erle',
      'fr': 'Erle',
      'ja': '\u30a2\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Flame Sergeant Dalvag': {
    'name': {
      'de': 'Dalvag',
      'en': 'Flame Sergeant Dalvag',
      'fr': 'sergent-major Dalvag',
      'ja': '\u4e0d\u6ec5\u306e\u30d5\u30a7\u30e9\u30f3\u30c9\u95d8\u8ecd\u66f9',
    },
    'rank': 'B',
  },
  'Forneus': {
    'name': {
      'de': 'Forneus',
      'en': 'Forneus',
      'fr': 'Forneus',
      'ja': '\u30d5\u30a1\u30eb\u30cd\u30a6\u30b9',
    },
    'rank': 'A',
  },
  'Funa Yurei': {
    'name': {
      'de': 'Funa Yurei',
      'en': 'Funa Yurei',
      'fr': 'Funa Yurei',
      'ja': '\u8239\u5e7d\u970a',
    },
    'rank': 'A',
  },
  'Gajasura': {
    'name': {
      'de': 'Gajasura',
      'en': 'Gajasura',
      'fr': 'Gajasura',
      'ja': '\u30ac\u30b8\u30e3\u30fc\u30b9\u30e9',
    },
    'rank': 'A',
  },
  'Gamma': {
    'name': {
      'de': 'Gamma',
      'en': 'Gamma',
      'fr': 'Gamma',
      'ja': '\u30ac\u30f3\u30de',
    },
    'rank': 'S',
  },
  'Gandarewa': {
    'name': {
      'de': 'Gandalva',
      'en': 'Gandarewa',
      'fr': 'Gandharva',
      'ja': '\u30ac\u30f3\u30c0\u30eb\u30f4\u30a1',
    },
    'rank': 'S',
  },
  'Gatling': {
    'name': {
      'de': 'Gatling',
      'en': 'Gatling',
      'fr': 'Acanthor',
      'ja': '\u30ac\u30c8\u30ea\u30f3\u30b0\u30b9',
    },
    'rank': 'B',
  },
  'Gauki Strongblade': {
    'name': {
      'de': 'Gauki Starkklinge',
      'en': 'Gauki Strongblade',
      'fr': 'Gauki la Lame forte',
      'ja': '\u5263\u8c6a\u30ac\u30a6\u30ad',
    },
    'rank': 'B',
  },
  'Ghede Ti Malice': {
    'name': {
      'de': 'Ghede Titus H\u00e4me',
      'en': 'Ghede Ti Malice',
      'fr': 'Gu\u00e9d\u00e9 Ti-Malice',
      'ja': '\u30b2\u30fc\u30c7',
    },
    'rank': 'A',
  },
  'Gilshs Aath Swiftclaw': {
    'name': {
      'de': 'Gilshs Aath',
      'en': 'Gilshs Aath Swiftclaw',
      'fr': 'Gilshs Aath l\'\u00e9trangleur',
      'ja': '\u624b\u63b4\u306e\u30ae\u30a6\u30b9\u30a3\u30fc\u30fb\u30a2\u30fc\u30b9',
    },
    'rank': 'B',
  },
  'Girimekhala': {
    'name': {
      'de': 'Girimekhala',
      'en': 'Girimekhala',
      'fr': 'Girimekhala',
      'ja': '\u30ae\u30ea\u30e1\u30ab\u30e9',
    },
    'rank': 'A',
  },
  'Girtab': {
    'name': {
      'de': 'Girtab',
      'en': 'Girtab',
      'fr': 'Girtab',
      'ja': '\u30ae\u30eb\u30bf\u30d6',
    },
    'rank': 'A',
  },
  'Gnath cometdrone': {
    'name': {
      'de': 'Gnath-Kometdrohne',
      'en': 'Gnath cometdrone',
      'fr': 'Gnathe myrmicom\u00e8te',
      'ja': '\u30b0\u30ca\u30fc\u30b9\u30fb\u30b3\u30e1\u30c3\u30c8\u30c9\u30ed\u30fc\u30f3',
    },
    'rank': 'B',
  },
  'Grassman': {
    'name': {
      'de': 'Grasmann',
      'en': 'Grassman',
      'fr': 'Sasquatch arboricole',
      'ja': '\u30b0\u30e9\u30b9\u30de\u30f3',
    },
    'rank': 'A',
  },
  'Guhuo Niao': {
    'name': {
      'de': 'Guhuo Niao',
      'en': 'Guhuo Niao',
      'fr': 'Guhuo Niao',
      'ja': '\u59d1\u7372\u9ce5',
    },
    'rank': 'B',
  },
  'Gunitt': {
    'name': {
      'de': 'Gunitt',
      'en': 'Gunitt',
      'fr': 'Gunitt',
      'ja': '\u30b0\u30cb\u30c3\u30c8',
    },
    'rank': 'S',
  },
  'Gwas-y-neidr': {
    'name': {
      'de': 'Gwas-y-neidr',
      'en': 'Gwas-y-neidr',
      'fr': 'Gwas-y-neidr',
      'ja': '\u30b0\u30a2\u30b9\u30fb\u30a2\u30fb\u30cb\u30fc\u30c9\u30eb',
    },
    'rank': 'B',
  },
  'Gyorai Quickstrike': {
    'name': {
      'de': 'Gyorai Schnellschlag',
      'en': 'Gyorai Quickstrike',
      'fr': 'Gyorai le Vif',
      'ja': '\u96f7\u6483\u306e\u30ae\u30e7\u30e9\u30a4',
    },
    'rank': 'B',
  },
  'Hellsclaw': {
    'name': {
      'de': 'H\u00f6llenklaue',
      'en': 'Hellsclaw',
      'fr': 'griffe des enfers magitek',
      'ja': '\u9b54\u5c0e\u30d8\u30eb\u30ba\u30af\u30ed\u30fc',
    },
    'rank': 'A',
  },
  'Huracan': {
    'name': {
      'de': 'Huracan',
      'en': 'Huracan',
      'fr': 'Huracan',
      'ja': '\u30d5\u30e9\u30ab\u30f3',
    },
    'rank': 'A',
  },
  'Indomitable': {
    'name': {
      'de': 'Unbez\u00e4hmbar',
      'en': 'Indomitable',
      'fr': 'Indomptable',
      'ja': '\u30a4\u30f3\u30c9\u30df\u30bf\u30d6\u30eb',
    },
    'rank': 'B',
  },
  'Itzpapalotl': {
    'name': {
      'de': 'Itzpapalotl',
      'en': 'Itzpapalotl',
      'fr': 'Itzpapalotl',
      'ja': '\u30a4\u30c4\u30d1\u30d1\u30ed\u30c4\u30eb',
    },
    'rank': 'B',
  },
  'Ixtab': {
    'name': {
      'de': 'Ixtab',
      'en': 'Ixtab',
      'fr': 'Ixtab',
      'ja': '\u30a4\u30b7\u30e5\u30bf\u30e0',
    },
    'rank': 'S',
  },
  'Juggler Hecatomb': {
    'name': {
      'de': 'Gaukler Hecatomb',
      'en': 'Juggler Hecatomb',
      'fr': 'Jongleur h\u00e9catombe',
      'ja': '\u30b8\u30e3\u30b0\u30e9\u30fc\u30fb\u30d8\u30ab\u30c8\u30a5\u30fc\u30e0',
    },
    'rank': 'B',
  },
  'Kiwa': {
    'name': {
      'de': 'Kiwa',
      'en': 'Kiwa',
      'fr': 'Kiwa',
      'ja': '\u30ad\u30ef',
    },
    'rank': 'B',
  },
  'Kreutzet': {
    'name': {
      'de': 'Kreutzet',
      'en': 'Kreutzet',
      'fr': 'Kreutzet',
      'ja': '\u30af\u30eb\u30fc\u30bc',
    },
    'rank': 'B',
  },
  'Kurma': {
    'name': {
      'de': 'Kurma',
      'en': 'Kurma',
      'fr': 'Kurma',
      'ja': '\u30af\u30fc\u30eb\u30de',
    },
    'rank': 'B',
  },
  'Kurrea': {
    'name': {
      'de': 'Kurrea',
      'en': 'Kurrea',
      'fr': 'Kurrea',
      'ja': '\u30af\u30fc\u30ec\u30a2',
    },
    'rank': 'A',
  },
  'La Velue': {
    'name': {
      'de': 'La Velue',
      'en': 'La Velue',
      'fr': 'Velue',
      'ja': '\u30e9\u30fb\u30f4\u30a7\u30ea\u30e5',
    },
    'rank': 'B',
  },
  'Laideronnette': {
    'name': {
      'de': 'Laideronette',
      'en': 'Laideronnette',
      'fr': 'Laideronnette',
      'ja': '\u30ec\u30c9\u30ed\u30cd\u30c3\u30c8',
    },
    'rank': 'S',
  },
  'Lampalagua': {
    'name': {
      'de': 'Balaur',
      'en': 'Lampalagua',
      'fr': 'Balaur',
      'ja': '\u30d0\u30eb\u30a6\u30fc\u30eb',
    },
    'rank': 'S',
  },
  'Leech King': {
    'name': {
      'de': 'Egelk\u00f6nig',
      'en': 'Leech King',
      'fr': 'roi des sangsues',
      'ja': '\u30ea\u30fc\u30c1\u30ad\u30f3\u30b0',
    },
    'rank': 'B',
  },
  'Leucrotta': {
    'name': {
      'de': 'Leucrotta',
      'en': 'Leucrotta',
      'fr': 'leucrotta',
      'ja': '\u30ec\u30a6\u30af\u30ed\u30c3\u30bf',
    },
    'rank': 'S',
  },
  'Li\'l Murderer': {
    'name': {
      'de': 'Klein(?:e|er|es|en) M\u00f6rder',
      'en': 'Li\'l Murderer',
      'fr': 'Tra\u00eetre',
      'ja': '\u30ea\u30eb\u30de\u30fc\u30c0\u30fc',
    },
    'rank': 'A',
  },
  'Lord of the Wyverns': {
    'name': {
      'de': 'Wyvern-Lord',
      'en': 'Lord of the Wyverns',
      'fr': 'seigneur des wyvernes',
      'ja': '\u30ef\u30a4\u30d0\u30fc\u30f3\u30ed\u30fc\u30c9',
    },
    'rank': 'A',
  },
  'Luminare': {
    'name': {
      'de': 'Luminare',
      'en': 'Luminare',
      'fr': 'Luminare',
      'ja': '\u30eb\u30df\u30ca\u30fc\u30ec',
    },
    'rank': 'A',
  },
  'Lycidas': {
    'name': {
      'de': 'Lykidas',
      'en': 'Lycidas',
      'fr': 'Lycidas',
      'ja': '\u30ea\u30e5\u30ad\u30c0\u30b9',
    },
    'rank': 'B',
  },
  'Lyuba': {
    'name': {
      'de': 'Lyuba',
      'en': 'Lyuba',
      'fr': 'Lyuba',
      'ja': '\u30ea\u30e5\u30fc\u30d0',
    },
    'rank': 'A',
  },
  'Maahes': {
    'name': {
      'de': 'Maahes',
      'en': 'Maahes',
      'fr': 'Maahes',
      'ja': '\u30de\u30d8\u30b9',
    },
    'rank': 'A',
  },
  'Mahisha': {
    'name': {
      'de': 'Mahisha',
      'en': 'Mahisha',
      'fr': 'Mahisha',
      'ja': '\u30de\u30d2\u30b7\u30e3',
    },
    'rank': 'A',
  },
  'Maliktender': {
    'name': {
      'de': 'Malikkaktor',
      'en': 'Maliktender',
      'fr': 'Malikpampa',
      'ja': '\u30de\u30ea\u30af\u30c6\u30f3\u30c0\u30fc',
    },
    'rank': 'A',
  },
  'Manes': {
    'name': {
      'de': 'Manes',
      'en': 'Manes',
      'fr': 'Manes',
      'ja': '\u30de\u30cd\u30b9',
    },
    'rank': 'B',
  },
  'Marberry': {
    'name': {
      'de': 'Marberry',
      'en': 'Marberry',
      'fr': 'marberry',
      'ja': '\u30de\u30fc\u30d9\u30ea\u30fc',
    },
    'rank': 'A',
  },
  'Marraco': {
    'name': {
      'de': 'Marraco',
      'en': 'Marraco',
      'fr': 'Marraco',
      'ja': '\u30de\u30e9\u30af',
    },
    'rank': 'A',
  },
  'Melt': {
    'name': {
      'de': 'Schmelze',
      'en': 'Melt',
      'fr': 'Fondu',
      'ja': '\u30e1\u30eb\u30c6\u30a3\u30bc\u30ea\u30fc',
    },
    'rank': 'A',
  },
  'Mindmaker': {
    'name': {
      'de': 'Freigeist',
      'en': 'Mindmaker',
      'fr': 'Ma\u00eetre-penseur',
      'ja': '\u30de\u30a4\u30f3\u30c9\u30e1\u30fc\u30ab\u30fc',
    },
    'rank': 'B',
  },
  'Minhocao': {
    'name': {
      'de': 'Minhocao',
      'en': 'Minhocao',
      'fr': 'Minhocao',
      'ja': '\u30df\u30cb\u30e7\u30fc\u30ab\u30aa\u30f3',
    },
    'rank': 'S',
  },
  'Mirka': {
    'name': {
      'de': 'Mirka',
      'en': 'Mirka',
      'fr': 'Mirka',
      'ja': '\u30df\u30eb\u30ab',
    },
    'rank': 'A',
  },
  'Monarch Ogrefly': {
    'name': {
      'de': 'Monarch Ogerlibelle',
      'en': 'Monarch Ogrefly',
      'fr': 'agrion ogre monarque',
      'ja': '\u30e2\u30ca\u30fc\u30af\u30fb\u30aa\u30fc\u30ac\u30d5\u30e9\u30a4',
    },
    'rank': 'B',
  },
  'Myradrosh': {
    'name': {
      'de': 'Myradrosh',
      'en': 'Myradrosh',
      'fr': 'Myradrosh',
      'ja': '\u30df\u30e9\u30c9\u30ed\u30c3\u30b7\u30e5',
    },
    'rank': 'B',
  },
  'Nahn': {
    'name': {
      'de': 'Nahn',
      'en': 'Nahn',
      'fr': 'Nahn',
      'ja': '\u30ca\u30f3',
    },
    'rank': 'A',
  },
  'Nandi': {
    'name': {
      'de': 'Nandi',
      'en': 'Nandi',
      'fr': 'Nandi',
      'ja': '\u30ca\u30f3\u30c7\u30a3',
    },
    'rank': 'S',
  },
  'Nariphon': {
    'name': {
      'de': 'Nariphon',
      'en': 'Nariphon',
      'fr': 'Nariphon',
      'ja': '\u30ca\u30ea\u30fc\u30dd\u30f3',
    },
    'rank': 'A',
  },
  'Naul': {
    'name': {
      'de': 'Naul',
      'en': 'Naul',
      'fr': 'Naul',
      'ja': '\u30ca\u30a6\u30eb',
    },
    'rank': 'B',
  },
  'Nuckelavee': {
    'name': {
      'de': 'Nuckelavee',
      'en': 'Nuckelavee',
      'fr': 'Nuckelavee',
      'ja': '\u30ca\u30c3\u30af\u30e9\u30f4\u30a3\u30fc',
    },
    'rank': 'A',
  },
  'Nunyunuwi': {
    'name': {
      'de': 'Nunyunuwi',
      'en': 'Nunyunuwi',
      'fr': 'Nunyunuwi',
      'ja': '\u30cc\u30cb\u30e5\u30cc\u30a6\u30a3',
    },
    'rank': 'S',
  },
  'O Poorest Pauldia': {
    'name': {
      'de': 'gepeinigt(?:e|er|es|en) Pauldia',
      'en': 'O Poorest Pauldia',
      'fr': 'Pauldia',
      'ja': '\u30dd\u30fc\u30eb\u30c7\u30a3\u30a2',
    },
    'rank': 'A',
  },
  'Okina': {
    'name': {
      'de': 'Okina',
      'en': 'Okina',
      'fr': 'Okina',
      'ja': '\u30aa\u30ad\u30ca',
    },
    'rank': 'S',
  },
  'Omni': {
    'name': {
      'de': 'Omni',
      'en': 'Omni',
      'fr': 'Omni',
      'ja': '\u30aa\u30e0\u30cb',
    },
    'rank': 'B',
  },
  'Oni Yumemi': {
    'name': {
      'de': 'Oni Yumemi',
      'en': 'Oni Yumemi',
      'fr': 'Oni Yumemi',
      'ja': '\u30aa\u30cb\u30e6\u30e1\u30df',
    },
    'rank': 'A',
  },
  'Orcus': {
    'name': {
      'de': 'Orcus',
      'en': 'Orcus',
      'fr': 'Orcus',
      'ja': '\u30aa\u30eb\u30af\u30b9',
    },
    'rank': 'A',
  },
  'Orghana': {
    'name': {
      'de': 'Orghana',
      'en': 'Orghana',
      'fr': 'Orghana',
      'ja': '\u30aa\u30eb\u30ac\u30ca',
    },
    'rank': 'S',
  },
  'Ouzelum': {
    'name': {
      'de': 'Ouzelum',
      'en': 'Ouzelum',
      'fr': 'Ouzelum',
      'ja': '\u30aa\u30bc\u30eb\u30e0',
    },
    'rank': 'B',
  },
  'Ovjang': {
    'name': {
      'de': 'Ovjang',
      'en': 'Ovjang',
      'fr': 'Ovjang',
      'ja': '\u30a2\u30f4\u30bc\u30f3',
    },
    'rank': 'B',
  },
  'Pachamama': {
    'name': {
      'de': 'Pachamama',
      'en': 'Pachamama',
      'fr': 'Pachamama',
      'ja': '\u30d1\u30c1\u30e3\u30de\u30de',
    },
    'rank': 'B',
  },
  'Phecda': {
    'name': {
      'de': 'Phecda',
      'en': 'Phecda',
      'fr': 'Phecda',
      'ja': '\u30d5\u30a7\u30af\u30c0',
    },
    'rank': 'B',
  },
  'Pterygotus': {
    'name': {
      'de': 'Pterygotus',
      'en': 'Pterygotus',
      'fr': 'Pterygotus',
      'ja': '\u30d7\u30c6\u30ea\u30b4\u30c8\u30a5\u30b9',
    },
    'rank': 'B',
  },
  'Pylraster': {
    'name': {
      'de': 'Xhauron',
      'en': 'Pylraster',
      'fr': 'Pirlasta',
      'ja': '\u30d1\u30a4\u30eb\u30e9\u30b9\u30bf',
    },
    'rank': 'A',
  },
  'Rusalka': {
    'name': {
      'de': 'Rusalka',
      'en': 'Rusalka',
      'fr': 'Roussalka',
      'ja': '\u30eb\u30b5\u30eb\u30ab',
    },
    'rank': 'A',
  },
  'Sabotender Bailarina': {
    'name': {
      'de': 'Sabotender Bailarina',
      'en': 'Sabotender Bailarina',
      'fr': 'pampa ballerine',
      'ja': '\u30b5\u30dc\u30c6\u30f3\u30c0\u30fc\u30fb\u30d0\u30a4\u30e9\u30ea\u30fc\u30ca',
    },
    'rank': 'A',
  },
  'Safat': {
    'name': {
      'de': 'Safat',
      'en': 'Safat',
      'fr': 'Safat',
      'ja': '\u30b5\u30d5\u30a1\u30c8',
    },
    'rank': 'S',
  },
  'Salt and Light': {
    'name': {
      'de': 'Salzlicht',
      'en': 'Salt and Light',
      'fr': 'Salaclux',
      'ja': '\u30bd\u30eb\u30c8\u30fb\u30a2\u30f3\u30c9\u30fb\u30e9\u30a4\u30c8',
    },
    'rank': 'S',
  },
  'Sanu Vali of Dancing Wings': {
    'name': {
      'de': 'Sanu Vali (?:der|die|das) Tanzend(?:e|er|es|en) Schwinge',
      'en': 'Sanu Vali of Dancing Wings',
      'fr': 'Sanu Vali',
      'ja': '\u821e\u624b\u306e\u30b5\u30cc\u30d0\u30ea',
    },
    'rank': 'B',
  },
  'Scitalis': {
    'name': {
      'de': 'Scitalis',
      'en': 'Scitalis',
      'fr': 'Scitalis',
      'ja': '\u30b9\u30ad\u30bf\u30ea\u30b9',
    },
    'rank': 'B',
  },
  'Senmurv': {
    'name': {
      'de': 'Simurgh',
      'en': 'Senmurv',
      'fr': 'S\u00eanmurw',
      'ja': '\u30bb\u30fc\u30f3\u30e0\u30eb\u30a6',
    },
    'rank': 'S',
  },
  'Sewer Syrup': {
    'name': {
      'de': 'Abwasser-Sirup',
      'en': 'Sewer Syrup',
      'fr': 'Syrop d\'\u00e9gout',
      'ja': '\u30b9\u30a7\u30a2\u30fc\u30b7\u30ed\u30c3\u30d7',
    },
    'rank': 'B',
  },
  'Shadow-dweller Yamini': {
    'name': {
      'de': 'Schattenkauer-Yamini',
      'en': 'Shadow-dweller Yamini',
      'fr': 'Yamini la Nocturne',
      'ja': '\u5bb5\u95c7\u306e\u30e4\u30df\u30cb',
    },
    'rank': 'B',
  },
  'Sisiutl': {
    'name': {
      'de': 'Sisiutl',
      'en': 'Sisiutl',
      'fr': 'Sisiutl',
      'ja': '\u30b7\u30b7\u30a6\u30c8\u30a5\u30eb',
    },
    'rank': 'A',
  },
  'Skogs Fru': {
    'name': {
      'de': 'Skogs Fru',
      'en': 'Skogs Fru',
      'fr': 'Skogs Fru',
      'ja': '\u30b9\u30b3\u30c3\u30b0\u30fb\u30d5\u30ea\u30e5\u30fc',
    },
    'rank': 'B',
  },
  'Slipkinx Steeljoints': {
    'name': {
      'de': 'Rutschfix Stahlscharnier',
      'en': 'Slipkinx Steeljoints',
      'fr': 'Slipkinx Joints-d\'acier',
      'ja': '\u6a5f\u5175\u306e\u30b9\u30ea\u30c3\u30d7\u30ad\u30f3\u30af\u30b9',
    },
    'rank': 'A',
  },
  'Squonk': {
    'name': {
      'de': 'Squonk',
      'en': 'Squonk',
      'fr': 'Squonk',
      'ja': '\u30b9\u30af\u30aa\u30f3\u30af',
    },
    'rank': 'B',
  },
  'Stinging Sophie': {
    'name': {
      'de': 'Stinkig(?:e|er|es|en) Sophie',
      'en': 'Stinging Sophie',
      'fr': 'Sophie la dardante',
      'ja': '\u30b9\u30c6\u30a3\u30f3\u30ae\u30f3\u30b0\u30fb\u30bd\u30d5\u30a3\u30fc',
    },
    'rank': 'B',
  },
  'Stolas': {
    'name': {
      'de': 'Stolas',
      'en': 'Stolas',
      'fr': 'Stolas',
      'ja': '\u30b9\u30c8\u30e9\u30b9',
    },
    'rank': 'A',
  },
  'Sugaar': {
    'name': {
      'de': 'Sugaar',
      'en': 'Sugaar',
      'fr': 'Sugaar',
      'ja': '\u30b7\u30e5\u30ac\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Sum': {
    'name': {
      'de': 'Sum',
      'en': 'Sum',
      'fr': 'Sum',
      'ja': '\u30bd\u30e0',
    },
    'rank': 'A',
  },
  'Supay': {
    'name': {
      'de': 'Supay',
      'en': 'Supay',
      'fr': 'Supay',
      'ja': '\u30b9\u30da\u30a4',
    },
    'rank': 'A',
  },
  'Tarchia': {
    'name': {
      'de': 'Tarchia',
      'en': 'Tarchia',
      'fr': 'Tarchia',
      'ja': '\u30bf\u30eb\u30ad\u30a2',
    },
    'rank': 'S',
  },
  'Thextera': {
    'name': {
      'de': 'Dexter',
      'en': 'Thextera',
      'fr': 'Texta',
      'ja': '\u30c6\u30af\u30b9\u30bf',
    },
    'rank': 'B',
  },
  'Thousand-cast Theda': {
    'name': {
      'de': 'Tausendzahn Theda',
      'en': 'Thousand-cast Theda',
      'fr': 'Theda la tripoteuse',
      'ja': '\u30b5\u30a6\u30b6\u30f3\u30c9\u30ad\u30e3\u30b9\u30c8\u30fb\u30bb\u30c0',
    },
    'rank': 'S',
  },
  'Tyger': {
    'name': {
      'de': 'Tyger',
      'en': 'Tyger',
      'fr': 'Tygre',
      'ja': '\u30c6\u30a3\u30ac\u30fc',
    },
    'rank': 'S',
  },
  'Udumbara': {
    'name': {
      'de': 'Udumbara',
      'en': 'Udumbara',
      'fr': 'Udumbara',
      'ja': '\u30a6\u30c9\u30f3\u30b2',
    },
    'rank': 'S',
  },
  'Unktehi': {
    'name': {
      'de': 'Unktehi',
      'en': 'Unktehi',
      'fr': 'Unktehi',
      'ja': '\u30a6\u30f3\u30af\u30c6\u30d2',
    },
    'rank': 'A',
  },
  'Vochstein': {
    'name': {
      'de': 'Vochstein',
      'en': 'Vochstein',
      'fr': 'Vochstein',
      'ja': '\u30d0\u30c3\u30af\u30b9\u30bf\u30a4\u30f3',
    },
    'rank': 'A',
  },
  'Vogaal Ja': {
    'name': {
      'de': 'Vogaal Ja',
      'en': 'Vogaal Ja',
      'fr': 'Vogaal Ja',
      'ja': '\u919c\u7537\u306e\u30f4\u30a9\u30ac\u30fc\u30b8\u30e3',
    },
    'rank': 'A',
  },
  'Vulpangue': {
    'name': {
      'de': 'Vulpangue',
      'en': 'Vulpangue',
      'fr': 'Vulpangue',
      'ja': '\u30f4\u30eb\u30d1\u30f3\u30b0\u30a8',
    },
    'rank': 'B',
  },
  'Vuokho': {
    'name': {
      'de': 'Vuokho',
      'en': 'Vuokho',
      'fr': 'Vuokho',
      'ja': '\u30f4\u30aa\u30b3\u30fc',
    },
    'rank': 'B',
  },
  'White Joker': {
    'name': {
      'de': 'Wei\u00df(?:e|er|es|en) Joker',
      'en': 'White Joker',
      'fr': 'joker blanc',
      'ja': '\u30db\u30ef\u30a4\u30c8\u30b8\u30e7\u30fc\u30ab\u30fc',
    },
    'rank': 'B',
  },
  'Worm of the Well': {
    'name': {
      'de': 'Wurm des Brunnens',
      'en': 'Worm of the Well',
      'fr': 'Verpuy',
      'ja': '\u30a6\u30a7\u30eb\u30a6\u30a9\u30fc\u30e0',
    },
    'rank': 'B',
  },
  'Wulgaru': {
    'name': {
      'de': 'Wulgaru',
      'en': 'Wulgaru',
      'fr': 'Wulgaru',
      'ja': '\u30a6\u30eb\u30ac\u30eb',
    },
    'rank': 'S',
  },
  'Zanig\'oh': {
    'name': {
      'de': 'Zanig\'oh',
      'en': 'Zanig\'oh',
      'fr': 'Zanig\'oh',
      'ja': '\u30b6\u30cb\u30b4',
    },
    'rank': 'A',
  },
  'Zona Seeker': {
    'name': {
      'de': 'Zona Sucher',
      'en': 'Zona Seeker',
      'fr': 'Zona Seeker',
      'ja': '\u30be\u30fc\u30ca\u30fb\u30b7\u30fc\u30ab\u30fc',
    },
    'rank': 'S',
  },
  'false gigantopithecus': {
    'name': {
      'de': 'Gigantopithecus',
      'en': 'false gigantopithecus',
      'fr': 'gigantopith\u00e8que',
      'ja': '\u30d6\u30e9\u30af\u30ad',
    },
    'rank': 'B',
  },
  'forgiven gossip': {
    'name': {
      'de': 'gel\u00e4utert(?:e|er|es|en) L\u00e4sterei',
      'en': 'forgiven gossip',
      'fr': 'm\u00e9disance pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30b4\u30b7\u30c3\u30d7',
    },
    'rank': 'SS-',
  },
  'forgiven pedantry': {
    'name': {
      'de': 'gel\u00e4utert(?:e|er|es|en) Pedanterie',
      'en': 'forgiven pedantry',
      'fr': 'p\u00e9danterie pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30da\u30c0\u30f3\u30c8\u30ea\u30fc',
    },
    'rank': 'S',
  },
  'forgiven rebellion': {
    'name': {
      'de': 'gel\u00e4utert(?:e|er|es|en) Rebellion',
      'en': 'forgiven rebellion',
      'fr': 'r\u00e9bellion pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30ea\u30d9\u30ea\u30aa\u30f3',
    },
    'rank': 'SS+',
  },
  'kaiser behemoth': {
    'name': {
      'de': 'Kaiser-Behemoth',
      'en': 'kaiser behemoth',
      'fr': 'b\u00e9h\u00e9moth empereur',
      'ja': '\u30ab\u30a4\u30b6\u30fc\u30d9\u30d2\u30fc\u30e2\u30b9',
    },
    'rank': 'S',
  },
  'mindflayer': {
    'name': {
      'de': 'Seelenbrenner',
      'en': 'mindflayer',
      'fr': 'flagelleur mental',
      'ja': '\u30de\u30a4\u30f3\u30c9\u30d5\u30ec\u30a2',
    },
    'rank': 'S',
  },
  'stench blossom': {
    'name': {
      'de': 'Pestwurz',
      'en': 'stench blossom',
      'fr': 'fleur naus\u00e9abonde',
      'ja': '\u30bb\u30f3\u30c1\u30d6\u30ed\u30c3\u30b5\u30e0',
    },
    'rank': 'A',
  },
  'the Garlok': {
    'name': {
      'de': 'Garlok',
      'en': 'the Garlok',
      'fr': 'Garlok',
      'ja': '\u30ac\u30fc\u30ed\u30c3\u30af',
    },
    'rank': 'S',
  },
  'the Pale Rider': {
    'name': {
      'de': 'Bleich(?:e|er|es|en) Reiter',
      'en': 'the Pale Rider',
      'fr': 'Cavalier p\u00e2le',
      'ja': '\u30da\u30a4\u30eb\u30e9\u30a4\u30c0\u30fc',
    },
    'rank': 'S',
  },
  'the Scarecrow': {
    'name': {
      'de': 'Tyranno',
      'en': 'the Scarecrow',
      'fr': 'dracosaure primus',
      'ja': '\u30b9\u30b1\u30a2\u30af\u30ed\u30a6',
    },
    'rank': 'B',
  },
  'the mudman': {
    'name': {
      'de': 'Matschklops',
      'en': 'the mudman',
      'fr': 'tas de boue',
      'ja': '\u6ce5\u4eba',
    },
    'rank': 'A',
  },
};
