'use strict';

// Auto-generated from get_radar_data.py
// DO NOT EDIT THIS FILE DIRECTLY

let gMonster = {
  'Agathos': {
    'name': {
      'cn': '\u963f\u4f3d\u6258\u65af',
      'de': 'Agathos',
      'en': 'Agathos',
      'fr': 'Agathos',
      'ja': '\u30a2\u30ac\u30c8\u30b9',
    },
    'rank': 'A',
  },
  'Aglaope': {
    'name': {
      'cn': '\u963f\u683c\u62c9\u4fc4\u73c0',
      'de': 'Aglaope',
      'en': 'Aglaope',
      'fr': 'Aglaope',
      'ja': '\u30a2\u30b0\u30e9\u30aa\u30da',
    },
    'rank': 'S',
  },
  'Agrippa the Mighty': {
    'name': {
      'cn': '\u963f\u683c\u91cc\u5e15',
      'de': 'Agrippa',
      'en': 'Agrippa the Mighty',
      'fr': 'Agrippa',
      'ja': '\u30a2\u30b0\u30ea\u30c3\u30d1',
    },
    'rank': 'S',
  },
  'Albin the Ashen': {
    'name': {
      'cn': '\u6b7b\u7070\u590d\u71c3\u7684\u963f\u5c14\u5bbe',
      'de': 'Albin Aschfahl',
      'en': 'Albin the Ashen',
      'fr': 'Albin le blafard',
      'ja': '\u6b7b\u7070\u306e\u30a2\u30eb\u30d3\u30f3',
    },
    'rank': 'B',
  },
  'Alectryon': {
    'name': {
      'cn': '\u963f\u5217\u523b\u7279\u5229\u6602',
      'de': 'Alectryon',
      'en': 'Alectryon',
      'fr': 'Alectryon',
      'ja': '\u30a2\u30ec\u30af\u30c8\u30ea\u30aa\u30f3',
    },
    'rank': 'A',
  },
  'Alteci': {
    'name': {
      'cn': '\u963f\u5c14\u63d0\u514b',
      'de': 'Artic',
      'en': 'Alteci',
      'fr': 'Altek',
      'ja': '\u30a2\u30eb\u30c6\u30a3\u30c3\u30af',
    },
    'rank': 'B',
  },
  'Angada': {
    'name': {
      'cn': '\u5b89\u8fe6\u8fbe',
      'de': 'Angada',
      'en': 'Angada',
      'fr': 'Angada',
      'ja': '\u30a2\u30f3\u30ac\u30c0',
    },
    'rank': 'A',
  },
  'Aqrabuamelu': {
    'name': {
      'cn': '\u7194\u9aa8\u708e\u874e',
      'de': 'Aqrabuamelu',
      'en': 'Aqrabuamelu',
      'fr': 'Aqrabuamelu',
      'ja': '\u30a2\u30af\u30e9\u30d6\u30a2\u30e1\u30eb',
    },
    'rank': 'A',
  },
  'Aswang': {
    'name': {
      'cn': '\u963f\u82cf\u9ec4',
      'de': 'Aswang',
      'en': 'Aswang',
      'fr': 'Aswang',
      'ja': '\u30a2\u30b9\u30ef\u30f3\u30b0',
    },
    'rank': 'B',
  },
  'Baal': {
    'name': {
      'cn': '\u5df4\u529b',
      'de': 'Baal',
      'en': 'Baal',
      'fr': 'Baal',
      'ja': '\u30d0\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Barbastelle': {
    'name': {
      'cn': '\u5bbd\u8033\u51f6\u8760',
      'de': 'Barbastelle',
      'en': 'Barbastelle',
      'fr': 'Barbastelle',
      'ja': '\u30d0\u30fc\u30d0\u30b9\u30c6\u30eb',
    },
    'rank': 'B',
  },
  'Bird of Paradise': {
    'name': {
      'cn': '\u6781\u4e50\u9e1f',
      'de': 'Paradiesvogel',
      'en': 'Bird of Paradise',
      'fr': 'oiseau de Paradis',
      'ja': '\u6975\u697d\u9ce5',
    },
    'rank': 'S',
  },
  'Bloody Mary': {
    'name': {
      'cn': '\u8840\u8165\u739b\u4e3d',
      'de': 'Bloody Mary',
      'en': 'Bloody Mary',
      'fr': 'Mary la sanglante',
      'ja': '\u30d6\u30e9\u30c3\u30c7\u30a3\u30fb\u30de\u30ea\u30fc',
    },
    'rank': 'B',
  },
  'Bone Crawler': {
    'name': {
      'cn': '\u722c\u9aa8\u602a\u9f99',
      'de': 'Knochenkriecher',
      'en': 'Bone Crawler',
      'fr': 'Mangeur d\'os',
      'ja': '\u30dc\u30fc\u30f3\u30af\u30ed\u30fc\u30e9\u30fc',
    },
    'rank': 'S',
  },
  'Bonnacon': {
    'name': {
      'cn': '\u706b\u6124\u725b',
      'de': 'Bonnacon',
      'en': 'Bonnacon',
      'fr': 'Bonnacon',
      'ja': '\u30dc\u30ca\u30b3\u30f3',
    },
    'rank': 'S',
  },
  'Brontes': {
    'name': {
      'cn': '\u5e03\u9686\u7279\u65af',
      'de': 'Brontes',
      'en': 'Brontes',
      'fr': 'Brontes',
      'ja': '\u30d6\u30ed\u30f3\u30c6\u30b9',
    },
    'rank': 'S',
  },
  'Buccaboo': {
    'name': {
      'cn': '\u5e03\u5361\u535c',
      'de': 'Buccaboo',
      'en': 'Buccaboo',
      'fr': 'Bucca-boo',
      'ja': '\u30d6\u30c3\u30ab\u30d6\u30fc',
    },
    'rank': 'B',
  },
  'Bune': {
    'name': {
      'cn': '\u5e03\u6d85',
      'de': 'Bune',
      'en': 'Bune',
      'fr': 'Bune',
      'ja': '\u30d6\u30cd',
    },
    'rank': 'A',
  },
  'Campacti': {
    'name': {
      'cn': '\u574e\u5e15\u63d0',
      'de': 'Campacti',
      'en': 'Campacti',
      'fr': 'Campacti',
      'ja': '\u30ad\u30e3\u30e0\u30d1\u30af\u30c6\u30a3',
    },
    'rank': 'A',
  },
  'Chernobog': {
    'name': {
      'cn': '\u725b\u5934\u9ed1\u795e',
      'de': 'Czernobog',
      'en': 'Chernobog',
      'fr': 'Czernobog',
      'ja': '\u30c1\u30a7\u30eb\u30ce\u30dc\u30fc\u30b0',
    },
    'rank': 'S',
  },
  'Coquecigrue': {
    'name': {
      'cn': '\u4e09\u5408\u9e1f\u513f',
      'de': 'Coquecigrue',
      'en': 'Coquecigrue',
      'fr': 'Coquecigrue',
      'ja': '\u30b3\u30af\u30b7\u30b0\u30eb\u30fc',
    },
    'rank': 'B',
  },
  'Cornu': {
    'name': {
      'cn': '\u89d2\u7956',
      'de': 'Cornu',
      'en': 'Cornu',
      'fr': 'Cornu',
      'ja': '\u30b3\u30f3\u30cc',
    },
    'rank': 'A',
  },
  'Croakadile': {
    'name': {
      'cn': '\u5495\u5c14\u5471\u6d1b\u65af',
      'de': 'Quakquak',
      'en': 'Croakadile',
      'fr': 'Croab\u00e9ros',
      'ja': '\u30b1\u30ed\u30b2\u30ed\u30b9',
    },
    'rank': 'S',
  },
  'Croque-mitaine': {
    'name': {
      'cn': '\u62a4\u571f\u7cbe\u7075',
      'de': 'Croque Mitaine',
      'en': 'Croque-mitaine',
      'fr': 'Croque-mitaine',
      'ja': '\u30af\u30ed\u30c3\u30af\u30fb\u30df\u30c6\u30fc\u30cc',
    },
    'rank': 'S',
  },
  'Dalvag\'s Final Flame': {
    'name': {
      'cn': '\u83f2\u5170\u5fb7\u7684\u9057\u706b',
      'de': 'Letzt[a] Flamme[p] Dalvags',
      'en': 'Dalvag\'s Final Flame',
      'fr': 'derni\u00e8re flamme de Dalvag',
      'ja': '\u30d5\u30a1\u30a4\u30ca\u30eb\u30d5\u30ec\u30a4\u30e0',
    },
    'rank': 'A',
  },
  'Dark Helmet': {
    'name': {
      'cn': '\u6697\u76d4\u9b54\u87f9',
      'de': 'Dunkelhelm',
      'en': 'Dark Helmet',
      'fr': 'Casque noir',
      'ja': '\u30c0\u30fc\u30af\u30d8\u30eb\u30e1\u30c3\u30c8',
    },
    'rank': 'B',
  },
  'Deacon': {
    'name': {
      'cn': '\u52a9\u796d\u5927\u87f9',
      'de': 'Diakon',
      'en': 'Deacon',
      'fr': 'Diacre',
      'ja': '\u30c7\u30a3\u30fc\u30b3\u30f3',
    },
    'rank': 'B',
  },
  'Deidar': {
    'name': {
      'cn': '\u5927\u592a',
      'de': 'Deidar',
      'en': 'Deidar',
      'fr': 'Deidar',
      'ja': '\u30c7\u30a4\u30c0\u30e9',
    },
    'rank': 'B',
  },
  'Domovoi': {
    'name': {
      'cn': '\u675c\u83ab\u4f0a',
      'de': 'Domovoi',
      'en': 'Domovoi',
      'fr': 'Domovo\u00ef',
      'ja': '\u30c9\u30e2\u30f4\u30a9\u30fc\u30a4',
    },
    'rank': 'B',
  },
  'Enkelados': {
    'name': {
      'cn': '\u6069\u514b\u62c9\u591a\u65af',
      'de': 'Engedoras',
      'en': 'Enkelados',
      'fr': 'Enk\u00e9lados',
      'ja': '\u30a8\u30f3\u30b1\u30c9\u30e9\u30b9',
    },
    'rank': 'A',
  },
  'Erle': {
    'name': {
      'cn': '\u5973\u738b\u8702',
      'de': 'Erle',
      'en': 'Erle',
      'fr': 'Erle',
      'ja': '\u30a2\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Flame Sergeant Dalvag': {
    'name': {
      'cn': '\u6c38\u6052\u4e0d\u706d\u7684\u83f2\u5170\u5fb7\u526f\u8000\u58eb',
      'de': 'Dalvag',
      'en': 'Flame Sergeant Dalvag',
      'fr': 'sergent-major Dalvag',
      'ja': '\u4e0d\u6ec5\u306e\u30d5\u30a7\u30e9\u30f3\u30c9\u95d8\u8ecd\u66f9',
    },
    'rank': 'B',
  },
  'Forneus': {
    'name': {
      'cn': '\u5f17\u5185\u4e4c\u65af',
      'de': 'Forneus',
      'en': 'Forneus',
      'fr': 'Forneus',
      'ja': '\u30d5\u30a1\u30eb\u30cd\u30a6\u30b9',
    },
    'rank': 'A',
  },
  'Funa Yurei': {
    'name': {
      'cn': '\u8239\u5e7d\u7075',
      'de': 'Funa Yurei',
      'en': 'Funa Yurei',
      'fr': 'Funa Yurei',
      'ja': '\u8239\u5e7d\u970a',
    },
    'rank': 'A',
  },
  'Gajasura': {
    'name': {
      'cn': '\u8c61\u9b54\u4fee\u7f57',
      'de': 'Gajasura',
      'en': 'Gajasura',
      'fr': 'Gajasura',
      'ja': '\u30ac\u30b8\u30e3\u30fc\u30b9\u30e9',
    },
    'rank': 'A',
  },
  'Gamma': {
    'name': {
      'cn': '\u4f3d\u9a6c',
      'de': 'Gamma',
      'en': 'Gamma',
      'fr': 'Gamma',
      'ja': '\u30ac\u30f3\u30de',
    },
    'rank': 'S',
  },
  'Gandarewa': {
    'name': {
      'cn': '\u521a\u5fb7\u745e\u74e6',
      'de': 'Gandalva',
      'en': 'Gandarewa',
      'fr': 'Gandharva',
      'ja': '\u30ac\u30f3\u30c0\u30eb\u30f4\u30a1',
    },
    'rank': 'S',
  },
  'Gatling': {
    'name': {
      'cn': '\u52a0\u7279\u6797\u9488\u9f39',
      'de': 'Gatling',
      'en': 'Gatling',
      'fr': 'Acanthor',
      'ja': '\u30ac\u30c8\u30ea\u30f3\u30b0\u30b9',
    },
    'rank': 'B',
  },
  'Gauki Strongblade': {
    'name': {
      'cn': '\u5251\u8c6a \u5211\u5177',
      'de': 'Gauki Starkklinge',
      'en': 'Gauki Strongblade',
      'fr': 'Gauki la Lame forte',
      'ja': '\u5263\u8c6a\u30ac\u30a6\u30ad',
    },
    'rank': 'B',
  },
  'Ghede Ti Malice': {
    'name': {
      'cn': '\u76d6\u5f97',
      'de': 'Ghede Titus H\u00e4me',
      'en': 'Ghede Ti Malice',
      'fr': 'Gu\u00e9d\u00e9 Ti-Malice',
      'ja': '\u30b2\u30fc\u30c7',
    },
    'rank': 'A',
  },
  'Gilshs Aath Swiftclaw': {
    'name': {
      'cn': '\u5f92\u624b\u6293\u9c7c \u57fa\u4e4c\u5636\u00b7\u6e0a\u65af',
      'de': 'Gilshs Aath',
      'en': 'Gilshs Aath Swiftclaw',
      'fr': 'Gilshs Aath l\'\u00e9trangleur',
      'ja': '\u624b\u63b4\u306e\u30ae\u30a6\u30b9\u30a3\u30fc\u30fb\u30a2\u30fc\u30b9',
    },
    'rank': 'B',
  },
  'Girimekhala': {
    'name': {
      'cn': '\u57fa\u91cc\u9ea6\u5361\u62c9',
      'de': 'Girimekhala',
      'en': 'Girimekhala',
      'fr': 'Girimekhala',
      'ja': '\u30ae\u30ea\u30e1\u30ab\u30e9',
    },
    'rank': 'A',
  },
  'Girtab': {
    'name': {
      'cn': '\u5c3e\u5bbf\u86db\u874e',
      'de': 'Girtab',
      'en': 'Girtab',
      'fr': 'Girtab',
      'ja': '\u30ae\u30eb\u30bf\u30d6',
    },
    'rank': 'A',
  },
  'Gnath cometdrone': {
    'name': {
      'cn': '\u9aa8\u988c\u5f57\u661f\u5175',
      'de': 'Gnath-Kometdrohne',
      'en': 'Gnath cometdrone',
      'fr': 'Gnathe myrmicom\u00e8te',
      'ja': '\u30b0\u30ca\u30fc\u30b9\u30fb\u30b3\u30e1\u30c3\u30c8\u30c9\u30ed\u30fc\u30f3',
    },
    'rank': 'B',
  },
  'Grassman': {
    'name': {
      'cn': '\u683c\u62c9\u65af\u66fc',
      'de': 'Grasmann',
      'en': 'Grassman',
      'fr': 'Sasquatch arboricole',
      'ja': '\u30b0\u30e9\u30b9\u30de\u30f3',
    },
    'rank': 'A',
  },
  'Guhuo Niao': {
    'name': {
      'cn': '\u59d1\u83b7\u9e1f',
      'de': 'Guhuo Niao',
      'en': 'Guhuo Niao',
      'fr': 'Guhuo Niao',
      'ja': '\u59d1\u7372\u9ce5',
    },
    'rank': 'B',
  },
  'Gunitt': {
    'name': {
      'cn': '\u987e\u5c3c\u56fe',
      'de': 'Gunitt',
      'en': 'Gunitt',
      'fr': 'Gunitt',
      'ja': '\u30b0\u30cb\u30c3\u30c8',
    },
    'rank': 'S',
  },
  'Gwas-y-neidr': {
    'name': {
      'cn': '\u86c7\u4ec6\u8682\u8713',
      'de': 'Gwas-y-neidr',
      'en': 'Gwas-y-neidr',
      'fr': 'Gwas-y-neidr',
      'ja': '\u30b0\u30a2\u30b9\u30fb\u30a2\u30fb\u30cb\u30fc\u30c9\u30eb',
    },
    'rank': 'B',
  },
  'Gyorai Quickstrike': {
    'name': {
      'cn': '\u95ea\u96f7\u51fb \u9c7c\u96f7',
      'de': 'Gyorai Schnellschlag',
      'en': 'Gyorai Quickstrike',
      'fr': 'Gyorai le Vif',
      'ja': '\u96f7\u6483\u306e\u30ae\u30e7\u30e9\u30a4',
    },
    'rank': 'B',
  },
  'Hellsclaw': {
    'name': {
      'cn': '\u9b54\u5bfc\u5730\u72f1\u722a',
      'de': 'H\u00f6llenklaue',
      'en': 'Hellsclaw',
      'fr': 'griffe des enfers magitek',
      'ja': '\u9b54\u5c0e\u30d8\u30eb\u30ba\u30af\u30ed\u30fc',
    },
    'rank': 'A',
  },
  'Huracan': {
    'name': {
      'cn': '\u4e4c\u62c9\u574e',
      'de': 'Huracan',
      'en': 'Huracan',
      'fr': 'Huracan',
      'ja': '\u30d5\u30e9\u30ab\u30f3',
    },
    'rank': 'A',
  },
  'Indomitable': {
    'name': {
      'cn': '\u4e0d\u5c48\u53f7',
      'de': 'Unbez\u00e4hmbar',
      'en': 'Indomitable',
      'fr': 'Indomptable',
      'ja': '\u30a4\u30f3\u30c9\u30df\u30bf\u30d6\u30eb',
    },
    'rank': 'B',
  },
  'Itzpapalotl': {
    'name': {
      'cn': '\u4f0a\u5179\u5e15\u5e15\u6d1b\u7279\u5c14',
      'de': 'Itzpapalotl',
      'en': 'Itzpapalotl',
      'fr': 'Itzpapalotl',
      'ja': '\u30a4\u30c4\u30d1\u30d1\u30ed\u30c4\u30eb',
    },
    'rank': 'B',
  },
  'Ixtab': {
    'name': {
      'cn': '\u4f0a\u4f11\u59b2',
      'de': 'Ixtab',
      'en': 'Ixtab',
      'fr': 'Ixtab',
      'ja': '\u30a4\u30b7\u30e5\u30bf\u30e0',
    },
    'rank': 'S',
  },
  'Juggler Hecatomb': {
    'name': {
      'cn': '\u6b8b\u8650\u6742\u6280\u5e08',
      'de': 'Gaukler[p] Hecatomb',
      'en': 'Juggler Hecatomb',
      'fr': 'Jongleur h\u00e9catombe',
      'ja': '\u30b8\u30e3\u30b0\u30e9\u30fc\u30fb\u30d8\u30ab\u30c8\u30a5\u30fc\u30e0',
    },
    'rank': 'B',
  },
  'Kiwa': {
    'name': {
      'cn': '\u5947\u6d3c',
      'de': 'Kiwa',
      'en': 'Kiwa',
      'fr': 'Kiwa',
      'ja': '\u30ad\u30ef',
    },
    'rank': 'B',
  },
  'Kreutzet': {
    'name': {
      'cn': '\u514b\u9c81\u6cfd',
      'de': 'Kreutzet',
      'en': 'Kreutzet',
      'fr': 'Kreutzet',
      'ja': '\u30af\u30eb\u30fc\u30bc',
    },
    'rank': 'B',
  },
  'Kurma': {
    'name': {
      'cn': '\u4ff1\u5229\u6469',
      'de': 'Kurma',
      'en': 'Kurma',
      'fr': 'Kurma',
      'ja': '\u30af\u30fc\u30eb\u30de',
    },
    'rank': 'B',
  },
  'Kurrea': {
    'name': {
      'cn': '\u5e93\u96f7\u4e9a',
      'de': 'Kurrea',
      'en': 'Kurrea',
      'fr': 'Kurrea',
      'ja': '\u30af\u30fc\u30ec\u30a2',
    },
    'rank': 'A',
  },
  'La Velue': {
    'name': {
      'cn': '\u6d53\u6bdb\u517d',
      'de': 'La Velue',
      'en': 'La Velue',
      'fr': 'Velue',
      'ja': '\u30e9\u30fb\u30f4\u30a7\u30ea\u30e5',
    },
    'rank': 'B',
  },
  'Laideronnette': {
    'name': {
      'cn': '\u96f7\u5fb7\u7f57\u5de8\u86c7',
      'de': 'Laideronette',
      'en': 'Laideronnette',
      'fr': 'Laideronnette',
      'ja': '\u30ec\u30c9\u30ed\u30cd\u30c3\u30c8',
    },
    'rank': 'S',
  },
  'Lampalagua': {
    'name': {
      'cn': '\u5df4\u62c9\u4e4c\u5c14',
      'de': 'Balaur',
      'en': 'Lampalagua',
      'fr': 'Balaur',
      'ja': '\u30d0\u30eb\u30a6\u30fc\u30eb',
    },
    'rank': 'S',
  },
  'Leech King': {
    'name': {
      'cn': '\u6c34\u86ed\u738b',
      'de': 'Egelk\u00f6nig',
      'en': 'Leech King',
      'fr': 'roi des sangsues',
      'ja': '\u30ea\u30fc\u30c1\u30ad\u30f3\u30b0',
    },
    'rank': 'B',
  },
  'Leucrotta': {
    'name': {
      'cn': '\u5362\u514b\u6d1b\u5854',
      'de': 'Leucrotta',
      'en': 'Leucrotta',
      'fr': 'leucrotta',
      'ja': '\u30ec\u30a6\u30af\u30ed\u30c3\u30bf',
    },
    'rank': 'S',
  },
  'Li\'l Murderer': {
    'name': {
      'cn': '\u5c0f\u5c0f\u6740\u624b',
      'de': 'Klein[a] M\u00f6rder',
      'en': 'Li\'l Murderer',
      'fr': 'Tra\u00eetre',
      'ja': '\u30ea\u30eb\u30de\u30fc\u30c0\u30fc',
    },
    'rank': 'A',
  },
  'Lord of the Wyverns': {
    'name': {
      'cn': '\u53cc\u8db3\u98de\u9f99\u4e4b\u738b',
      'de': 'Wyvern-Lord',
      'en': 'Lord of the Wyverns',
      'fr': 'seigneur des wyvernes',
      'ja': '\u30ef\u30a4\u30d0\u30fc\u30f3\u30ed\u30fc\u30c9',
    },
    'rank': 'A',
  },
  'Luminare': {
    'name': {
      'cn': '\u6cdb\u5149\u6676\u4f53',
      'de': 'Luminare',
      'en': 'Luminare',
      'fr': 'Luminare',
      'ja': '\u30eb\u30df\u30ca\u30fc\u30ec',
    },
    'rank': 'A',
  },
  'Lycidas': {
    'name': {
      'cn': '\u5229\u897f\u8fbe\u65af',
      'de': 'Lykidas',
      'en': 'Lycidas',
      'fr': 'Lycidas',
      'ja': '\u30ea\u30e5\u30ad\u30c0\u30b9',
    },
    'rank': 'B',
  },
  'Lyuba': {
    'name': {
      'cn': '\u5362\u82ad',
      'de': 'Lyuba',
      'en': 'Lyuba',
      'fr': 'Lyuba',
      'ja': '\u30ea\u30e5\u30fc\u30d0',
    },
    'rank': 'A',
  },
  'Maahes': {
    'name': {
      'cn': '\u739b\u8d6b\u65af',
      'de': 'Maahes',
      'en': 'Maahes',
      'fr': 'Maahes',
      'ja': '\u30de\u30d8\u30b9',
    },
    'rank': 'A',
  },
  'Mahisha': {
    'name': {
      'cn': '\u9a6c\u5e0c\u6c99',
      'de': 'Mahisha',
      'en': 'Mahisha',
      'fr': 'Mahisha',
      'ja': '\u30de\u30d2\u30b7\u30e3',
    },
    'rank': 'A',
  },
  'Maliktender': {
    'name': {
      'cn': '\u9a6c\u5229\u514b\u5de8\u4eba\u638c',
      'de': 'Malikkaktor',
      'en': 'Maliktender',
      'fr': 'Malikpampa',
      'ja': '\u30de\u30ea\u30af\u30c6\u30f3\u30c0\u30fc',
    },
    'rank': 'A',
  },
  'Manes': {
    'name': {
      'cn': '\u739b\u6d85\u65af',
      'de': 'Manes',
      'en': 'Manes',
      'fr': 'Manes',
      'ja': '\u30de\u30cd\u30b9',
    },
    'rank': 'B',
  },
  'Marberry': {
    'name': {
      'cn': '\u739b\u8d1d\u5229',
      'de': 'Marberry',
      'en': 'Marberry',
      'fr': 'marberry',
      'ja': '\u30de\u30fc\u30d9\u30ea\u30fc',
    },
    'rank': 'A',
  },
  'Marraco': {
    'name': {
      'cn': '\u9a6c\u62c9\u514b',
      'de': 'Marraco',
      'en': 'Marraco',
      'fr': 'Marraco',
      'ja': '\u30de\u30e9\u30af',
    },
    'rank': 'A',
  },
  'Melt': {
    'name': {
      'cn': '\u5343\u773c\u51dd\u80f6',
      'de': 'Schmelze',
      'en': 'Melt',
      'fr': 'Fondu',
      'ja': '\u30e1\u30eb\u30c6\u30a3\u30bc\u30ea\u30fc',
    },
    'rank': 'A',
  },
  'Mindmaker': {
    'name': {
      'cn': '\u542f\u7075\u679c',
      'de': 'Freigeist',
      'en': 'Mindmaker',
      'fr': 'Ma\u00eetre-penseur',
      'ja': '\u30de\u30a4\u30f3\u30c9\u30e1\u30fc\u30ab\u30fc',
    },
    'rank': 'B',
  },
  'Minhocao': {
    'name': {
      'cn': '\u8693\u8788\u5de8\u866b',
      'de': 'Minhocao',
      'en': 'Minhocao',
      'fr': 'Minhocao',
      'ja': '\u30df\u30cb\u30e7\u30fc\u30ab\u30aa\u30f3',
    },
    'rank': 'S',
  },
  'Mirka': {
    'name': {
      'cn': '\u7c73\u52d2\u5361',
      'de': 'Mirka',
      'en': 'Mirka',
      'fr': 'Mirka',
      'ja': '\u30df\u30eb\u30ab',
    },
    'rank': 'A',
  },
  'Monarch Ogrefly': {
    'name': {
      'cn': '\u541b\u738b\u9b3c\u873b\u8713',
      'de': 'Monarch Ogerlibelle',
      'en': 'Monarch Ogrefly',
      'fr': 'agrion ogre monarque',
      'ja': '\u30e2\u30ca\u30fc\u30af\u30fb\u30aa\u30fc\u30ac\u30d5\u30e9\u30a4',
    },
    'rank': 'B',
  },
  'Myradrosh': {
    'name': {
      'cn': '\u7c73\u814a\u5fb7\u7f57\u65af\u8702\u9e1f',
      'de': 'Myradrosh',
      'en': 'Myradrosh',
      'fr': 'Myradrosh',
      'ja': '\u30df\u30e9\u30c9\u30ed\u30c3\u30b7\u30e5',
    },
    'rank': 'B',
  },
  'Nahn': {
    'name': {
      'cn': '\u7eb3\u6069',
      'de': 'Nahn',
      'en': 'Nahn',
      'fr': 'Nahn',
      'ja': '\u30ca\u30f3',
    },
    'rank': 'A',
  },
  'Nandi': {
    'name': {
      'cn': '\u5357\u8fea',
      'de': 'Nandi',
      'en': 'Nandi',
      'fr': 'Nandi',
      'ja': '\u30ca\u30f3\u30c7\u30a3',
    },
    'rank': 'S',
  },
  'Nariphon': {
    'name': {
      'cn': '\u7eb3\u91cc\u84ec',
      'de': 'Nariphon',
      'en': 'Nariphon',
      'fr': 'Nariphon',
      'ja': '\u30ca\u30ea\u30fc\u30dd\u30f3',
    },
    'rank': 'A',
  },
  'Naul': {
    'name': {
      'cn': '\u7eb3\u4e4c\u5c14',
      'de': 'Naul',
      'en': 'Naul',
      'fr': 'Naul',
      'ja': '\u30ca\u30a6\u30eb',
    },
    'rank': 'B',
  },
  'Nuckelavee': {
    'name': {
      'cn': '\u7eb3\u514b\u62c9\u7ef4',
      'de': 'Nuckelavee',
      'en': 'Nuckelavee',
      'fr': 'Nuckelavee',
      'ja': '\u30ca\u30c3\u30af\u30e9\u30f4\u30a3\u30fc',
    },
    'rank': 'A',
  },
  'Nunyunuwi': {
    'name': {
      'cn': '\u52aa\u7ebd\u52aa\u7ef4',
      'de': 'Nunyunuwi',
      'en': 'Nunyunuwi',
      'fr': 'Nunyunuwi',
      'ja': '\u30cc\u30cb\u30e5\u30cc\u30a6\u30a3',
    },
    'rank': 'S',
  },
  'O Poorest Pauldia': {
    'name': {
      'cn': '\u4fdd\u5c14\u8fea\u96c5',
      'de': 'gepeinigt[a] Pauldia',
      'en': 'O Poorest Pauldia',
      'fr': 'Pauldia',
      'ja': '\u30dd\u30fc\u30eb\u30c7\u30a3\u30a2',
    },
    'rank': 'A',
  },
  'Okina': {
    'name': {
      'cn': '\u5de8\u5927\u9cd0',
      'de': 'Okina',
      'en': 'Okina',
      'fr': 'Okina',
      'ja': '\u30aa\u30ad\u30ca',
    },
    'rank': 'S',
  },
  'Omni': {
    'name': {
      'cn': '\u5168\u80fd\u673a\u7532',
      'de': 'Omni',
      'en': 'Omni',
      'fr': 'Omni',
      'ja': '\u30aa\u30e0\u30cb',
    },
    'rank': 'B',
  },
  'Oni Yumemi': {
    'name': {
      'cn': '\u9b3c\u89c2\u68a6',
      'de': 'Oni Yumemi',
      'en': 'Oni Yumemi',
      'fr': 'Oni Yumemi',
      'ja': '\u30aa\u30cb\u30e6\u30e1\u30df',
    },
    'rank': 'A',
  },
  'Orcus': {
    'name': {
      'cn': '\u5965\u8fe6\u65af',
      'de': 'Orcus',
      'en': 'Orcus',
      'fr': 'Orcus',
      'ja': '\u30aa\u30eb\u30af\u30b9',
    },
    'rank': 'A',
  },
  'Orghana': {
    'name': {
      'cn': '\u5140\u9c81\u5ffd\u4e43\u671d\u9c81',
      'de': 'Orghana',
      'en': 'Orghana',
      'fr': 'Orghana',
      'ja': '\u30aa\u30eb\u30ac\u30ca',
    },
    'rank': 'S',
  },
  'Ouzelum': {
    'name': {
      'cn': '\u5965\u7956\u9c81\u59c6',
      'de': 'Ouzelum',
      'en': 'Ouzelum',
      'fr': 'Ouzelum',
      'ja': '\u30aa\u30bc\u30eb\u30e0',
    },
    'rank': 'B',
  },
  'Ovjang': {
    'name': {
      'cn': '\u5965\u5f17\u6770\u6069',
      'de': 'Ovjang',
      'en': 'Ovjang',
      'fr': 'Ovjang',
      'ja': '\u30a2\u30f4\u30bc\u30f3',
    },
    'rank': 'B',
  },
  'Pachamama': {
    'name': {
      'cn': '\u5e15\u67e5\u739b\u739b',
      'de': 'Pachamama',
      'en': 'Pachamama',
      'fr': 'Pachamama',
      'ja': '\u30d1\u30c1\u30e3\u30de\u30de',
    },
    'rank': 'B',
  },
  'Phecda': {
    'name': {
      'cn': '\u5929\u7391\u5de8\u718a',
      'de': 'Phecda',
      'en': 'Phecda',
      'fr': 'Phecda',
      'ja': '\u30d5\u30a7\u30af\u30c0',
    },
    'rank': 'B',
  },
  'Pterygotus': {
    'name': {
      'cn': '\u7ffc\u80a2\u9c8e',
      'de': 'Pterygotus',
      'en': 'Pterygotus',
      'fr': 'Pterygotus',
      'ja': '\u30d7\u30c6\u30ea\u30b4\u30c8\u30a5\u30b9',
    },
    'rank': 'B',
  },
  'Pylraster': {
    'name': {
      'cn': '\u6d3e\u62c9\u65af\u7279\u66b4\u9f99',
      'de': 'Xhauron',
      'en': 'Pylraster',
      'fr': 'Pirlasta',
      'ja': '\u30d1\u30a4\u30eb\u30e9\u30b9\u30bf',
    },
    'rank': 'A',
  },
  'Rusalka': {
    'name': {
      'cn': '\u5362\u838e\u5361',
      'de': 'Rusalka',
      'en': 'Rusalka',
      'fr': 'Roussalka',
      'ja': '\u30eb\u30b5\u30eb\u30ab',
    },
    'rank': 'A',
  },
  'Sabotender Bailarina': {
    'name': {
      'cn': '\u82b1\u821e\u4ed9\u4eba\u523a',
      'de': 'Sabotender Bailarina',
      'en': 'Sabotender Bailarina',
      'fr': 'pampa ballerine',
      'ja': '\u30b5\u30dc\u30c6\u30f3\u30c0\u30fc\u30fb\u30d0\u30a4\u30e9\u30ea\u30fc\u30ca',
    },
    'rank': 'A',
  },
  'Safat': {
    'name': {
      'cn': '\u8428\u6cd5\u7279',
      'de': 'Safat',
      'en': 'Safat',
      'fr': 'Safat',
      'ja': '\u30b5\u30d5\u30a1\u30c8',
    },
    'rank': 'S',
  },
  'Salt and Light': {
    'name': {
      'cn': '\u76d0\u548c\u5149',
      'de': 'Salzlicht',
      'en': 'Salt and Light',
      'fr': 'Salaclux',
      'ja': '\u30bd\u30eb\u30c8\u30fb\u30a2\u30f3\u30c9\u30fb\u30e9\u30a4\u30c8',
    },
    'rank': 'S',
  },
  'Sanu Vali of Dancing Wings': {
    'name': {
      'cn': '\u98de\u821e\u7ffc \u8428\u52aa\u74e6\u529b',
      'de': 'Sanu Vali [t] Tanzend[a] Schwinge',
      'en': 'Sanu Vali of Dancing Wings',
      'fr': 'Sanu Vali',
      'ja': '\u821e\u624b\u306e\u30b5\u30cc\u30d0\u30ea',
    },
    'rank': 'B',
  },
  'Scitalis': {
    'name': {
      'cn': '\u65af\u5947\u5854\u5229\u65af',
      'de': 'Scitalis',
      'en': 'Scitalis',
      'fr': 'Scitalis',
      'ja': '\u30b9\u30ad\u30bf\u30ea\u30b9',
    },
    'rank': 'B',
  },
  'Senmurv': {
    'name': {
      'cn': '\u795e\u7a46\u5c14\u9e1f',
      'de': 'Simurgh',
      'en': 'Senmurv',
      'fr': 'S\u00eanmurw',
      'ja': '\u30bb\u30fc\u30f3\u30e0\u30eb\u30a6',
    },
    'rank': 'S',
  },
  'Sewer Syrup': {
    'name': {
      'cn': '\u9634\u6c9f\u6bd2\u6db2',
      'de': 'Abwasser-Sirup',
      'en': 'Sewer Syrup',
      'fr': 'Syrop d\'\u00e9gout',
      'ja': '\u30b9\u30a7\u30a2\u30fc\u30b7\u30ed\u30c3\u30d7',
    },
    'rank': 'B',
  },
  'Shadow-dweller Yamini': {
    'name': {
      'cn': '\u5f71\u4e2d\u6697 \u96c5\u5f25\u5c3c',
      'de': 'Schattenkauer-Yamini',
      'en': 'Shadow-dweller Yamini',
      'fr': 'Yamini la Nocturne',
      'ja': '\u5bb5\u95c7\u306e\u30e4\u30df\u30cb',
    },
    'rank': 'B',
  },
  'Sisiutl': {
    'name': {
      'cn': '\u897f\u65af\u5c24',
      'de': 'Sisiutl',
      'en': 'Sisiutl',
      'fr': 'Sisiutl',
      'ja': '\u30b7\u30b7\u30a6\u30c8\u30a5\u30eb',
    },
    'rank': 'A',
  },
  'Skogs Fru': {
    'name': {
      'cn': '\u82b1\u6797\u5973\u90ce',
      'de': 'Skogs Fru',
      'en': 'Skogs Fru',
      'fr': 'Skogs Fru',
      'ja': '\u30b9\u30b3\u30c3\u30b0\u30fb\u30d5\u30ea\u30e5\u30fc',
    },
    'rank': 'B',
  },
  'Slipkinx Steeljoints': {
    'name': {
      'cn': '\u673a\u5de5\u5175 \u65af\u5229\u666e\u91d1\u514b\u65af',
      'de': 'Rutschfix Stahlscharnier',
      'en': 'Slipkinx Steeljoints',
      'fr': 'Slipkinx Joints-d\'acier',
      'ja': '\u6a5f\u5175\u306e\u30b9\u30ea\u30c3\u30d7\u30ad\u30f3\u30af\u30b9',
    },
    'rank': 'A',
  },
  'Squonk': {
    'name': {
      'cn': '\u65af\u594e\u514b',
      'de': 'Squonk',
      'en': 'Squonk',
      'fr': 'Squonk',
      'ja': '\u30b9\u30af\u30aa\u30f3\u30af',
    },
    'rank': 'B',
  },
  'Stinging Sophie': {
    'name': {
      'cn': '\u51fb\u523a\u9b54\u8702\u7d22\u83f2',
      'de': 'Stinkig[a] Sophie',
      'en': 'Stinging Sophie',
      'fr': 'Sophie la dardante',
      'ja': '\u30b9\u30c6\u30a3\u30f3\u30ae\u30f3\u30b0\u30fb\u30bd\u30d5\u30a3\u30fc',
    },
    'rank': 'B',
  },
  'Stolas': {
    'name': {
      'cn': '\u65af\u7279\u62c9\u65af',
      'de': 'Stolas',
      'en': 'Stolas',
      'fr': 'Stolas',
      'ja': '\u30b9\u30c8\u30e9\u30b9',
    },
    'rank': 'A',
  },
  'Sugaar': {
    'name': {
      'cn': '\u4f11\u683c\u5c14',
      'de': 'Sugaar',
      'en': 'Sugaar',
      'fr': 'Sugaar',
      'ja': '\u30b7\u30e5\u30ac\u30fc\u30eb',
    },
    'rank': 'A',
  },
  'Sum': {
    'name': {
      'cn': '\u7855\u59c6',
      'de': 'Sum',
      'en': 'Sum',
      'fr': 'Sum',
      'ja': '\u30bd\u30e0',
    },
    'rank': 'A',
  },
  'Supay': {
    'name': {
      'cn': '\u82cf\u5e15\u4f0a',
      'de': 'Supay',
      'en': 'Supay',
      'fr': 'Supay',
      'ja': '\u30b9\u30da\u30a4',
    },
    'rank': 'A',
  },
  'Tarchia': {
    'name': {
      'de': 'Tarchia',
      'en': 'Tarchia',
      'fr': 'Tarchia',
      'ja': '\u30bf\u30eb\u30ad\u30a2',
    },
    'rank': 'S',
  },
  'Thextera': {
    'name': {
      'cn': '\u63d0\u514b\u65af\u5854',
      'de': 'Dexter',
      'en': 'Thextera',
      'fr': 'Texta',
      'ja': '\u30c6\u30af\u30b9\u30bf',
    },
    'rank': 'B',
  },
  'Thousand-cast Theda': {
    'name': {
      'cn': '\u5343\u7aff\u53e3\u82b1\u5e0c\u8fbe',
      'de': 'Tausendzahn Theda',
      'en': 'Thousand-cast Theda',
      'fr': 'Theda la tripoteuse',
      'ja': '\u30b5\u30a6\u30b6\u30f3\u30c9\u30ad\u30e3\u30b9\u30c8\u30fb\u30bb\u30c0',
    },
    'rank': 'S',
  },
  'Tyger': {
    'name': {
      'de': 'Tyger',
      'en': 'Tyger',
      'fr': 'Tygre',
      'ja': '\u30c6\u30a3\u30ac\u30fc',
    },
    'rank': 'S',
  },
  'Udumbara': {
    'name': {
      'cn': '\u4f18\u6619\u5a46\u7f57\u82b1',
      'de': 'Udumbara',
      'en': 'Udumbara',
      'fr': 'Udumbara',
      'ja': '\u30a6\u30c9\u30f3\u30b2',
    },
    'rank': 'S',
  },
  'Unktehi': {
    'name': {
      'cn': '\u4e4c\u514b\u63d0\u5e0c',
      'de': 'Unktehi',
      'en': 'Unktehi',
      'fr': 'Unktehi',
      'ja': '\u30a6\u30f3\u30af\u30c6\u30d2',
    },
    'rank': 'A',
  },
  'Vochstein': {
    'name': {
      'cn': '\u5f17\u514b\u65bd\u6cf0\u56e0',
      'de': 'Vochstein',
      'en': 'Vochstein',
      'fr': 'Vochstein',
      'ja': '\u30d0\u30c3\u30af\u30b9\u30bf\u30a4\u30f3',
    },
    'rank': 'A',
  },
  'Vogaal Ja': {
    'name': {
      'cn': '\u4e11\u7537\u5b50 \u6c83\u8fe6\u52a0',
      'de': 'Vogaal Ja',
      'en': 'Vogaal Ja',
      'fr': 'Vogaal Ja',
      'ja': '\u919c\u7537\u306e\u30f4\u30a9\u30ac\u30fc\u30b8\u30e3',
    },
    'rank': 'A',
  },
  'Vulpangue': {
    'name': {
      'cn': '\u72d0\u9996\u867a',
      'de': 'Vulpangue',
      'en': 'Vulpangue',
      'fr': 'Vulpangue',
      'ja': '\u30f4\u30eb\u30d1\u30f3\u30b0\u30a8',
    },
    'rank': 'B',
  },
  'Vuokho': {
    'name': {
      'cn': '\u5deb\u523b\u730e\u9e6b',
      'de': 'Vuokho',
      'en': 'Vuokho',
      'fr': 'Vuokho',
      'ja': '\u30f4\u30aa\u30b3\u30fc',
    },
    'rank': 'B',
  },
  'White Joker': {
    'name': {
      'cn': '\u767d\u9b3c\u9f20\u738b',
      'de': 'Wei\u00df[a] Joker',
      'en': 'White Joker',
      'fr': 'joker blanc',
      'ja': '\u30db\u30ef\u30a4\u30c8\u30b8\u30e7\u30fc\u30ab\u30fc',
    },
    'rank': 'B',
  },
  'Worm of the Well': {
    'name': {
      'cn': '\u5927\u4e95\u5de8\u866b',
      'de': 'Wurm[p] des Brunnens',
      'en': 'Worm of the Well',
      'fr': 'Verpuy',
      'ja': '\u30a6\u30a7\u30eb\u30a6\u30a9\u30fc\u30e0',
    },
    'rank': 'B',
  },
  'Wulgaru': {
    'name': {
      'cn': '\u4e4c\u5c14\u4f3d\u9c81',
      'de': 'Wulgaru',
      'en': 'Wulgaru',
      'fr': 'Wulgaru',
      'ja': '\u30a6\u30eb\u30ac\u30eb',
    },
    'rank': 'S',
  },
  'Zanig\'oh': {
    'name': {
      'cn': '\u672d\u5c3c\u6208',
      'de': 'Zanig\'oh',
      'en': 'Zanig\'oh',
      'fr': 'Zanig\'oh',
      'ja': '\u30b6\u30cb\u30b4',
    },
    'rank': 'A',
  },
  'Zona Seeker': {
    'name': {
      'cn': '\u865a\u65e0\u63a2\u7d22\u8005',
      'de': 'Zona Sucher',
      'en': 'Zona Seeker',
      'fr': 'Zona Seeker',
      'ja': '\u30be\u30fc\u30ca\u30fb\u30b7\u30fc\u30ab\u30fc',
    },
    'rank': 'S',
  },
  'false gigantopithecus': {
    'name': {
      'cn': '\u5e03\u62c9\u5de8\u733f',
      'de': 'Gigantopithecus',
      'en': 'false gigantopithecus',
      'fr': 'gigantopith\u00e8que',
      'ja': '\u30d6\u30e9\u30af\u30ad',
    },
    'rank': 'B',
  },
  'forgiven gossip': {
    'name': {
      'cn': '\u5f97\u5230\u5bbd\u6055\u7684\u6d41\u8a00',
      'de': 'gel\u00e4utert[a] L\u00e4sterei',
      'en': 'forgiven gossip',
      'fr': 'm\u00e9disance pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30b4\u30b7\u30c3\u30d7',
    },
    'rank': 'SS-',
  },
  'forgiven pedantry': {
    'name': {
      'de': 'gel\u00e4utert[a] Pedanterie',
      'en': 'forgiven pedantry',
      'fr': 'p\u00e9danterie pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30da\u30c0\u30f3\u30c8\u30ea\u30fc',
    },
    'rank': 'S',
  },
  'forgiven rebellion': {
    'name': {
      'cn': '\u5f97\u5230\u5bbd\u6055\u7684\u53db\u4e71',
      'de': 'gel\u00e4utert[a] Rebellion',
      'en': 'forgiven rebellion',
      'fr': 'r\u00e9bellion pardonn\u00e9e',
      'ja': '\u30d5\u30a9\u30fc\u30ae\u30f4\u30f3\u30fb\u30ea\u30d9\u30ea\u30aa\u30f3',
    },
    'rank': 'SS+',
  },
  'kaiser behemoth': {
    'name': {
      'cn': '\u51ef\u6492\u8d1d\u5e0c\u6469\u65af',
      'de': 'Kaiser-Behemoth',
      'en': 'kaiser behemoth',
      'fr': 'b\u00e9h\u00e9moth empereur',
      'ja': '\u30ab\u30a4\u30b6\u30fc\u30d9\u30d2\u30fc\u30e2\u30b9',
    },
    'rank': 'S',
  },
  'mindflayer': {
    'name': {
      'cn': '\u593a\u5fc3\u9b54',
      'de': 'Seelenbrenner',
      'en': 'mindflayer',
      'fr': 'flagelleur mental',
      'ja': '\u30de\u30a4\u30f3\u30c9\u30d5\u30ec\u30a2',
    },
    'rank': 'S',
  },
  'stench blossom': {
    'name': {
      'cn': '\u6076\u81ed\u72c2\u82b1',
      'de': 'Pestwurz',
      'en': 'stench blossom',
      'fr': 'fleur naus\u00e9abonde',
      'ja': '\u30bb\u30f3\u30c1\u30d6\u30ed\u30c3\u30b5\u30e0',
    },
    'rank': 'A',
  },
  'the Garlok': {
    'name': {
      'cn': '\u4f3d\u6d1b\u514b',
      'de': 'Garlok',
      'en': 'the Garlok',
      'fr': 'Garlok',
      'ja': '\u30ac\u30fc\u30ed\u30c3\u30af',
    },
    'rank': 'S',
  },
  'the Pale Rider': {
    'name': {
      'cn': '\u82cd\u767d\u9a91\u58eb',
      'de': 'Bleich[a] Reiter',
      'en': 'the Pale Rider',
      'fr': 'Cavalier p\u00e2le',
      'ja': '\u30da\u30a4\u30eb\u30e9\u30a4\u30c0\u30fc',
    },
    'rank': 'S',
  },
  'the Scarecrow': {
    'name': {
      'cn': '\u60ca\u614c\u7a3b\u8349\u9f99',
      'de': 'Tyranno',
      'en': 'the Scarecrow',
      'fr': 'dracosaure primus',
      'ja': '\u30b9\u30b1\u30a2\u30af\u30ed\u30a6',
    },
    'rank': 'B',
  },
  'the mudman': {
    'name': {
      'cn': '\u6ce5\u4eba',
      'de': 'Matschklops',
      'en': 'the mudman',
      'fr': 'tas de boue',
      'ja': '\u6ce5\u4eba',
    },
    'rank': 'A',
  },
};
