'use strict';

let gLang = null;

class CactbotLanguage {
  constructor(lang) {
    this.InitStrings();

    this.lang = lang;
    this.playerName = null;
    this.kAbility = Object.freeze({
      // Player abilities
      DragonKick: '4A',
      TwinSnakes: '3D',
      Demolish: '42',
      Verstone: '1D57',
      Verfire: '1D56',
      Veraero: '1D53',
      Verthunder: '1D51',
      Verholy: '1D66',
      Verflare: '1D65',
      Jolt2: '1D64',
      Jolt: '1D4F',
      Impact: '1D62',
      Scatter: '1D55',
      Vercure: '1D5A',
      Verraise: '1D63',
      Riposte: '1D50',
      Zwerchhau: '1D58',
      Redoublement: '1D5C',
      Moulinet: '1D59',
      EnchantedRiposte: '1D67',
      EnchantedZwerchhau: '1D68',
      EnchantedRedoublement: '1D69',
      EnchantedMoulinet: '1D6A',
      Tomahawk: '2E',
      Overpower: '29',
      HeavySwing: '1F',
      SkullSunder: '23',
      ButchersBlock: '2F',
      Maim: '25',
      StormsEye: '2D',
      StormsPath: '2A',
      TrickAttack: '8D2',
      Embolden: '1D60',
      Aetherflow: 'A6',
      ChainStratagem: '1D0C',
      Hypercharge: 'B45',
      Adloquium: 'B9',
      RabbitMedium: '8E0',
      OneIlmPunch: '48',
      Bootshine: '35',
      FastBlade: '09',
      RiotBlade: '0F',
      GoringBlade: 'DD2',
      RoyalAuthority: 'DD3',
      RageOfHalone: '15',
      SavageBlade: '0B',
      ShieldLob: '18',
      Requiescat: '1CD7',
      HolySpirit: '1CD8',
      TotalEclipse: '1CD5',
      Clemency: 'DD5',
      ShieldBash: '10',
      ShieldSwipe: '19',
      FightOrFlight: '14',
      BloodWeapon: 'E29',
      Souleater: 'E30',
      SyphonStrike: 'E27',
      HardSlash: 'E21',
      CarveAndSpit: 'E3B',
      Plunge: 'E38',
      Unmend: 'E28',
      AbyssalDrain: 'E39',
      PowerSlash: 'E2B',
      SpinningSlash: 'E23',
      BloodPrice: 'E2F',
      TheBlackestNight: '1CE1',
      Delirium: '1CDE',
      Combust2: 'E18',
      Combust3: '40AA',
      AspectedBenefic: 'E0B',
      AspectedHelios: 'E11',
      Bio: '45C8',
      Bio2: '45C9',
      Biolysis: '409C',
      Contagion: '31B',
      OffGuard: '2C93',
      SongOfTorment: '2C7A',
      PeculiarLight: '2C9D',
      MythrilTempest: '404E',
      Prominence: '4049',
      HolyCircle: '404A',
      Confiteor: '404B',
      FourPointFury: '4059',
      TechnicalFinish: '3F44',
      Thunder1: '90',
      Thunder2: '94',
      Thunder3: '99',
      Thunder4: '1CFC',
      Divination: '40A8',
      LucidDreaming: '1D8A',
    });

    this.kZone = Object.freeze({
      O1S: /Deltascape V1\.0 \(Savage\)/,
      O2S: /Deltascape V2\.0 \(Savage\)/,
      O3S: /Deltascape V3\.0 \(Savage\)/,
      O4S: /Deltascape V4\.0 \(Savage\)/,
      UCU: /The Unending Coil Of Bahamut \(Ultimate\)/,
      O5S: /Sigmascape V1\.0 \(Savage\)/,
      O6S: /Sigmascape V2\.0 \(Savage\)/,
      O7S: /Sigmascape V3\.0 \(Savage\)/,
      O8S: /Sigmascape V4\.0 \(Savage\)/,
      UWU: /The Weapon's Refrain \(Ultimate\)/,
      O9S: /Alphascape V1\.0 \(Savage\)/,
      O10S: /Alphascape V2\.0 \(Savage\)/,
      O11S: /Alphascape V3\.0 \(Savage\)/,
      O12S: /Alphascape V4\.0 \(Savage\)/,
      E1S: /Eden's Gate: Resurrection \(Savage\)/,
      E2S: /Eden's Gate: Descent \(Savage\)/,
      E3S: /Eden's Gate: Inundation \(Savage\)/,
      E4S: /Eden's Gate: Sepulture \(Savage\)/,
      E5S: /Eden's Verse: Fulmination \(Savage\)/,
      E6S: /Eden's Verse: Furor \(Savage\)/,
      E7S: /Eden's Verse: Iconoclasm \(Savage\)/,
      E8S: /Eden's Verse: Refulgence \(Savage\)/,
      PvpSeize: /Seal Rock \(Seize\)/,
      PvpSecure: /The Borderland Ruins \(Secure\)/,
      PvpShatter: /The Fields Of Glory \(Shatter\)/,
      EurekaAnemos: /Eureka Anemos/,
      EurekaPagos: /(Eureka Pagos|Unknown Zone \(2Fb\))/,
      EurekaPyros: /(Eureka Pyros|Unknown Zone \(31B\))/,
      EurekaHydatos: /(Eureka Hydatos|Unknown Zone \(33B\))/,
    });

    this.kLanguages = Object.freeze([
      'ja',
      'en',
      'de',
      'fr',
      'cn',
      'ko',
    ]);
  }

  InitStrings() {
    console.error('Derived language class must implement InitStrings');
  }
}
