(function () {
    var ratfinx = {
        fightId: "A5S",
        bossName: "Ratfinx Twinkledinks",
        minHP: 10000,
        areaSeal: "Advanced Clevering",
        phases: [
            {
                title: "Phase 1 (big)",
                shortName: "P1",
                phaseIdx: 1,
                loop: false,
                endSeconds: 44,
                endLog: "Ratfinx Twinkledinks loses the effect of Bigbulge Biggerbrain",
                rotation: [
                    { name: "(become big)", time: 4 },
                    { name: "Gobjab1", time: 9 },
                    { name: "Gobjab2", time: 13 },
                    { name: "Gobjab3", time: 17 },
                    { name: "Gobjab4", time: 21 },
                    { name: "buster/stack", time: 28 },
                    { name: "Prey (to B)", time: 33 },
                    { name: "Gobdash", time: 39 },
                    { name: "(become small)", time: 44 },
                ],
            },
            {
                title: "Phase 2 (small)",
                shortName: "P2",
                phaseIdx: 2,
                loop: false,
                endSeconds: 80, //?
                endLog: "Ratfinx Twinkledinks gains the effect of Bigbulge Biggerbrain",
                rotation: [
                    { name: "Gloop (to red)", time: 4 },
                    { name: "Gloop (to purple)", time: 14 },
                    { name: "Cobras B+C (bring C to B)", time: 18 },
                    { name: "Shock Therapy AOE", time: 24 },
                    { name: "Steel Scales (stun)", time: 26 },
                    { name: "(folks with poison => green)", time: 35 },
                    { name: "Bombs+GORILLA (party opposite spike)", time: 49 },
                    { name: "(become big => birds)", time: 80 },
                ],
            },
            {
                title: "Phase 3 (big)",
                shortName: "P3",
                phaseIdx: 3,
                loop: false,
                endSeconds: 70,
                endLog: "Ratfinx Twinkledinks loses the effect of Bigbulge Biggerbrain",
                rotation: [
                    { name: "Boost (tag purple)", time: 4 },
                    { name: "Bombs+BIRDS (bait by #1)", time: 11 },
                    { name: "Gobswing", time: 14 },
                    { name: "Gobswing", time: 16 },
                    { name: "Gobswing", time: 18 },
                    { name: "Gobswing", time: 20 },
                    { name: "Prey (party follow)", time: 26 },
                    { name: "Gobdash", time: 32 },
                    { name: "Gobhook (LOS)", time: 34 },
                    { name: "Gobjab1", time: 45 },
                    { name: "Gobjab2", time: 50 },
                    { name: "Gobjab3", time: 54 },
                    { name: "Gobjab4", time: 58 },
                    { name: "buster/stack", time: 66 },
                    { name: "(become small)", time: 70 },
                ],
            },
            {
                title: "Phase 4 (small)",
                shortName: "P4",
                phaseIdx: 4,
                loop: false,
                endSeconds: 77,
                endLog: "Ratfinx Twinkledinks gains the effect of Bigbulge Biggerbrain",
                rotation: [
                    { name: "Groper spawn at D, hit blue", time: 2 },
                    { name: "Gloop to blue", time: 21 },
                    { name: "Bombs+GORILLA (party to spike)", time: 33 },
                    { name: "Shock Therapy (AOE)", time: 37 },
                    { name: "Shock Therapy (AOE)", time: 45 },
                    { name: "Shock Therapy (AOE)", time: 53 },
                    { name: "Shock Therapy (AOE)", time: 61 },
                    { name: "Shock Therapy (AOE)", time: 69 },
                    { name: "(become big => birds)", time: 77 },
                ],
            },
            {
                title: "Phase 5 (big)",
                shortName: "P5",
                phaseIdx: 5,
                loop: false,
                endSeconds: 102,
                endLog: "Ratfinx Twinkledinks loses the effect of Bigbulge Biggerbrain",
                rotation: [
                    { name: "Boost (tag purple)", time: 4 },
                    { name: "Bombs+BIRDS (bait by #1)", time: 11 },
                    { name: "Gobswing", time: 13 },
                    { name: "Gobswing", time: 15 },
                    { name: "Gobswing", time: 17 },
                    { name: "Gobswing", time: 19 },
                    { name: "Prey #1 (away)", time: 37 },
                    { name: "Prey #2 (wall by party)", time: 39 },
                    { name: "Gobcut (stack)", time: 41 },
                    { name: "Gobdash", time: 46 },
                    { name: "Gobdash", time: 50 },
                    { name: "Gobhook (LOS)", time: 52 },
                    { name: "Gobjab1", time: 63 },
                    { name: "Gobjab2", time: 67 },
                    { name: "Gobjab3", time: 71 },
                    { name: "Gobjab4", time: 75 },
                    { name: "buster/stack", time: 82 },
                    { name: "(refresh on green, go to B)", time: 90 },
                    { name: "(offtank to A)", time: 95 },
                    { name: "(become small)", time: 102 },
                ],
            },
            {
                title: "Phase 6 (small)",
                shortName: "P6",
                phaseIdx: 6,
                loop: false,
                endSeconds: 129,
                rotation: [
                    { name: "Minotaur at A, pigs at B", time: 8 },
                    { name: "Gawkers at C+D, lb3", time: 10 },
                    { name: "Move minotaur to B", time: 14 },
                    { name: "Ooogle (look away)", time: 17 },
                    { name: "pigs at A, cobra at B", time: 30 },
                    { name: "(burn+refresh stacks if <1m)", time: 51 },
                    { name: "Shock Therapy (AOE)", time: 51 },
                    { name: "Shock Therapy (AOE)", time: 58 },
                    { name: "Shock Therapy (AOE)", time: 64 },
                    { name: "Shock Therapy (AOE)", time: 72 },
                    { name: "Shock Therapy (AOE)", time: 80 },
                    { name: "crit mob at C", time: 88 },
                    { name: "(become big)", time: 91 },
                    { name: "Gobjab1", time: 101 },
                    { name: "Gobjab2", time: 105 },
                    { name: "Gobjab3", time: 109 },
                    { name: "Gobjab4", time: 113 },
                    { name: "buster/stack", time: 121 },
                    { name: "(become small)", time: 129 },
                ],
            },
            {
                title: "Phase 7 (small)",
                shortName: "P7",
                phaseIdx: 7,
                loop: false,
                endSeconds: 10000,
                rotation: [
                    { name: "Groper spawn at D, hit blue", time: 2 },
                    { name: "Gloop to blue", time: 21 },
                    { name: "Bombs+GORILLA (party to spike)", time: 33 },
                    { name: "Shock Therapy (AOE)", time: 37 },
                    { name: "Shock Therapy (AOE)", time: 45 },
                    { name: "Shock Therapy (AOE)", time: 53 },
                    { name: "Shock Therapy (AOE)", time: 61 },
                    { name: "Shock Therapy (AOE)", time: 69 },
                ],
            },
        ],
    };

    var AlexanderSavageTurn5 = function () {
        BaseTickable.apply(this, arguments);
        this.zoneFilter = "Alexander - The Fist Of The Son (Savage)";
        this.bosses = [ratfinx];
    };
    AlexanderSavageTurn5.prototype = new BaseTickable;

    cb.updateRegistrar.register(new AlexanderSavageTurn5());

    var alex5_unknown = new AlexanderSavageTurn5();
    alex5_unknown.zoneFilter = "Unknown Zone (1C1)";
    cb.updateRegistrar.register(alex5_unknown);
})();