(function () {
    var bruteJustice = {
        fightId: "A8S",
        bossName: "Brute Justice",
        minHP: 10000,
        startLog: "Combat protocols restarting",
        phases: [
            {
                title: "Phase 1",
                shortName: "P1",
                phaseIdx: 1,
                loop: false,
                endLog: "Initiating combat protocol... Eliminate intruders",
                rotation: [
                    { name: "Hydrothermal", time: 6 },
                    { name: "Seed of the Sky", time: 13 },
                    { name: "Megabeemu~", time: 18 },
                    { name: "Hydrothermal", time: 22 },
                    { name: "(qarn boxes)", time: 27 },
                    { name: "Hydrothermal", time: 31 },
                    { name: "Megabeemu~", time: 41 },
                    { name: "PERPETUAL RAY", time: 44 },
                    { name: "Hydrothermal", time: 55 },
                    { name: "Megabeemu~", time: 62 },
                    { name: "Hydrothermal", time: 66 },
                    { name: "LEGISLATION", time: 75 },
                    { name: "Hydrothermal", time: 80 },
                    { name: "Seed", time: 87 },
                    { name: "Megabeemu~", time: 92 },
                    { name: "Hydrothermal", time: 95 },
                    { name: "PERPETUAL RAY", time: 96 },
                    { name: "Hydrothermal", time: 107 },
                    { name: "Hydrothermal", time: 120 },
                    { name: "Hella Late Seed", time: 125 },
                ],
            },
            {
                title: "Robot Attack",
                shortName: "R",
                phaseIdx: 2,
                loop: false,
                endLog: "Brute Justice uses Transform",
                rotation: [
                ],
            },
            {
                title: "Brute Justice",
                shortName: "P2",
                phaseIdx: 3,
                endLog: "Brute Justice uses J Kick",
                loop: false,
                rotation: [
                    { name: "Flarethrower", time: 9 },
                    { name: "Double Rocket Punch", time: 16 },
                    { name: "Prey / Seed / Flame", time: 20 },
                    { name: "Megabeamu~ (bait)", time: 30 },
                    { name: "Super Jump", time: 35 },
                    { name: "Apocalyptic Ray", time: 40 },
                    { name: "Flarethrower", time: 48 },
                    { name: "Double Rocket Punch", time: 55 },
                    { name: "Prey / Seed / Flame", time: 61 },
                    { name: "Megabeamu~ (bait)", time: 70 },
                    { name: "Super Jump", time: 76 },
                    { name: "(fly off)", time: 78 },
                    { name: "J Kick", time: 82 },
                ],
            },
            {
                title: "Intermission",
                shortName: "I1",
                phaseIdx: 4,
                loop: false,
		        endTime: 40,
                rotation: [
                    { name: "Mirage drop", time: 5 },
                    { name: "Stack Laser", time: 13 },
                    { name: "Chakram / Megabeamu~", time: 17 },
                    { name: "Height", time: 25 },
                    { name: "Buster / Megabeamu~", time: 30 },
                ],
            },
            {
                title: "Brute Justice 2",
                shortName: "P3",
                phaseIdx: 5,
                loop: true,
		        endTime: 78,
                rotation: [
                    { name: "Flarethrower", time: 9 },
                    { name: "Double Rocket Punch", time: 16 },
                    { name: "Prey / Seed / Flame", time: 20 },
                    { name: "Megabeamu~ (bait)", time: 30 },
                    { name: "Super Jump", time: 35 },
                    { name: "Apocalyptic Ray", time: 40 },
                    { name: "Flarethrower", time: 48 },
                    { name: "Double Rocket Punch", time: 55 },
                    { name: "Prey / Seed / Flame", time: 61 },
                    { name: "Megabeamu~ (bait)", time: 70 },
                    { name: "Super Jump", time: 76 },
                ],
            },
            {
                title: "Intermission 2",
                shortName: "I2",
                phaseIdx: 6,
                loop: false,
		        endTime: 39,
                rotation: [
                    { name: "Mines", time: 6 },
                    { name: "Double Drill", time: 10 },
                    { name: "Megabeamu~", time: 13 },
                    { name: "Mirage drop", time: 19 },
                    { name: "Single drill", time: 21 },
                    { name: "Megabeamu~", time: 21 },
                    { name: "Enumeration+flash", time: 31 },
                    { name: "(fly away)", time: 34 },
                ],
            },
            {
                title: "Ultimate Justice",
                shortName: "P4",
                phaseIdx: 7,
                loop: false,
                rotation: [
                    { name: "Justice", time: 5 },
                    { name: "Verdict", time: 12 },
                    { name: "Gavel", time: 40 },
                    { name: "(fly off)", time: 48 },
                    { name: "J Kick", time: 52 },
                    { name: "Water", time: 57 },
                    { name: "Final Punch", time: 68 },
                    { name: "Final Apocalypse", time: 70 },
                    { name: "Final Beam", time: 77 },
                    { name: "Prey / Seed dance", time: 79 },
                    { name: "Flarethrower", time: 84 },
                    { name: "DEATH!!!", time:  98 },
                    { name: "Megabeamu~", time:  100 },
                    { name: "Super Jump", time:  110 },
                    { name: "Flarethrower", time:  115 },
                    { name: "Short Needle spam", time:  120 },
                    { name: "Final Punch", time:  127 },
                    { name: "Final Apocalypse", time:  129 },
                    { name: "Final Beam", time:  136 },
                    { name: "(fly away)", time:  136 },
                    { name: "J Wave", time:  141 },
                    { name: "J Wave", time:  146 },
                    { name: "J Wave", time:  151 },
                    { name: "J Wave", time:  156 },
                    { name: "J Wave", time:  161 },
                    { name: "J Wave", time:  166 },
                    { name: "J Wave", time:  171 },
                    { name: "J Wave", time:  176 },
                    { name: "J Wave", time:  181 },
                ],
            },
        ],
    };

    var AlexanderSavageTurn8 = function () {
        BaseTickable.apply(this, arguments);
        this.zoneFilter = "Alexander - The Burden Of The Son (Savage)";
        this.bosses = [bruteJustice];
    };
    AlexanderSavageTurn8.prototype = new BaseTickable;

    cb.updateRegistrar.register(new AlexanderSavageTurn8());
})();
