Options.Triggers.push({
    zoneId: ZoneId.AsphodelosTheFourthCircleSavage,
    timelineFile: 'p4s.txt',
    triggers: [],
    timelineReplace: [
        {
            'locale': 'de',
            'missingTranslations': true,
            'replaceSync': {
                'Hesperos': 'Hesperos',
            },
            'replaceText': {
                '--debuffs--': '--Debuffs--',
                '--element debuffs--': '--Elementar-Debuffs--',
                '--role debuffs--': '--Rollen-Debuffs--',
                'Acid Pinax': 'Säure-Pinax',
                'Aetheric Chlamys': 'Ätherische Chlamys',
                'Akanthai: Act 1': 'Akanthai: Erster Akt',
                'Akanthai: Act 2': 'Akanthai: Zweiter Akt',
                'Akanthai: Act 3': 'Akanthai: Dritter Akt',
                'Akanthai: Act 4': 'Akanthai: Vierter Akt',
                'Akanthai: Curtain Call': 'Akanthai: Vorhang',
                'Akanthai: Finale': 'Akanthai: Finale',
                'Belone Bursts': 'Berstendes Belone',
                'Belone Coils': 'Gewundenes Belone',
                'Bloodrake': 'Blutharke',
                '(?<!Belone )Burst': 'Explosion',
                'Cursed Casting': 'Fluches Frucht',
                'Dark Design': 'Finsteres Formen',
                'Decollation': 'Enthauptung',
                'Director\'s Belone': 'Maskiertes Belone',
                'Elegant Evisceration': 'Adrette Ausweidung',
                'Elemental Belone': 'Elementares Belone',
                'Fleeting Impulse': 'Flüchtiger Impuls',
                'Heart Stake': 'Herzenspfahl',
                'Hell\'s Sting': 'Höllenstich',
                'Hemitheos\'s Aero III': 'Hemitheisches Windga',
                'Hemitheos\'s Dark IV': 'Hemitheisches Nachtka',
                'Hemitheos\'s Fire III': 'Hemitheisches Feuga',
                'Hemitheos\'s Fire IV': 'Hemitheisches Feuka',
                'Hemitheos\'s Thunder III': 'Hemitheisches Blitzga',
                'Hemitheos\'s Water IV': 'Hemitheisches Aquaka',
                'Inversive Chlamys': 'Invertierte Chlamys',
                'Kothornos Kick': 'Kothornoi-Tritt',
                'Kothornos Quake': 'Kothornoi-Beben',
                'Lava Pinax': 'Lava-Pinax',
                'Levinstrike Pinax': 'Donner-Pinax',
                'Periaktoi': 'Periaktoi',
                '(?<!\\w )Pinax': 'Pinax',
                'Searing Stream': 'Sengender Strom',
                'Setting the Scene': 'Vorhang auf',
                'Shifting Strike': 'Schwingenschlag',
                'Ultimate Impulse': 'Ultimativer Impuls',
                'Vengeful Belone': 'Rachsüchtiges Belone',
                'Well Pinax': 'Brunnen-Pinax',
                'Wreath of Thorns': 'Dornenhecke',
            },
        },
        {
            'locale': 'fr',
            'missingTranslations': true,
            'replaceSync': {
                'Hesperos': 'Hespéros',
            },
            'replaceText': {
                'Acid Pinax': 'Pinax de poison',
                'Aetheric Chlamys': 'Chlamyde d\'éther',
                'Akanthai: Act 1': 'La Tragédie des épines : acte I',
                'Akanthai: Act 2': 'La Tragédie des épines : acte II',
                'Akanthai: Act 3': 'La Tragédie des épines : acte III',
                'Akanthai: Act 4': 'La Tragédie des épines : acte IV',
                'Akanthai: Curtain Call': 'La Tragédie des épines : rappel',
                'Akanthai: Finale': 'La Tragédie des épines : acte final',
                'Belone Bursts': 'Bélos enchanté : explosion',
                'Belone Coils': 'Bélos enchanté : rotation',
                'Bloodrake': 'Racle de sang',
                '(?<!Belone )Burst': 'Explosion',
                'Cursed Casting': 'Malédiction immortelle',
                'Dark Design': 'Dessein noir',
                'Decollation': 'Décollation',
                'Director\'s Belone': 'Bélos enchanté : persona',
                'Elegant Evisceration': 'Éviscération élégante',
                'Elemental Belone': 'Bélos enchanté : élémentaire',
                'Fleeting Impulse': 'Impulsion fugace',
                'Heart Stake': 'Pieu dans le cœur',
                'Hell\'s Sting': 'Pointe infernale',
                'Hemitheos\'s Aero III': 'Méga Vent de l\'hémithéos',
                'Hemitheos\'s Dark IV': 'Giga Ténèbres de l\'hémithéos',
                'Hemitheos\'s Fire III': 'Méga Feu de l\'hémithéos',
                'Hemitheos\'s Fire IV': 'Giga Feu de l\'hémithéos',
                'Hemitheos\'s Thunder III': 'Méga Foudre de l\'hémithéos',
                'Hemitheos\'s Water IV': 'Giga Eau de l\'hémithéos',
                'Inversive Chlamys': 'Chlamyde retournée',
                'Kothornos Kick': 'Coup de cothurne',
                'Kothornos Quake': 'Piétinement de cothurne',
                'Lava Pinax': 'Pinax de feu',
                'Levinstrike Pinax': 'Pinax de foudre',
                'Periaktoi': 'Périacte',
                '(?<!\\w )Pinax': 'Pinax',
                'Searing Stream': 'Flux ardent',
                'Setting the Scene': 'Lever de rideau',
                'Shifting Strike': 'Frappe mouvante',
                'Ultimate Impulse': 'Impulsion ultime',
                'Vengeful Belone': 'Bélos enchanté : vengeance',
                'Well Pinax': 'Pinax d\'eau',
                'Wreath of Thorns': 'Haie d\'épines',
            },
        },
        {
            'locale': 'ja',
            'missingTranslations': true,
            'replaceSync': {
                'Hesperos': 'ヘスペロス',
            },
            'replaceText': {
                'Acid Pinax': 'ピナクスポイズン',
                'Aetheric Chlamys': 'エーテルクラミュス',
                'Akanthai: Act 1': '茨の悲劇：序幕',
                'Akanthai: Act 2': '茨の悲劇：第ニ幕',
                'Akanthai: Act 3': '茨の悲劇：第三幕',
                'Akanthai: Act 4': '茨の悲劇：第四幕',
                'Akanthai: Curtain Call': '茨の悲劇：カーテンコール',
                'Akanthai: Finale': '茨の悲劇：終幕',
                'Belone Bursts': 'エンチャンテッドペロネー：エクスプロージョン',
                'Belone Coils': 'エンチャンテッドペロネー：ラウンド',
                'Bloodrake': 'ブラッドレイク',
                '(?<!Belone )Burst': '爆発',
                'Cursed Casting': '呪詛発動',
                'Dark Design': 'ダークデザイン',
                'Decollation': 'デコレーション',
                'Director\'s Belone': 'エンチャンテッドペロネー：ペルソナ',
                'Elegant Evisceration': 'エレガントイヴィセレーション',
                'Elemental Belone': 'エンチャンテッドペロネー：エレメンタル',
                'Fleeting Impulse': 'フリーティングインパルス',
                'Heart Stake': 'ハートステイク',
                'Hell\'s Sting': 'ヘルスティング',
                'Hemitheos\'s Aero III': 'ヘーミテオス・エアロガ',
                'Hemitheos\'s Dark IV': 'ヘーミテオス・ダージャ',
                'Hemitheos\'s Fire III': 'ヘーミテオス・ファイガ',
                'Hemitheos\'s Fire IV': 'ヘーミテオス・ファイジャ',
                'Hemitheos\'s Thunder III': 'ヘーミテオス・サンダガ',
                'Hemitheos\'s Water IV': 'ヘーミテオス・ウォタジャ',
                'Inversive Chlamys': 'インヴァースクラミュス',
                'Kothornos Kick': 'コトルヌスキック',
                'Kothornos Quake': 'コトルヌスクエイク',
                'Lava Pinax': 'ピナクスラーヴァ',
                'Levinstrike Pinax': 'ピナクスサンダー',
                'Periaktoi': 'ペリアクトイ',
                '(?<!\\w )Pinax': 'ピナクス',
                'Searing Stream': 'シアリングストリーム',
                'Setting the Scene': '劇場創造',
                'Shifting Strike': 'シフティングストライク',
                'Ultimate Impulse': 'アルティメットインパルス',
                'Vengeful Belone': 'エンチャンテッドペロネー：リベンジ',
                'Well Pinax': 'ピナクススプラッシュ',
                'Wreath of Thorns': 'ソーンヘッジ',
            },
        },
    ],
});
