var currentDps;

function generateDpsEvent() {
  if (!currentDps) {
    currentDps = JSON.parse(JSON.stringify(testDps));
  }

  currentDps.Encounter.DURATION++;

  for (var key in currentDps.Combatant) {
    currentDps.Combatant[key].damage =
      parseFloat(currentDps.Combatant[key].damage) +
      Math.floor(Math.random() * 10000);
    currentDps.Combatant[key].DURATION++;
  }

  return {
    detail: currentDps,
    type: 'onOverlayDataUpdate',
  };
}

function generateStartPhaseEvent(name) {
  var dps = generateDpsEvent().detail;
  var e = {
    "type": "onFightPhaseStart",
    "detail": {
      "name": name,
      "dps": {
        "Encounter": dps.Encounter,
        "Combatant": dps.Combatant,
      },
    },
  };
  return e;
}

function generateEndPhaseEvent(name) {
  var e = generateStartPhaseEvent(name);
  e.type = 'onFightPhaseEnd';
  return e;
}

function resetDps() {
  currentDps = null;
}

var testDps = {
  "Encounter": {
    "n": "\n",
    "t": "\t",
    "title": "Encounter",
    "duration": "04:51",
    "DURATION": "291",
    "damage": "31867",
    "damage-m": "0.03",
    "DAMAGE-k": "32",
    "DAMAGE-m": "0",
    "dps": "109.51",
    "DPS": "110",
    "DPS-k": "0",
    "encdps": "10923.51",
    "ENCDPS": "10924",
    "ENCDPS-k": "0",
    "hits": "856",
    "crithits": "86",
    "crithit%": "0%",
    "misses": "3",
    "hitfailed": "0",
    "swings": "859",
    "tohit": "---",
    "TOHIT": "---",
    "maxhit": "Nobono Nobo-Fire-249",
    "MAXHIT": "Nobono Nobo-249",
    "healed": "181",
    "enchps": "0.62",
    "ENCHPS": "1",
    "ENCHPS-k": "0",
    "critheals": "86",
    "critheal%": "0%",
    "heals": "3",
    "cures": "0",
    "maxheal": "Dodd Himself-Life Surge-70",
    "MAXHEAL": "Dodd Himself-70",
    "maxhealward": "Dodd Himself-Life Surge-70",
    "MAXHEALWARD": "Dodd Himself-70",
    "damagetaken": "4467",
    "healstaken": "181",
    "powerdrain": "0",
    "powerheal": "0",
    "kills": "47",
    "deaths": "1",
    "Last10DPS": "100",
    "Last30DPS": "",
    "Last60DPS": ""
  },
  "Combatant": {
    "YOU": {
      "n": "\n",
      "t": "\t",
      "name": "YOU",
      "duration": "04:24",
      "DURATION": "264",
      "damage": "5094",
      "damage-m": "0.01",
      "DAMAGE-k": "5",
      "DAMAGE-m": "0",
      "damage%": "15%",
      "dps": "19.30",
      "DPS": "19",
      "DPS-k": "0",
      "encdps": "1327.51",
      "ENCDPS": "18",
      "ENCDPS-k": "0",
      "hits": "168",
      "crithits": "17",
      "crithit%": "10%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "168",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "True Strike-81",
      "MAXHIT": "81",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "840",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "9",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "YOU",
      "NAME4": "YOU",
      "NAME5": "YOU",
      "NAME6": "YOU",
      "NAME7": "YOU",
      "NAME8": "YOU",
      "NAME9": "YOU",
      "NAME10": "YOU",
      "NAME11": "YOU",
      "NAME12": "YOU",
      "NAME13": "YOU",
      "NAME14": "YOU",
      "NAME15": "YOU",
      "Last10DPS": "20",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Mnk",
      "ParryPct": "6%",
      "BlockPct": "0%",
      "IncToHit": "92.73",
      "OverHealPct": "0%"
    },
    "Dodd Himself": {
      "n": "\n",
      "t": "\t",
      "name": "Dodd Himself Dodd Himself Dodd Himself Dodd Himself",
      "duration": "02:21",
      "DURATION": "141",
      "damage": "4130",
      "damage-m": "0.00",
      "DAMAGE-k": "4",
      "DAMAGE-m": "0",
      "damage%": "12%",
      "dps": "29.29",
      "DPS": "29",
      "DPS-k": "0",
      "encdps": "14.19",
      "ENCDPS": "14",
      "ENCDPS-k": "0",
      "hits": "81",
      "crithits": "7",
      "crithit%": "9%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "81",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Full Thrust-186",
      "MAXHIT": "186",
      "healed": "125",
      "healed%": "69%",
      "enchps": "0.43",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "2",
      "cures": "0",
      "maxheal": "Life Surge-70",
      "MAXHEAL": "70",
      "maxhealward": "Life Surge-70",
      "MAXHEALWARD": "70",
      "damagetaken": "151",
      "healstaken": "125",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "6",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Dod",
      "NAME4": "Dodd",
      "NAME5": "Dodd",
      "NAME6": "Dodd H",
      "NAME7": "Dodd Hi",
      "NAME8": "Dodd Him",
      "NAME9": "Dodd Hims",
      "NAME10": "Dodd Himse",
      "NAME11": "Dodd Himsel",
      "NAME12": "Dodd Himself",
      "NAME13": "Dodd Himself",
      "NAME14": "Dodd Himself",
      "NAME15": "Dodd Himself",
      "Last10DPS": "5",
      "Last30DPS": "0",
      "Last60DPS": "9",
      "Job": "Drg",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "75.00",
      "OverHealPct": "0%"
    },
    "Kyrie Otaku": {
      "n": "\n",
      "t": "\t",
      "name": "Kyrie Otaku",
      "duration": "02:27",
      "DURATION": "147",
      "damage": "3956",
      "damage-m": "0.00",
      "DAMAGE-k": "4",
      "DAMAGE-m": "0",
      "damage%": "12%",
      "dps": "26.91",
      "DPS": "27",
      "DPS-k": "0",
      "encdps": "13.59",
      "ENCDPS": "14",
      "ENCDPS-k": "0",
      "hits": "62",
      "crithits": "11",
      "crithit%": "18%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "62",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Heavy Shot-234",
      "MAXHIT": "234",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "64",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "5",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Kyr",
      "NAME4": "Kyri",
      "NAME5": "Kyrie",
      "NAME6": "Kyrie",
      "NAME7": "Kyrie O",
      "NAME8": "Kyrie Ot",
      "NAME9": "Kyrie Ota",
      "NAME10": "Kyrie Otak",
      "NAME11": "Kyrie Otaku",
      "NAME12": "Kyrie Otaku",
      "NAME13": "Kyrie Otaku",
      "NAME14": "Kyrie Otaku",
      "NAME15": "Kyrie Otaku",
      "Last10DPS": "100",
      "Last30DPS": "0",
      "Last60DPS": "17",
      "Job": "Brd",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "62.50",
      "OverHealPct": "0%"
    },
    "Lexxi Foxx": {
      "n": "\n",
      "t": "\t",
      "name": "Lexxi Foxx",
      "duration": "02:57",
      "DURATION": "177",
      "damage": "3260",
      "damage-m": "0.00",
      "DAMAGE-k": "3",
      "DAMAGE-m": "0",
      "damage%": "10%",
      "dps": "18.42",
      "DPS": "18",
      "DPS-k": "0",
      "encdps": "11.20",
      "ENCDPS": "11",
      "ENCDPS-k": "0",
      "hits": "94",
      "crithits": "15",
      "crithit%": "16%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "94",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Heavy Shot-71",
      "MAXHIT": "71",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "59",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Lex",
      "NAME4": "Lexx",
      "NAME5": "Lexxi",
      "NAME6": "Lexxi",
      "NAME7": "Lexxi F",
      "NAME8": "Lexxi Fo",
      "NAME9": "Lexxi Fox",
      "NAME10": "Lexxi Foxx",
      "NAME11": "Lexxi Foxx",
      "NAME12": "Lexxi Foxx",
      "NAME13": "Lexxi Foxx",
      "NAME14": "Lexxi Foxx",
      "NAME15": "Lexxi Foxx",
      "Last10DPS": "1234",
      "Last30DPS": "0",
      "Last60DPS": "5",
      "Job": "Nin",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "62.50",
      "OverHealPct": "0%"
    },
    "Crippled Jordan": {
      "n": "\n",
      "t": "\t",
      "name": "Crippled Jordan",
      "duration": "02:15",
      "DURATION": "135",
      "damage": "2956",
      "damage-m": "0.00",
      "DAMAGE-k": "3",
      "DAMAGE-m": "0",
      "damage%": "9%",
      "dps": "21.90",
      "DPS": "22",
      "DPS-k": "0",
      "encdps": "10.16",
      "ENCDPS": "10",
      "ENCDPS-k": "0",
      "hits": "55",
      "crithits": "5",
      "crithit%": "9%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "55",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Stone-158",
      "MAXHIT": "158",
      "healed": "850",
      "healed%": "32%",
      "enchps": "19.32",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "159",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "6",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Cri",
      "NAME4": "Crip",
      "NAME5": "Cripp",
      "NAME6": "Crippl",
      "NAME7": "Cripple",
      "NAME8": "Crippled",
      "NAME9": "Crippled",
      "NAME10": "Crippled J",
      "NAME11": "Crippled Jo",
      "NAME12": "Crippled Jor",
      "NAME13": "Crippled Jord",
      "NAME14": "Crippled Jorda",
      "NAME15": "Crippled Jordan",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "8",
      "Job": "Whm",
      "ParryPct": "100%",
      "BlockPct": "0%",
      "IncToHit": "95.45",
      "OverHealPct": "0%"
    },
    "Wood Wailer Lance": {
      "n": "\n",
      "t": "\t",
      "name": "Wood Wailer Lance",
      "duration": "03:11",
      "DURATION": "191",
      "damage": "1765",
      "damage-m": "0.00",
      "DAMAGE-k": "2",
      "DAMAGE-m": "0",
      "damage%": "5%",
      "dps": "9.24",
      "DPS": "9",
      "DPS-k": "0",
      "encdps": "6.07",
      "ENCDPS": "6",
      "ENCDPS-k": "0",
      "hits": "145",
      "crithits": "7",
      "crithit%": "5%",
      "misses": "3",
      "hitfailed": "0",
      "swings": "148",
      "tohit": "97.97",
      "TOHIT": "98",
      "maxhit": "Heartstopper-80",
      "MAXHIT": "80",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "2189",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "3",
      "deaths": "1",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Woo",
      "NAME4": "Wood",
      "NAME5": "Wood",
      "NAME6": "Wood W",
      "NAME7": "Wood Wa",
      "NAME8": "Wood Wai",
      "NAME9": "Wood Wail",
      "NAME10": "Wood Waile",
      "NAME11": "Wood Wailer",
      "NAME12": "Wood Wailer",
      "NAME13": "Wood Wailer L",
      "NAME14": "Wood Wailer La",
      "NAME15": "Wood Wailer Lan",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "2",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "89.12",
      "OverHealPct": "0%"
    },
    "Nobono Nobo": {
      "n": "\n",
      "t": "\t",
      "name": "Nobono Nobo",
      "duration": "00:51",
      "DURATION": "51",
      "damage": "1765",
      "damage-m": "0.00",
      "DAMAGE-k": "2",
      "DAMAGE-m": "0",
      "damage%": "5%",
      "dps": "34.61",
      "DPS": "35",
      "DPS-k": "0",
      "encdps": "6.07",
      "ENCDPS": "6",
      "ENCDPS-k": "0",
      "hits": "14",
      "crithits": "1",
      "crithit%": "7%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "14",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Fire-249",
      "MAXHIT": "249",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "18",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "4",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Nob",
      "NAME4": "Nobo",
      "NAME5": "Nobon",
      "NAME6": "Nobono",
      "NAME7": "Nobono",
      "NAME8": "Nobono N",
      "NAME9": "Nobono No",
      "NAME10": "Nobono Nob",
      "NAME11": "Nobono Nobo",
      "NAME12": "Nobono Nobo",
      "NAME13": "Nobono Nobo",
      "NAME14": "Nobono Nobo",
      "NAME15": "Nobono Nobo",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Blm",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "66.67",
      "OverHealPct": "0%"
    },
    "Nailius Grieves": {
      "n": "\n",
      "t": "\t",
      "name": "Nailius Grieves",
      "duration": "01:37",
      "DURATION": "97",
      "damage": "1711",
      "damage-m": "0.00",
      "DAMAGE-k": "2",
      "DAMAGE-m": "0",
      "damage%": "5%",
      "dps": "17.64",
      "DPS": "18",
      "DPS-k": "0",
      "encdps": "5.88",
      "ENCDPS": "6",
      "ENCDPS-k": "0",
      "hits": "42",
      "crithits": "4",
      "crithit%": "10%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "42",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Full Thrust-120",
      "MAXHIT": "120",
      "healed": "56",
      "healed%": "30%",
      "enchps": "0.19",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "1",
      "cures": "0",
      "maxheal": "Life Surge-56",
      "MAXHEAL": "56",
      "maxhealward": "Life Surge-56",
      "MAXHEALWARD": "56",
      "damagetaken": "95",
      "healstaken": "56",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Nai",
      "NAME4": "Nail",
      "NAME5": "Naili",
      "NAME6": "Nailiu",
      "NAME7": "Nailius",
      "NAME8": "Nailius",
      "NAME9": "Nailius G",
      "NAME10": "Nailius Gr",
      "NAME11": "Nailius Gri",
      "NAME12": "Nailius Grie",
      "NAME13": "Nailius Griev",
      "NAME14": "Nailius Grieve",
      "NAME15": "Nailius Grieves",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "4",
      "Job": "Smn",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "72.73",
      "OverHealPct": "0%"
    },
    "Yehn Woln": {
      "n": "\n",
      "t": "\t",
      "name": "Yehn Woln",
      "duration": "00:38",
      "DURATION": "38",
      "damage": "1679",
      "damage-m": "0.00",
      "DAMAGE-k": "2",
      "DAMAGE-m": "0",
      "damage%": "5%",
      "dps": "44.18",
      "DPS": "44",
      "DPS-k": "0",
      "encdps": "5.77",
      "ENCDPS": "6",
      "ENCDPS-k": "0",
      "hits": "32",
      "crithits": "12",
      "crithit%": "38%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "32",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Snap Punch-107",
      "MAXHIT": "107",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "20",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "2",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Yeh",
      "NAME4": "Yehn",
      "NAME5": "Yehn",
      "NAME6": "Yehn W",
      "NAME7": "Yehn Wo",
      "NAME8": "Yehn Wol",
      "NAME9": "Yehn Woln",
      "NAME10": "Yehn Woln",
      "NAME11": "Yehn Woln",
      "NAME12": "Yehn Woln",
      "NAME13": "Yehn Woln",
      "NAME14": "Yehn Woln",
      "NAME15": "Yehn Woln",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "13",
      "Job": "Sch",
      "ParryPct": "50%",
      "BlockPct": "0%",
      "IncToHit": "100.00",
      "OverHealPct": "0%"
    },
    "J\'nai Kitsunah": {
      "n": "\n",
      "t": "\t",
      "name": "J\'nai Kitsunah",
      "duration": "01:01",
      "DURATION": "61",
      "damage": "1425",
      "damage-m": "0.00",
      "DAMAGE-k": "1",
      "DAMAGE-m": "0",
      "damage%": "4%",
      "dps": "23.36",
      "DPS": "23",
      "DPS-k": "0",
      "encdps": "4.90",
      "ENCDPS": "5",
      "ENCDPS-k": "0",
      "hits": "45",
      "crithits": "1",
      "crithit%": "2%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "45",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Rage Of Halone-88",
      "MAXHIT": "88",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "432",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)318",
      "threatdelta": "-318",
      "NAME3": "J\'n",
      "NAME4": "J\'na",
      "NAME5": "J\'nai",
      "NAME6": "J\'nai",
      "NAME7": "J\'nai K",
      "NAME8": "J\'nai Ki",
      "NAME9": "J\'nai Kit",
      "NAME10": "J\'nai Kits",
      "NAME11": "J\'nai Kitsu",
      "NAME12": "J\'nai Kitsun",
      "NAME13": "J\'nai Kitsuna",
      "NAME14": "J\'nai Kitsunah",
      "NAME15": "J\'nai Kitsunah",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Pld",
      "ParryPct": "23%",
      "BlockPct": "8%",
      "IncToHit": "82.50",
      "OverHealPct": "0%"
    },
    "Sathyasai Baba": {
      "n": "\n",
      "t": "\t",
      "name": "Sathyasai Baba",
      "duration": "01:59",
      "DURATION": "119",
      "damage": "1373",
      "damage-m": "0.00",
      "DAMAGE-k": "1",
      "DAMAGE-m": "0",
      "damage%": "4%",
      "dps": "11.54",
      "DPS": "12",
      "DPS-k": "0",
      "encdps": "4.72",
      "ENCDPS": "5",
      "ENCDPS-k": "0",
      "hits": "43",
      "crithits": "2",
      "crithit%": "5%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "43",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Scathe-114",
      "MAXHIT": "114",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "38",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Sat",
      "NAME4": "Sath",
      "NAME5": "Sathy",
      "NAME6": "Sathya",
      "NAME7": "Sathyas",
      "NAME8": "Sathyasa",
      "NAME9": "Sathyasai",
      "NAME10": "Sathyasai",
      "NAME11": "Sathyasai B",
      "NAME12": "Sathyasai Ba",
      "NAME13": "Sathyasai Bab",
      "NAME14": "Sathyasai Baba",
      "NAME15": "Sathyasai Baba",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "1",
      "Job": "War",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "66.67",
      "OverHealPct": "0%"
    },
    "Val (Kyrie Otaku)": {
      "n": "\n",
      "t": "\t",
      "name": "Val (Kyrie Otaku)",
      "duration": "02:13",
      "DURATION": "133",
      "damage": "818",
      "damage-m": "0.00",
      "DAMAGE-k": "1",
      "DAMAGE-m": "0",
      "damage%": "2%",
      "dps": "6.15",
      "DPS": "6",
      "DPS-k": "0",
      "encdps": "2.81",
      "ENCDPS": "3",
      "ENCDPS-k": "0",
      "hits": "21",
      "crithits": "3",
      "crithit%": "14%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "21",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Choco Kick-73",
      "MAXHIT": "73",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "2",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Val",
      "NAME4": "Val",
      "NAME5": "Val (",
      "NAME6": "Val (K",
      "NAME7": "Val (Ky",
      "NAME8": "Val (Kyr",
      "NAME9": "Val (Kyri",
      "NAME10": "Val (Kyrie",
      "NAME11": "Val (Kyrie",
      "NAME12": "Val (Kyrie O",
      "NAME13": "Val (Kyrie Ot",
      "NAME14": "Val (Kyrie Ota",
      "NAME15": "Val (Kyrie Otak",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "3",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "---",
      "OverHealPct": "0%"
    },
    "Slynxx (Lexxi Foxx)": {
      "n": "\n",
      "t": "\t",
      "name": "Slynxx (Lexxi Foxx)",
      "duration": "02:54",
      "DURATION": "174",
      "damage": "631",
      "damage-m": "0.00",
      "DAMAGE-k": "1",
      "DAMAGE-m": "0",
      "damage%": "1%",
      "dps": "3.63",
      "DPS": "4",
      "DPS-k": "0",
      "encdps": "2.17",
      "ENCDPS": "2",
      "ENCDPS-k": "0",
      "hits": "23",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "23",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Choco Drop-39",
      "MAXHIT": "39",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "2",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Sly",
      "NAME4": "Slyn",
      "NAME5": "Slynx",
      "NAME6": "Slynxx",
      "NAME7": "Slynxx",
      "NAME8": "Slynxx (",
      "NAME9": "Slynxx (L",
      "NAME10": "Slynxx (Le",
      "NAME11": "Slynxx (Lex",
      "NAME12": "Slynxx (Lexx",
      "NAME13": "Slynxx (Lexxi",
      "NAME14": "Slynxx (Lexxi",
      "NAME15": "Slynxx (Lexxi F",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "1",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "---",
      "OverHealPct": "0%"
    },
    "Chumpchange (Crippled Jordan)": {
      "n": "\n",
      "t": "\t",
      "name": "Chumpchange (Crippled Jordan)",
      "duration": "01:52",
      "DURATION": "112",
      "damage": "510",
      "damage-m": "0.00",
      "DAMAGE-k": "1",
      "DAMAGE-m": "0",
      "damage%": "1%",
      "dps": "4.55",
      "DPS": "5",
      "DPS-k": "0",
      "encdps": "1.75",
      "ENCDPS": "2",
      "ENCDPS-k": "0",
      "hits": "14",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "14",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Choco Drop-51",
      "MAXHIT": "51",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Chu",
      "NAME4": "Chum",
      "NAME5": "Chump",
      "NAME6": "Chumpc",
      "NAME7": "Chumpch",
      "NAME8": "Chumpcha",
      "NAME9": "Chumpchan",
      "NAME10": "Chumpchang",
      "NAME11": "Chumpchange",
      "NAME12": "Chumpchange",
      "NAME13": "Chumpchange (",
      "NAME14": "Chumpchange (C",
      "NAME15": "Chumpchange (Cr",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "2",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "---",
      "OverHealPct": "0%"
    },
    "Morendo Czell": {
      "n": "\n",
      "t": "\t",
      "name": "Morendo Czell",
      "duration": "01:17",
      "DURATION": "77",
      "damage": "341",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "1%",
      "dps": "4.43",
      "DPS": "4",
      "DPS-k": "0",
      "encdps": "1.17",
      "ENCDPS": "1",
      "ENCDPS-k": "0",
      "hits": "10",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "10",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Fast Blade-49",
      "MAXHIT": "49",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "113",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "2",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)4427",
      "threatdelta": "-4427",
      "NAME3": "Mor",
      "NAME4": "More",
      "NAME5": "Moren",
      "NAME6": "Morend",
      "NAME7": "Morendo",
      "NAME8": "Morendo",
      "NAME9": "Morendo C",
      "NAME10": "Morendo Cz",
      "NAME11": "Morendo Cze",
      "NAME12": "Morendo Czel",
      "NAME13": "Morendo Czell",
      "NAME14": "Morendo Czell",
      "NAME15": "Morendo Czell",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Pld",
      "ParryPct": "5%",
      "BlockPct": "5%",
      "IncToHit": "47.83",
      "OverHealPct": "0%"
    },
    "Spookweh (Gaalmak Errethios)": {
      "n": "\n",
      "t": "\t",
      "name": "Spookweh (Gaalmak Errethios)",
      "duration": "00:07",
      "DURATION": "7",
      "damage": "200",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "28.57",
      "DPS": "29",
      "DPS-k": "0",
      "encdps": "0.69",
      "ENCDPS": "1",
      "ENCDPS-k": "0",
      "hits": "3",
      "crithits": "1",
      "crithit%": "33%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "3",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Choco Blast-80",
      "MAXHIT": "80",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Spo",
      "NAME4": "Spoo",
      "NAME5": "Spook",
      "NAME6": "Spookw",
      "NAME7": "Spookwe",
      "NAME8": "Spookweh",
      "NAME9": "Spookweh",
      "NAME10": "Spookweh (",
      "NAME11": "Spookweh (G",
      "NAME12": "Spookweh (Ga",
      "NAME13": "Spookweh (Gaa",
      "NAME14": "Spookweh (Gaal",
      "NAME15": "Spookweh (Gaalm",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "---",
      "OverHealPct": "0%"
    },
    "Khari Nahdahra": {
      "n": "\n",
      "t": "\t",
      "name": "Khari Nahdahra",
      "duration": "00:18",
      "DURATION": "18",
      "damage": "148",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "8.22",
      "DPS": "8",
      "DPS-k": "0",
      "encdps": "0.51",
      "ENCDPS": "1",
      "ENCDPS-k": "0",
      "hits": "2",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "2",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Stone II-77",
      "MAXHIT": "77",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "0",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "1",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Kha",
      "NAME4": "Khar",
      "NAME5": "Khari",
      "NAME6": "Khari",
      "NAME7": "Khari N",
      "NAME8": "Khari Na",
      "NAME9": "Khari Nah",
      "NAME10": "Khari Nahd",
      "NAME11": "Khari Nahda",
      "NAME12": "Khari Nahdah",
      "NAME13": "Khari Nahdahr",
      "NAME14": "Khari Nahdahra",
      "NAME15": "Khari Nahdahra",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Cnj",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "0.00",
      "OverHealPct": "0%"
    },
    "Gaalmak Errethios": {
      "n": "\n",
      "t": "\t",
      "name": "Gaalmak Errethios",
      "duration": "00:02",
      "DURATION": "2",
      "damage": "105",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "52.50",
      "DPS": "53",
      "DPS-k": "0",
      "encdps": "0.36",
      "ENCDPS": "0",
      "ENCDPS-k": "0",
      "hits": "2",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "2",
      "tohit": "100.00",
      "TOHIT": "100",
      "maxhit": "Heavy Shot-69",
      "MAXHIT": "69",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "53",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Gaa",
      "NAME4": "Gaal",
      "NAME5": "Gaalm",
      "NAME6": "Gaalma",
      "NAME7": "Gaalmak",
      "NAME8": "Gaalmak",
      "NAME9": "Gaalmak E",
      "NAME10": "Gaalmak Er",
      "NAME11": "Gaalmak Err",
      "NAME12": "Gaalmak Erre",
      "NAME13": "Gaalmak Erret",
      "NAME14": "Gaalmak Erreth",
      "NAME15": "Gaalmak Errethi",
      "Last10DPS": "0",
      "Last30DPS": "0",
      "Last60DPS": "0",
      "Job": "Arc",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "100.00",
      "OverHealPct": "0%"
    },
    "Lenex Zemphonia": {
      "n": "\n",
      "t": "\t",
      "name": "Lenex Zemphonia",
      "duration": "00:00",
      "DURATION": "0",
      "damage": "0",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "---",
      "DPS": "---",
      "DPS-k": "---",
      "encdps": "0.00",
      "ENCDPS": "0",
      "ENCDPS-k": "0",
      "hits": "0",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "0",
      "tohit": "---",
      "TOHIT": "---",
      "maxhit": "",
      "MAXHIT": "",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "236",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Len",
      "NAME4": "Lene",
      "NAME5": "Lenex",
      "NAME6": "Lenex",
      "NAME7": "Lenex Z",
      "NAME8": "Lenex Ze",
      "NAME9": "Lenex Zem",
      "NAME10": "Lenex Zemp",
      "NAME11": "Lenex Zemph",
      "NAME12": "Lenex Zempho",
      "NAME13": "Lenex Zemphon",
      "NAME14": "Lenex Zemphoni",
      "NAME15": "Lenex Zemphonia",
      "Last10DPS": "10",
      "Last30DPS": "",
      "Last60DPS": "",
      "Job": "",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "75.00",
      "OverHealPct": "0%"
    },
    "Cid Garlond": {
      "n": "\n",
      "t": "\t",
      "name": "Cid Garlond",
      "duration": "00:00",
      "DURATION": "0",
      "damage": "0",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "---",
      "DPS": "---",
      "DPS-k": "---",
      "encdps": "0.00",
      "ENCDPS": "0",
      "ENCDPS-k": "0",
      "hits": "0",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "0",
      "tohit": "---",
      "TOHIT": "---",
      "maxhit": "",
      "MAXHIT": "",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "236",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Cid",
      "NAME4": "Cid ",
      "NAME5": "Cid G",
      "NAME6": "Cid Ga",
      "NAME7": "Cid Gar",
      "NAME8": "Cid Garl",
      "NAME9": "Cid Garlo",
      "NAME10": "Cid Garlon",
      "NAME11": "Cid Garlond",
      "NAME12": "Cid Garlond",
      "NAME13": "Cid Garlond",
      "NAME14": "Cid Garlond",
      "NAME15": "Cid Garlond",
      "Last10DPS": "10",
      "Last30DPS": "",
      "Last60DPS": "",
      "Job": "Mch",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "75.00",
      "OverHealPct": "0%"
    },
    "Star Gazer": {
      "n": "\n",
      "t": "\t",
      "name": "Star Gazer",
      "duration": "00:00",
      "DURATION": "0",
      "damage": "0",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "---",
      "DPS": "---",
      "DPS-k": "---",
      "encdps": "0.00",
      "ENCDPS": "0",
      "ENCDPS-k": "0",
      "hits": "0",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "0",
      "tohit": "---",
      "TOHIT": "---",
      "maxhit": "",
      "MAXHIT": "",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "236",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Sta",
      "NAME4": "Star",
      "NAME5": "Star ",
      "NAME6": "Star G",
      "NAME7": "Star Ga",
      "NAME8": "Star Gaz",
      "NAME9": "Star Gaze",
      "NAME10": "Star Gazer",
      "NAME11": "Star Gazer",
      "NAME12": "Star Gazer",
      "NAME13": "Star Gazer",
      "NAME14": "Star Gazer",
      "NAME15": "Star Gazer",
      "Last10DPS": "10",
      "Last30DPS": "",
      "Last60DPS": "",
      "Job": "Ast",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "75.00",
      "OverHealPct": "0%"
    },
    "Darth Vader": {
      "n": "\n",
      "t": "\t",
      "name": "Darth Vader",
      "duration": "00:00",
      "DURATION": "0",
      "damage": "0",
      "damage-m": "0.00",
      "DAMAGE-k": "0",
      "DAMAGE-m": "0",
      "damage%": "0%",
      "dps": "---",
      "DPS": "---",
      "DPS-k": "---",
      "encdps": "0.00",
      "ENCDPS": "0",
      "ENCDPS-k": "0",
      "hits": "0",
      "crithits": "0",
      "crithit%": "0%",
      "misses": "0",
      "hitfailed": "0",
      "swings": "0",
      "tohit": "---",
      "TOHIT": "---",
      "maxhit": "",
      "MAXHIT": "",
      "healed": "0",
      "healed%": "0%",
      "enchps": "0.00",
      "ENCHPS": "0",
      "ENCHPS-k": "0",
      "critheals": "0",
      "critheal%": "0%",
      "heals": "0",
      "cures": "0",
      "maxheal": "",
      "MAXHEAL": "",
      "maxhealward": "",
      "MAXHEALWARD": "",
      "damagetaken": "236",
      "healstaken": "0",
      "powerdrain": "0",
      "powerheal": "0",
      "kills": "0",
      "deaths": "0",
      "threatstr": "+(0)0/-(0)0",
      "threatdelta": "0",
      "NAME3": "Dar",
      "NAME4": "Dart",
      "NAME5": "Darth",
      "NAME6": "Darth ",
      "NAME7": "Darth V",
      "NAME8": "Darth Va",
      "NAME9": "Darth Vad",
      "NAME10": "Darth Vade",
      "NAME11": "Darth Vader",
      "NAME12": "Darth Vader",
      "NAME13": "Darth Vader",
      "NAME14": "Darth Vader",
      "NAME15": "Darth Vader",
      "Last10DPS": "10",
      "Last30DPS": "",
      "Last60DPS": "",
      "Job": "Drk",
      "ParryPct": "0%",
      "BlockPct": "0%",
      "IncToHit": "75.00",
      "OverHealPct": "0%"
    }
  },
};
