name: 'Setup Node and run npm ci'
description: "run actions/setup-node and `npm ci`"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install Dependencies
      shell: bash
      run: npm ci
