import Conditions from '../../../../../resources/conditions';
import Outputs from '../../../../../resources/outputs';
import { Responses } from '../../../../../resources/responses';
import ZoneId from '../../../../../resources/zone_id';
import { RaidbossData } from '../../../../../types/data';
import { TriggerSet } from '../../../../../types/trigger';

// all Masked Carnivale Stages/Acts take place in the same zone
// 01|2022-11-01T12:26:48.9250000-04:00|31C|All's Well That Starts Well|
// 0x31C = 796 = ZoneId.AllsWellThatStartsWell
// default zone is Stage 01 - All's Well That Starts Well
// actual zone was Stage 03 - Waiting for Golem
// there are unique Instance Content IDs for each Masked Carnivale Stage
// first Instance Content ID appearance is an Actor Control (0x21 = 33) line
// 33|2022-11-01T12:26:52.0770000-04:00|800388BB|40000001|708|00|00|00|
// 0x40000001 = Initial Commence, 0x708 = 1800s = 30m = instance timer
// 0x8003 = instance content update, 0x88BB = 35003 = InstanceContentType
// https://xivapi.com/InstanceContent/35003?pretty=true (Waiting for Golem)
// Masked Carnivale missing from cactbot/resources/content_list.ts
// Masked Carnivale info not auto-generated by cactbot/util/gen_zone_id_and_info.py (partial data generated)
// Masked Carnivale missing from cactbot/resources/zone_info.ts (auto-generated) (entry for Stage 1 only)
// Masked Carnivale missing from cactbot/resources/content_type.ts (auto-generated) (ContentType = 27)

export interface Data extends RaidbossData {
  blind?: boolean;
  act2?: boolean;
}

const triggerSet: TriggerSet<Data> = {
  zoneId: ZoneId.AllsWellThatStartsWell,
  // timelineFile: 'the_masked_carnivale.txt',
  // initData: () => {
  //   return {
  //     blind: false,
  //   };
  // },
  triggers: [
    // ================ Stage 01 Act 1 ================
    // intentionally blank
    // ================ Stage 02 Act 1 ================
    // intentionally blank
    // ---------------- Stage 02 Act 2 ----------------
    // intentionally blank
    // ================ Stage 03 Act 1 ================
    {
      id: 'Carnivale S03 A1 Zipacna Obliterate',
      type: 'StartsUsing',
      netRegex: { id: '381D', source: 'Zipacna' },
      response: Responses.interrupt(),
    },
    // ================ Stage 04 Act 1 ================
    // intentionally blank
    // ---------------- Stage 04 Act 2 ----------------
    {
      id: 'Carnivale S04 A2 Kreios Magitek Field',
      type: 'StartsUsing',
      netRegex: { id: '3821', source: 'Kreios' },
      response: Responses.interrupt(),
    },
    // ================ Stage 05 Act 1 ================
    // intentionally blank
    // ================ Stage 06 Act 1 ================
    {
      id: 'Carnivale S06 A1-2 Blind Gain',
      // 23B = Blind (can't be hit by gaze attacks)
      type: 'GainsEffect',
      netRegex: { effectId: '23B' },
      condition: Conditions.targetIsYou(),
      preRun: (data) => data.blind = true,
    },
    {
      id: 'Carnivale S06 A1-2 Blind Lose',
      // 23B = Blind (can't be hit by gaze attacks)
      type: 'LosesEffect',
      netRegex: { effectId: '23B' },
      condition: Conditions.targetIsYou(),
      run: (data) => delete data.blind,
    },
    {
      id: 'Carnivale S06 A1-2 Arena Catoblepas Demon Eye',
      // if Blind then can't be hit by gaze attacks
      type: 'StartsUsing',
      netRegex: { id: '3963', source: 'Arena Catoblepas', capture: false },
      suppressSeconds: 1,
      infoText: (data, _matches, output) => {
        if (!data.blind)
          return output.lookAway!();
      },
      outputStrings: {
        lookAway: Outputs.lookAway,
      },
    },
    // ---------------- Stage 06 Act 2 ----------------
    {
      id: 'Carnivale S06 A2 Arena Eye Dread Gaze',
      // if Blind then can't be hit by gaze attacks
      type: 'StartsUsing',
      netRegex: { id: '3966', source: 'Arena Eye', capture: false },
      suppressSeconds: 1,
      infoText: (data, _matches, output) => {
        if (!data.blind)
          return output.lookAway!();
      },
      outputStrings: {
        lookAway: Outputs.lookAway,
      },
    },
    // ================ Stage 07 Act 1 ================
    // intentionally blank
    // ---------------- Stage 07 Act 2 ----------------
    // intentionally blank
    // ---------------- Stage 07 Act 3 ----------------
    {
      id: 'Carnivale S07 A3 Gladiatorial Node Low Voltage',
      type: 'StartsUsing',
      netRegex: { source: 'Gladiatorial Node', id: '3976' },
      delaySeconds: (_data, matches) => parseFloat(matches.castTime) - 3,
      suppressSeconds: 1,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Hide Behind Barricade',
          de: 'Hinter den Barrikaden verstecken',
          fr: 'Cachez-vous derrière la barricade',
          ja: '柵の後ろに',
          cn: '躲在栅栏后',
          ko: '울타리 뒤에 숨기',
        },
      },
    },
    // ================ Stage 08 Act 1 ================
    // intentionally blank
    // ---------------- Stage 08 Act 2 ----------------
    {
      id: 'Carnivale S08 A2 Arena Progenitrix Burst',
      type: 'StartsUsing',
      netRegex: { id: '3958', source: 'Arena Progenitrix' },
      response: Responses.interrupt(),
    },
    // ================ Stage 09 Act 1 ================
    {
      id: 'Carnivale S09 A1 Guimauve Golden Tongue',
      type: 'StartsUsing',
      netRegex: { id: '37B9', source: 'Guimauve' },
      response: Responses.interrupt(),
    },
    // ================ Stage 10 Act 1 ================
    {
      id: 'Carnivale S10 A1 Crom Dubh King\'s Will',
      // if attempting The Harder They Fall achievement, do not interrupt this cast
      type: 'StartsUsing',
      netRegex: { id: '397F', source: 'Crom Dubh' },
      response: Responses.interrupt(),
    },
    {
      id: 'Carnivale S10 A1 Crom Dubh Black Nebula',
      type: 'StartsUsing',
      netRegex: { id: '3984', source: 'Crom Dubh' },
      response: Responses.interrupt(),
    },
    // ================ Stage 11 Act 1 ================
    {
      id: 'Carnivale S11 A1-2 Arena Gas Bomb Fulmination',
      // Arena Gas Bombs (x2 Act 1, x4 Act 2) channel a long cast (22.7s) which is lethal if completed
      // this cast can be interrupted (immediate re-cast) by doing any damage to them; warn when this cast is about to finish
      // TODO: this trigger is janky; trigger can overlap from multiple targets in unintended ways,
      //   and trigger still fires if target dies
      type: 'StartsUsing',
      netRegex: { id: '38F7', source: 'Arena Gas Bomb' },
      delaySeconds: (_data, matches) => parseFloat(matches.castTime) - 5,
      suppressSeconds: 5,
      response: Responses.stunOrInterruptIfPossible(),
    },
    // ---------------- Stage 11 Act 2 ----------------
    // intentionally blank
    // ================ Stage 12 Act 1 ================
    // intentionally blank
    // ---------------- Stage 12 Act 2 ----------------
    {
      id: 'Carnivale S12 A2 Hydnora Inflammable Fumes',
      type: 'StartsUsing',
      netRegex: { id: '39A1', source: 'Hydnora' },
      response: Responses.stun(),
    },
    {
      id: 'Carnivale S12 A2 Hydnora Spore Sac',
      // spawns several Arena Roselets which can be killed individually
      // or can use Ice Spikes to reflect their attacks and kill them all at once
      type: 'StartsUsing',
      netRegex: { id: '39A0', source: 'Hydnora', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Arena Roselets spawning!',
        },
      },
    },
    // ================ Stage 13 Act 1 ================
    // intentionally blank
    // ---------------- Stage 13 Act 2 ----------------
    {
      id: 'Carnivale S13 A2 Carmilla Dark Sabbath',
      type: 'StartsUsing',
      netRegex: { id: '3A67', source: 'Carmilla', capture: false },
      response: Responses.lookAway(),
    },
    {
      id: 'Carnivale S13 A2 Carmilla Summon Darkness',
      // add needs to be killed before Carmilla consumes it
      // if not killed in time, Carmilla gains a Damage Up buff and kills the player
      type: 'AddedCombatant',
      netRegex: { name: 'Arena Succubus' },
      infoText: (_data, matches, output) => output.kill!({ name: matches.name }),
      outputStrings: {
        kill: {
          en: 'Kill ${name}',
          de: 'Besiege ${name}',
          fr: 'Tuez ${name}',
          ja: '${name}を倒す',
          cn: '击杀 ${name}',
          ko: '${name} 처치',
        },
      },
    },
    {
      id: 'Carnivale S13 A2 Arena Succubus Beguiling Mist',
      type: 'StartsUsing',
      netRegex: { id: '3AC5', source: 'Arena Succubus' },
      response: Responses.interrupt(),
    },
    // ================ Stage 14 Act 1 ================
    {
      id: 'Carnivale S14 A1-2 Arena Jam The Last Song',
      type: 'StartsUsing',
      netRegex: { source: 'Arena Jam', id: '39A4' },
      delaySeconds: (_data, matches) => parseFloat(matches.castTime) - 3,
      suppressSeconds: 1,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Hide Behind Barricade',
          de: 'Hinter den Barrikaden verstecken',
          fr: 'Cachez-vous derrière la barricade',
          ja: '柵の後ろに',
          cn: '躲在栅栏后',
          ko: '울타리 뒤에 숨기',
        },
      },
    },
    // ---------------- Stage 14 Act 2 ----------------
    // intentionally blank
    // ================ Stage 15 Act 1 ================
    {
      id: 'Carnivale S15 A1 Bestial Node High Voltage',
      type: 'StartsUsing',
      netRegex: { id: '3A2A', source: 'Bestial Node' },
      response: Responses.interrupt(),
    },
    {
      id: 'Carnivale S15 A1 Arena Shabti Spawn',
      // Arena Shabti spawns with a Damage Up buff that makes its attacks very dangerous
      // can Sleep the Arena Shabti until the buff expires
      type: 'AddedCombatant',
      netRegex: { name: 'Arena Shabti' },
      alertText: (_data, matches, output) => output.sleep!({ name: matches.name }),
      outputStrings: {
        sleep: Outputs.sleepTarget,
      },
    },
    {
      id: 'Carnivale S15 A1 Bestial Node Superstorm',
      type: 'StartsUsing',
      netRegex: { id: '3A7B', source: 'Bestial Node', capture: false },
      response: Responses.getIn(),
    },
    {
      id: 'Carnivale S15 A1 Bestial Node Repelling Cannons',
      type: 'StartsUsing',
      netRegex: { id: '3A2C', source: 'Bestial Node', capture: false },
      response: Responses.getOut(),
    },
    {
      id: 'Carnivale S15 A1 Bestial Node Ballast',
      type: 'StartsUsing',
      netRegex: { id: '3A2D', source: 'Bestial Node', capture: false },
      response: Responses.getBehind(),
    },
    // ================ Stage 16 Act 1 ================
    // intentionally blank
    // ---------------- Stage 16 Act 2 ----------------
    {
      id: 'Carnivale S16 A2 Tikbalang 10-tonze Slash',
      type: 'StartsUsing',
      netRegex: { id: '3A17', source: 'Tikbalang', capture: false },
      response: Responses.awayFromFront(),
    },
    {
      id: 'Carnivale S16 A2 Tikbalang 111-tonze Swing',
      type: 'StartsUsing',
      netRegex: { id: '3A18', source: 'Tikbalang', capture: false },
      response: Responses.getOut(),
    },
    {
      id: 'Carnivale S16 A2 Tikbalang Cry of Rage',
      type: 'StartsUsing',
      netRegex: { id: '3A1B', source: 'Tikbalang', capture: false },
      response: Responses.lookAway(),
    },
    {
      id: 'Carnivale S16 A2 Tikbalang 1111-tonze Swing',
      // Tikbalang casts The Bull's Voice (39BB) to give himself a Damage Up (122) buff,
      // then uses Predatorial Instinct (395D) to give the player an uncleansable Heavy (F0) and draw them in,
      // then begins casting 1111-tonze Swing (395E) which is lethal if not mitigated
      type: 'StartsUsing',
      netRegex: { id: '395E', source: 'Tikbalang', capture: false },
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Diamondback',
        },
      },
    },
    {
      id: 'Carnivale S16 A2 Tikbalang Zoom In',
      type: 'StartsUsing',
      netRegex: { id: '3A19', source: 'Tikbalang', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Charge + knockback',
        },
      },
    },
    {
      id: 'Carnivale S16 A2 Tikbalang 10-tonze Wave',
      // front cleave with donut aoe
      type: 'StartsUsing',
      netRegex: { id: '3A1C', source: 'Tikbalang', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Away from front + in',
        },
      },
    },
    // ================ Stage 17 Act 1 ================
    // intentionally blank
    // ---------------- Stage 17 Act 2 ----------------
    {
      id: 'Carnivale S17 A2 Kreios Magitek Field',
      // same name, different id from S04 A2
      type: 'StartsUsing',
      netRegex: { id: '3AC9', source: 'Kreios' },
      response: Responses.interrupt(),
    },
    // ================ Stage 18 Act 1 ================
    {
      id: 'Carnivale S18 A1-2 Arena Manticore Wild Charge',
      // non-telegraphed charge + knockback
      type: 'StartsUsing',
      netRegex: { id: '3ACF', source: 'Arena Manticore', capture: false },
      suppressSeconds: 1,
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Charge + knockback',
        },
      },
    },
    {
      id: 'Carnivale S18 A1-2 Arena Manticore Ripper Claw',
      // non-telegraphed front cleave
      type: 'StartsUsing',
      netRegex: { id: '3ACA', source: 'Arena Manticore', capture: false },
      suppressSeconds: 1,
      response: Responses.awayFromFront(),
    },
    {
      id: 'Carnivale S18 A1-2 Arena Manticore Fireball',
      // non-telegraphed ranged aoe
      type: 'StartsUsing',
      netRegex: { id: '3ACB', source: 'Arena Manticore', capture: false },
      suppressSeconds: 1,
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Fireball',
        },
      },
    },
    // ---------------- Stage 18 Act 2 ----------------
    // intentionally blank
    // ================ Stage 19 Act 1 ================
    {
      id: 'Carnivale S19 A1-2 Reflective Rebekkah Reflect',
      // reflects all magic attacks
      type: 'StartsUsing',
      netRegex: { id: '3AE1', source: 'Reflective Rebekkah', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Magic reflect',
        },
      },
    },
    {
      id: 'Carnivale S19 A1-2 Reflective Rebekkah Offal Breath',
      type: 'StartsUsing',
      netRegex: { id: '3AE4', source: 'Reflective Rebekkah' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 19 Act 2 ----------------
    {
      id: 'Carnivale S19 A2 Reflective Rebekkah Schizocarps',
      // spawns 8x Hot Hips around the arena that do a simultaneous gaze attack
      // can either look away from all Hot Hips or Blind yourself to dodge the gazes
      type: 'StartsUsing',
      netRegex: { id: '3AE5', source: 'Reflective Rebekkah', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Blind yourself or Look Away',
        },
      },
    },
    // ================ Stage 20 Act 1 ================
    {
      id: 'Carnivale S20 A1,3 Typhon Snort',
      // Typhon casts Snort to knock the player back,
      // then uses 3x un-telegraphed Fireballs that do very high damage if not mitigated
      type: 'StartsUsing',
      netRegex: { id: '3970', source: 'Typhon', capture: false },
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Diamondback',
        },
      },
    },
    // ---------------- Stage 20 Act 2 ----------------
    {
      id: 'Carnivale S20 A2 Ultros Imp Song',
      type: 'StartsUsing',
      netRegex: { id: '3978', source: 'Ultros' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 20 Act 3 ----------------
    {
      id: 'Carnivale S20 A3 Ultros Imp Song',
      // same name, different id from S20 A2
      type: 'StartsUsing',
      netRegex: { id: '3998', source: 'Ultros' },
      response: Responses.interrupt(),
    },
    {
      id: 'Carnivale S20 A3 Stylish Tentacle Clearout',
      type: 'Ability',
      netRegex: { id: '399D', source: 'Stylish Tentacle', capture: false },
      response: Responses.knockback(),
    },
    // ================ Stage 21 Act 1 ================
    {
      id: 'Carnivale S21 A1-2 Arena Imp Void Blizzard',
      type: 'StartsUsing',
      netRegex: { id: '3AD7', source: 'Arena Imp' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 21 Act 2 ----------------
    {
      id: 'Carnivale S21 A2 Act Start',
      // triggers off of the first autoattack in S21 A2
      type: 'Ability',
      netRegex: { id: '1961', source: 'Apademak', capture: false },
      preRun: (data) => data.act2 = true,
      suppressSeconds: 999999,
    },
    {
      id: 'Carnivale S21 A2 Apademak The Ram\'s Voice',
      type: 'StartsUsing',
      netRegex: { id: '3AE7', source: 'Apademak', capture: false },
      response: Responses.getOut(),
    },
    {
      id: 'Carnivale S21 A2 Apademak The Dragon\'s Voice',
      type: 'StartsUsing',
      netRegex: { id: '3AE8', source: 'Apademak', capture: false },
      response: Responses.getIn(),
    },
    {
      id: 'Carnivale S21 A2 Apademak The Ram\'s Keeper',
      type: 'StartsUsing',
      netRegex: { id: '3AE9', source: 'Apademak' },
      response: Responses.interrupt(),
    },
    {
      id: 'Carnivale S21 A2 Arena Imp Spawn',
      // not necessary to kill add, but warn when spawned
      type: 'AddedCombatant',
      netRegex: { name: 'Arena Imp', capture: false },
      infoText: (data, _matches, output) => {
        if (data.act2)
          return output.addSpawned!();
      },
      outputStrings: {
        addSpawned: {
          en: 'Add spawned!',
        },
      },
    },
    // ================ Stage 22 Act 1 ================
    // intentionally blank
    // ---------------- Stage 22 Act 2 ----------------
    {
      id: 'Carnivale S22 A2 Act Start',
      // triggers off of the first autoattack in S22 A2
      type: 'Ability',
      netRegex: { id: '1963', source: 'The Forefather', capture: false },
      preRun: (data) => data.act2 = true,
      suppressSeconds: 999999,
    },
    {
      id: 'Carnivale S22 A2 The Forefather Sap',
      // aoe under the player, followed by several aoes around the room with one safe spot
      type: 'Ability',
      netRegex: { id: '3A3A', source: 'The Forefather', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Get to Safe Spot',
        },
      },
    },
    {
      id: 'Carnivale S22 A2 Arena Grenade Spawn',
      // Arena Grenades spawn with Sleep; if they wake up they will do lethal damage
      // Arena Grenades can be killed with a single standard (220p) attack spell
      // Arena Grenades need to be killed before the boss casts Ignition (light roomwide attack, wakes Grenades)
      type: 'AddedCombatant',
      netRegex: { name: 'Arena Grenade' },
      alertText: (data, matches, output) => {
        if (data.act2)
          return output.kill!({ name: matches.name });
      },
      outputStrings: {
        kill: {
          en: 'Kill ${name}',
          de: 'Besiege ${name}',
          fr: 'Tuez ${name}',
          ja: '${name}を倒す',
          cn: '击杀 ${name}',
          ko: '${name} 처치',
        },
      },
    },
    {
      id: 'Carnivale S22 A2 Arena Gas Bomb Spawn',
      // The Forefather will cast Burst, a non-interruptable, lethal roomwide attack
      // Arena Gas Bombs cast Flashthoom, a small aoe which will interrupt Burst
      // Arena Gas Bombs spawn on the edge of the room and need to be pulled in range of the boss
      type: 'AddedCombatant',
      netRegex: { name: 'Arena Gas Bomb' },
      alertText: (data, matches, output) => {
        if (data.act2)
          return output.pullToBoss!({ name: matches.name });
      },
      outputStrings: {
        pullToBoss: {
          en: 'Pull ${name} to boss',
        },
      },
    },
    // ================ Stage 23 Act 1 ================
    {
      id: 'Carnivale S23 A1 Kronprinz Behemoth Ecliptic Meteor',
      // Ecliptic Meteor (9.7s cast) is lethal if not mitigated
      // delay slightly so Diamondback doesn't run out too fast
      type: 'StartsUsing',
      netRegex: { id: '3B99', source: 'Kronprinz Behemoth', capture: false },
      delaySeconds: 1,
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Diamondback',
        },
      },
    },
    // ================ Stage 24 Act 1 ================
    // intentionally blank
    // ---------------- Stage 24 Act 2 ----------------
    {
      id: 'Carnivale S24 A2 Arena Scribe Silence',
      type: 'StartsUsing',
      netRegex: { id: '3BD9', source: 'Arena Scribe' },
      response: Responses.interrupt(),
    },
    {
      id: 'Carnivale S24 A2 Arena Scribe Condensed Libra',
      // 38 = Physical Vulnerability Up
      // will make next attack (Triple Hit, 3BD8) lethal
      type: 'GainsEffect',
      netRegex: { effectId: '38' },
      condition: Conditions.targetIsYou(),
      alertText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Cleanse vulnerability or mitigate',
        },
      },
    },
    // ---------------- Stage 24 Act 3 ----------------
    {
      id: 'Carnivale S24 A3 Epilogi Page Tear',
      type: 'StartsUsing',
      netRegex: { id: '3BDC', source: 'Epilogi', capture: false },
      response: Responses.awayFromFront(),
    },
    {
      id: 'Carnivale S24 A3 Epilogi Head Down',
      type: 'StartsUsing',
      netRegex: { id: '3BDD', source: 'Epilogi', capture: false },
      infoText: (_data, _matches, output) => output.text!(),
      outputStrings: {
        text: {
          en: 'Knockback into Safe Spot',
        },
      },
    },
    {
      id: 'Carnivale S24 A3 Epilogi Bone Shaker',
      // aoe + spawns adds
      type: 'Ability',
      netRegex: { id: '3BDE', source: 'Epilogi', capture: false },
      response: Responses.killAdds(),
    },
    // ================ Stage 25 Act 1 ================
    // ---------------- Stage 25 Act 2 ----------------
    // ---------------- Stage 25 Act 3 ----------------
    // ================ Stage 26 Act 1 ================
    // ---------------- Stage 26 Act 2 ----------------
    // ================ Stage 27 Act 1 ================
    // ================ Stage 28 Act 1 ================
    // ================ Stage 29 Act 1 ================
    {
      id: 'Carnivale S29 A1 Pyre Fluid Swing',
      type: 'StartsUsing',
      netRegex: { id: '4901', source: 'Shikigami of the Pyre' },
      response: Responses.interrupt(),
    },
    // ---------------- Stage 29 Act 2 ----------------
    {
      id: 'Carnivale S29 A2 Undertow Fluid Swing',
      type: 'StartsUsing',
      netRegex: { id: '4A11', source: 'Shikigami of the Undertow' },
      response: Responses.interrupt(),
    },
    // ================ Stage 30 Act 1 ================
    // ---------------- Stage 30 Act 2 ----------------
    // ---------------- Stage 30 Act 3 ----------------
    // ================ Stage 31 Act 1 ================
    // ---------------- Stage 31 Act 2 ----------------
  ],
};

export default triggerSet;
