// This file was autogenerated from running ts-node util/sync_files.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

import NetRegexes from '../../../../../resources/netregexes';
import ZoneId from '../../../../../resources/zone_id';
import { OopsyData } from '../../../../../types/data';
import { OopsyTriggerSet } from '../../../../../types/oopsy';
import { playerDamageFields } from '../../../oopsy_common';

// TODO: does Shishu Onmitsugashira Issen TODO cleave?
// TODO: does Splitting Cry 8442 cleave?
// TODO: taking both Vermilion Aura 8436 and Stygian Aura 8437
// TODO: taking two Unnatural Force 8440 stacks
// TODO: standing in outside of Shishio arena
// TODO: better track who didn't take Shishio towers
// TODO: does Gorai Torching Torment cleave?
// TODO: Humble Hammer share damage
// TODO: who missed Gorai towers or was not hit by protean
// TODO: does Lateral Slice cleave
// TODO: TODO whose adds were too close

export type Data = OopsyData;

const triggerSet: OopsyTriggerSet<Data> = {
  zoneId: ZoneId.AnotherMountRokkonSavage,
  damageWarn: {
    // Trash 1
    'AMRS Shishu Raiko Disciples of Levin': '8668', // centered circle
    'AMRS Shishu Raiko Master of Levin': '8667', // very large donut
    'AMRS Shishu Furutsubaki Bloody Carress': '8669', // front conal
    'AMRS Shishu Fuko Scythe Tail': '866C', // centered circle
    'AMRS Red Shishu Penghou Tornado': 'TODO', // targeted circle
    'AMRS Shishu Yuki Right Swipe': '8688', // 180 right cleave
    'AMRS Shishu Yuki Left Swipe': '8689', // 180 left cleave

    // Shishio
    'AMRS Shishio Rokujo Revel': '8425', // Smokeater line
    'AMRS Shishio Raiun Leaping Levin 1': '8426', // Raiun 1x Smokeater small cloud circles
    'AMRS Shishio Raiun Leaping Levin 2': '8427', // Raiun 1x Smokeater medium cloud circles
    'AMRS Shishio Raiun Leaping Levin 3': '8428', // Raiun 1x Smokeater large cloud circles
    'AMRS Shishio Lightning Bolt': '842A', // initial Cloud to Cloud circles
    'AMRS Shishio Cloud to Cloud 1': '842B', // 1x Smokeater small lines
    'AMRS Shishio Cloud to Cloud 2': '824C', // 2x Smokeater medium lines
    'AMRS Shishio Cloud to Cloud 3': '824D', // 3x Smokeater large lines
    'AMRS Shishio Noble Pursuit 1': '842E', // initial charge line
    'AMRS Shishio Noble Pursuit 2': '842F', // followup charge line
    'AMRS Shishio Levinburst': '8430', // line damage during Noble Pursuit
    'AMRS Shishio Devilish Thrall Right Swipe': '8432', // 180 right cleave from adds
    'AMRS Shishio Devilish Thrall Left Swipe': '8433', // 180 left cleave from adds
    'AMRS Shishio Haunting Thrall Reisho': '8434', // untelegraphed white explosions from Thralls
    'AMRS Shishio Thunder Vortex': '8439', // donut
    'AMRS Shishio Eye of the Thunder Vortex 1': '843A', // first "out" circle
    'AMRS Shishio Eye of the Thunder Vortex 2': '843B', // second "in" donut
    'AMRS Shishio Vortex of the Thunder Eye 1': '843C', // first "in" donut
    'AMRS Shishio Vortex of the Thunder Eye 2': '843D', // second "out" circle
    'AMRS Shishio Slither': '8443', // back conal

    // Trash 2
    'AMRS Shishu Yamabiko': 'TODO', // sprite line aoe
    'AMRS Shishu Kotengu Blade of the Tengu': 'TODO', // Leftward/Rightward/Backward Blows
    'AMRS Shishu Onmitsugashira Juji Shuriken': 'TODO', // untelegraphed front line
    'AMRS Shishu Onmitsugashira Juji Shuriken Huton': 'TODO', // untelegraphed fast front line on all players

    // Gorai
    'AMRS Gorai Fire Spread Purple': 'TODO', // line damage after purple Brazen Ballad
    'AMRS Gorai Fire Spread Blue': 'TODO', // line damage after blue Brazen Ballad
    'AMRS Gorai Falling Rock Purple': 'TODO', // expanded rock damage after purple Brazen Ballad
    'AMRS Gorai Falling Rock Blue': 'TODO', // donutified rock damage after purple Brazen Ballad
    'AMRS Gorai Ball of Levin Shock Small': 'TODO', // small circle from Ball of Levin hit by Humble Hammer
    'AMRS Gorai Ball of Levin Shock Big': 'TODO', // large circle from Ball of Levin
    'AMRS Gorai Cloud to Ground 1': 'TODO', // initial cloud exaflare
    'AMRS Gorai Cloud to Ground 2': 'TODO', // ongoing cloud exaflare
    'AMRS Gorai Impure Purgation Second': 'TODO', // follow-up protean'

    // Moko
    'AMRS Moko Triple Kasumi-Giri 1': 'TODO', // back red first
    'AMRS Moko Triple Kasumi-Giri 2': 'TODO', // left red first
    'AMRS Moko Triple Kasumi-Giri 3': 'TODO', // front red first
    'AMRS Moko Triple Kasumi-Giri 4': 'TODO', // right red first
    'AMRS Moko Triple Kasumi-Giri 5': 'TODO', // back red followup
    'AMRS Moko Triple Kasumi-Giri 6': 'TODO', // left red followup
    'AMRS Moko Triple Kasumi-Giri 7': 'TODO', // front red followup
    'AMRS Moko Triple Kasumi-Giri 8': 'TODO', // right red followup
    'AMRS Moko Triple Kasumi-Giri 9': 'TODO', // back blue first
    'AMRS Moko Triple Kasumi-Giri 10': 'TODO', // left blue first
    'AMRS Moko Triple Kasumi-Giri 11': 'TODO', // front blue first
    'AMRS Moko Triple Kasumi-Giri 12': 'TODO', // right blue first
    'AMRS Moko Triple Kasumi-Giri 13': 'TODO', // back blue followup
    'AMRS Moko Triple Kasumi-Giri 14': 'TODO', // left blue followup
    'AMRS Moko Triple Kasumi-Giri 15': 'TODO', // front blue followup
    'AMRS Moko Triple Kasumi-Giri 16': 'TODO', // right blue followup
    'AMRS Moko Unbound Spirit': 'TODO', // red "out" Triple Kasumi-Giri
    'AMRS Moko Azure Coil': 'TODO', // blue "in" Triple Kasumi-Giri

    'AMRS Moko Scarlet Auspice': 'TODO', // "get out" before Boundless Scarlet
    'AMRS Moko Boundless Scarlet': 'TODO', // initial red lines before they grow
    'AMRS Moko Explosion': 'TODO', // growing red lines
    'AMRS Moko Azure Auspice': 'TODO', // "get under" donut before Boundless Azure
    'AMRS Moko Boundless Azure': 'TODO', // initial blue lines before they bounce
    'AMRS Moko Upwell 1': 'TODO', // blue line first bounce
    'AMRS Moko Upwell 2': 'TODO', // blue line ongoing bounces

    'AMRS Moko Fleeting Iai-Giri 1': 'TODO', // back purple
    'AMRS Moko Fleeting Iai-Giri 2': 'TODO', // left purple
    'AMRS Moko Fleeting Iai-Giri 3': 'TODO', // right purple

    'AMRS Moko Shadow Kasumi-Giri 1': 'TODO', // back purple first
    'AMRS Moko Shadow Kasumi-giri 2': 'TODO', // left purple followup
    'AMRS Moko Shadow Kasumi-giri 3': 'TODO', // front purple followup
    'AMRS Moko Shadow Kasumi-giri 4': 'TODO', // right purple followup

    'AMRS Moko Oni\'s Claw Clearout 1': 'TODO', // hit 1 of large circles
    'AMRS Moko Oni\'s Claw Clearout 2': 'TODO', // hit 2 of large circles
    'AMRS Moko Oni\'s Claw Clearout 3': 'TODO', // hit 3 of large circles

    'AMRS Moko Ashigaru Kyuhei Iron Rain 1': 'TODO', // initial medium circle damage from red Ashigaru Kyuheis
    'AMRS Moko Ashigaru Kyuhei Iron Rain 2': 'TODO', // followup medium circle damage from red Ashigaru Kyuheis
    'AMRS Moko Ashigaru Kyuhei Iron Storm 1': 'TODO', // initial big circle damage from blue Ashigaru Kyuhei
    'AMRS Moko Ashigaru Kyuhei Iron Storm 2': 'TODO', // followup big circle damage from blue Ashigaru Kyuhei
  },
  damageFail: {
    'AMRS Shishio Unmitigated Explosion': '8438', // not taking towers
  },
  gainsEffectWarn: {
    // BF9 = 9999s duration, BFA = 15s duration
    'AMRS Gorai Burns': 'BF9', // standing in outside square of Gorai
  },
  shareWarn: {
    'AMRS Shishu Raiko Barreling Smash': '8665', // line charge
    'AMRS Gorai Pointed Purgation': 'TODO', // protean tether during towers
    'AMRS Gorai Impure Purgation': 'TODO', // initial protean for double hit protean
  },
  shareFail: {
    'AMRS Shishio Unnatural Ailment': '843F', // spread during Unnatural Wail
    'AMRS Gorai Great Ball of Fire': 'TODO', // spread damage from Live Candle debuff
    'AMRS Gorai Worldy Pursuit': 'TODO', // cross jumps
    'AMRS Moko Vengeful Flame': 'TODO', // spreads during Fleeting Iai-giri
    'AMRS Moko Accursed Edge': 'TODO', // bind on players from Far Edge / Near Edge
  },
  soloFail: {
    'AMRS Shishio Unnatural Force': '8440', // pair stack during Unnatural Wail
    'AMRS Gorai Greater Ball of Fire': 'TODO', // pair stack from Live Brazier debuff
    'AMRS Gorai Flintlock': 'TODO', // tank block line share
    'AMRS Moko Vengeful Pyre': 'TODO', // pair stack during Fleeting Iai-giri
  },
  triggers: [
    {
      id: 'AMRS Shishu Kotengu Gaze of the Tengu',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: 'TODO', ...playerDamageFields }),
      condition: (data, matches) => data.DamageFromMatches(matches) > 0,
      mistake: (_data, matches) => {
        return {
          type: 'fail',
          blame: matches.target,
          reportId: matches.targetId,
          text: matches.ability,
        };
      },
    },
  ],
};

export default triggerSet;
