// This file was autogenerated from running ts-node util/sync_files.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

import NetRegexes from '../../../../../resources/netregexes';
import ZoneId from '../../../../../resources/zone_id';
import { OopsyData } from '../../../../../types/data';
import { OopsyTriggerSet } from '../../../../../types/oopsy';
import { playerDamageFields } from '../../../oopsy_common';

// TODO: does Shishu Onmitsugashira Issen TODO cleave?
// TODO: does Splitting Cry TODO cleave?
// TODO: taking both Vermilion Aura TODO and Stygian Aura TODO
// TODO: taking two Unnatural Force TODO stacks
// TODO: standing in outside of Shishio arena
// TODO: better track who didn't take Shishio towers
// TODO: does Gorai Torching Torment cleave?
// TODO: who missed Gorai towers or was not hit by protean

export type Data = OopsyData;

const triggerSet: OopsyTriggerSet<Data> = {
  zoneId: ZoneId.AnotherMountRokkonSavage,
  damageWarn: {
    // Trash 1
    'AMRS Shishu Raiko Disciples of Levin': 'TODO', // centered circle
    'AMRS Shishu Raiko Master of Levin': 'TODO', // very large donut
    'AMRS Shishu Furutsubaki Bloody Carress': 'TODO', // front conal
    'AMRS Shishu Fuko Scythe Tail': 'TODO', // centered circle
    'AMRS Red Shishu Penghou Tornado': 'TODO', // targeted circle
    'AMRS Shishu Yuki Right Swipe': 'TODO', // 180 right cleave
    'AMRS Shishu Yuki Left Swipe': 'TODO', // 180 left cleave

    // Shishio
    'AMRS Shishio Rokujo Revel': 'TODO', // Smokeater line
    'AMRS Shishio Raiun Leaping Levin 1': 'TODO', // Raiun 1x Smokeater small cloud circles
    'AMRS Shishio Raiun Leaping Levin 2': 'TODO', // Raiun 1x Smokeater medium cloud circles
    'AMRS Shishio Raiun Leaping Levin 3': 'TODO', // Raiun 1x Smokeater large cloud circles
    'AMRS Shishio Lightning Bolt': 'TODO', // initial Cloud to Cloud circles
    'AMRS Shishio Cloud to Cloud 1': 'TODO', // 1x Smokeater small lines
    'AMRS Shishio Cloud to Cloud 2': 'TODO', // 2x Smokeater medium lines
    'AMRS Shishio Cloud to Cloud 3': 'TODO', // 3x Smokeater large lines
    'AMRS Shishio Noble Pursuit 1': 'TODO', // initial charge line
    'AMRS Shishio Noble Pursuit 2': 'TODO', // followup charge line
    'AMRS Shishio Levinburst': 'TODO', // line damage during Noble Pursuit
    'AMRS Shishio Devilish Thrall Right Swipe': 'TODO', // 180 right cleave from adds
    'AMRS Shishio Devilish Thrall Left Swipe': 'TODO', // 180 left cleave from adds
    'AMRS Shishio Haunting Thrall Reisho': 'TODO', // untelegraphed white explosions from Thralls
    'AMRS Shishio Thunder Vortex': 'TODO', // donut
    'AMRS Shishio Eye of the Thunder Vortex 1': 'TODO', // first "out" circle
    'AMRS Shishio Eye of the Thunder Vortex 2': 'TODO', // second "in" donut
    'AMRS Shishio Vortex of the Thunder Eye 1': 'TODO', // first "in" donut
    'AMRS Shishio Vortex of the Thunder Eye 2': 'TODO', // second "out" circle
    'AMRS Shishio Slither': 'TODO', // back conal

    // Trash 2
    'AMRS Shishu Yamabiko': 'TODO', // sprite line aoe
    'AMRS Shishu Kotengu Blade of the Tengu': 'TODO', // Leftward/Rightward/Backward Blows
    'AMRS Shishu Onmitsugashira Juji Shuriken': 'TODO', // untelegraphed front line
    'AMRS Shishu Onmitsugashira Juji Shuriken Huton': 'TODO', // untelegraphed fast front line on all players

    // Gorai
    'AMRS Gorai Fire Spread Purple': 'TODO', // line damage after purple Brazen Ballad
    'AMRS Gorai Fire Spread Blue': 'TODO', // line damage after blue Brazen Ballad
    'AMRS Gorai Falling Rock Purple': 'TODO', // expanded rock damage after purple Brazen Ballad
    'AMRS Gorai Falling Rock Blue': 'TODO', // donutified rock damage after purple Brazen Ballad
    'AMRS Gorai Ball of Levin Shock Small': 'TODO', // small circle from Ball of Levin hit by Humble Hammer
    'AMRS Gorai Ball of Levin Shock Big': 'TODO', // large circle from Ball of Levin
    'AMRS Gorai Cloud to Ground 1': 'TODO', // initial cloud exaflare
    'AMRS Gorai Cloud to Ground 2': 'TODO', // ongoing cloud exaflare
    'AMRS Gorai Impure Purgation Second': 'TODO', // follow-up protean
  },
  damageFail: {
    'AMRS Shishio Unmitigated Explosion': 'TODO', // not taking towers
  },
  gainsEffectWarn: {
    // BF9 = 9999s duration, BFA = 15s duration
    'AMRS Gorai Burns': 'BF9', // standing in outside square of Gorai
  },
  shareWarn: {
    'AMRS Shishu Raiko Barreling Smash': 'TODO', // line charge
    'AMRS Gorai Pointed Purgation': 'TODO', // protean tether during towers
    'AMRS Gorai Impure Purgation': 'TODO', // initial protean for double hit protean
  },
  shareFail: {
    'AMRS Shishio Unnatural Ailment': 'TODO', // spread during Unnatural Wail
    'AMRS Gorai Great Ball of Fire': 'TODO', // spread damage from Live Candle debuff
  },
  soloFail: {
    'AMRS Shishio Unnatural Force': 'TODO', // pair stack during Unnatural Wail
    'AMRS Gorai Greater Ball of Fire': 'TODO', // pair stack from Live Brazier debuff
    'AMRS Gorai Flintlock': 'TODO', // line share
  },
  triggers: [
    {
      id: 'AMRS Shishu Kotengu Gaze of the Tengu',
      type: 'Ability',
      netRegex: NetRegexes.ability({ id: 'TODO', ...playerDamageFields }),
      condition: (data, matches) => data.DamageFromMatches(matches) > 0,
      mistake: (_data, matches) => {
        return {
          type: 'fail',
          blame: matches.target,
          reportId: matches.targetId,
          text: matches.ability,
        };
      },
    },
  ],
};

export default triggerSet;
