name: JSON Lint

on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '**/*.json'
      - '.github/workflows/json-lint.yml'
  pull_request:
    paths:
      - '*.json'
      - '**/*.json'
      - '.github/workflows/json-lint.yml'

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci --ignore-scripts

      - name: Run dprint for json files
        run: |
          npx --no-install dprint check '**/*.json'
