name: Auto Label

on:
  pull_request_target:
    types: [ opened, synchronize ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Extract Yarn Cache
        run: |
          yarn

      - name: Run Label Script
        run: |
          node .github/scripts/auto-label.cjs
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_NUMBER: ${{ github.event.number }}
