name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run markdownlint
