name: Markdown Lint

on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    paths:
      - '*.json'
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"

      - name: Extract Yarn Cache
        run: |
          yarn install

      - name: yarn run markdownlint
        run: |
          yarn run markdownlint
