name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"
      - name: Install Dependencies
        run: |
          npm install
      - name: npm run markdownlint
        run: |
          npm run markdownlint
