name: Markdown Lint

on:
  push:
    branches:
      - main
    paths:
      - '*.json'
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    paths:
      - '*.json'
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"

      - name: Extract Yarn Cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: yarn run markdownlint
        run: |
          yarn run markdownlint
