name: Post-Process Test

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'
      - '.github/actions/setup-js-env/'
  pull_request:
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'
      - '.github/actions/setup-js-env/'

jobs:
  postprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-js-env

      - name: npm run coverage-report
        run: |
          npm run coverage-report

      - name: npm run process-triggers
        run: |
          npm run process-triggers
