name: Post-Process Test

on:
  push:
    branches:
      - main
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'
  pull_request:
    paths:
      - 'resources/**'
      - 'ui/raidboss/**'
      - 'ui/oopsyraidsy/**'
      - 'util/**'
      - '.github/workflows/post-process.yml'

jobs:
  postprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Extract Yarn Cache
        run: |
          yarn

      - name: yarn run coverage-report
        run: |
          yarn run coverage-report

      - name: yarn run process-triggers
        run: |
          yarn run process-triggers
