name: Python Lint

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'
      - 'requirements.txt'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: black **/*.py --line-length 100 --check --diff
        run: |
          black **/*.py --line-length 100 --check --diff

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: pylint **/*.py --errors-only
        run: |
          pylint **/*.py --errors-only
