name: Python Lint

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Dependencies
        run: |
          pip install black==19.10b0
      - name: black **/*.py --line-length 100 --check --diff
        run: |
          black **/*.py --line-length 100 --check --diff
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"
      - name: Install Dependencies
        run: | # TODO: Update pylint version to one that natively caps isort dependency
          pip install pylint==2.2.3 isort==4.3.21 PyYAML requests
      - name: pylint **/*.py --errors-only
        run: |
          pylint **/*.py --errors-only
