name: Python Lint

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/python-lint.yml'
      - 'requirements.txt'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      # Cache pip dependencies
      # See also: https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Get pip cache dir
        id: pip-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.pip-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: black **/*.py --line-length 100 --check --diff
        run: |
          black **/*.py --line-length 100 --check --diff

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Add Custom Problem Matcher
        run: |
          echo "::add-matcher::.github/matchers/${{ github.job }}.json"

      # Cache pip dependencies
      # See also: https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Get pip cache dir
        id: pip-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.pip-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: pylint **/*.py --errors-only
        run: |
          pylint **/*.py --errors-only
